
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.abandonment import Abandonment
    from schema.objects.abandonment_email_state_update_user_error import AbandonmentEmailStateUpdateUserError



class AbandonmentEmailStateUpdatePayload(ObjectType):
    class Fields:
        abandonment = ObjectField("abandonment", "Abandonment")
        user_errors = ObjectField("userErrors", "AbandonmentEmailStateUpdateUserError")

    abandonment: "Abandonment"
    user_errors: "AbandonmentEmailStateUpdateUserError"

    