
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.abandonment_update_activities_delivery_statuses_user_error_code import AbandonmentUpdateActivitiesDeliveryStatusesUserErrorCode
    from schema.scalars.string import String



class AbandonmentUpdateActivitiesDeliveryStatusesUserError(ObjectType):
    class Fields:
        code = EnumField("code", "AbandonmentUpdateActivitiesDeliveryStatusesUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "AbandonmentUpdateActivitiesDeliveryStatusesUserErrorCode"
    field: "String"
    message: "String"

    