
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.abandoned_checkout_line_item import AbandonedCheckoutLineItem
    from schema.scalars.string import String



class AbandonedCheckoutLineItemEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "AbandonedCheckoutLineItem")

    cursor: "String"
    node: "AbandonedCheckoutLineItem"

    