
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.abandoned_checkout_line_item_connection import AbandonedCheckoutLineItemConnection
    from schema.objects.attribute import Attribute
    from schema.objects.customer import Customer
    from schema.objects.mailing_address import MailingAddress
    from schema.objects.money_bag import MoneyBag
    from schema.objects.tax_line import TaxLine
    from schema.scalars.boolean import Boolean
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.string import String
    from schema.scalars.url import URL



class AbandonedCheckout(ObjectType):
    class Fields:
        abandoned_checkout_url = ScalarField("abandonedCheckoutUrl", "URL")
        billing_address = ObjectField("billingAddress", "MailingAddress")
        completed_at = ScalarField("completedAt", "DateTime")
        created_at = ScalarField("createdAt", "DateTime")
        custom_attributes = ObjectField("customAttributes", "Attribute")
        customer = ObjectField("customer", "Customer")
        default_cursor = ScalarField("defaultCursor", "String")
        discount_codes = ScalarField("discountCodes", "String")
        id = ScalarField("id", "ID")
        line_items = ObjectField("lineItems", "AbandonedCheckoutLineItemConnection")
        line_items_quantity = ScalarField("lineItemsQuantity", "Int")
        name = ScalarField("name", "String")
        note = ScalarField("note", "String")
        shipping_address = ObjectField("shippingAddress", "MailingAddress")
        subtotal_price_set = ObjectField("subtotalPriceSet", "MoneyBag")
        tax_lines = ObjectField("taxLines", "TaxLine")
        taxes_included = ScalarField("taxesIncluded", "Boolean")
        total_discount_set = ObjectField("totalDiscountSet", "MoneyBag")
        total_duties_set = ObjectField("totalDutiesSet", "MoneyBag")
        total_line_items_price_set = ObjectField("totalLineItemsPriceSet", "MoneyBag")
        total_price_set = ObjectField("totalPriceSet", "MoneyBag")
        total_tax_set = ObjectField("totalTaxSet", "MoneyBag")
        updated_at = ScalarField("updatedAt", "DateTime")

    abandoned_checkout_url: "URL"
    billing_address: "MailingAddress"
    completed_at: "DateTime"
    created_at: "DateTime"
    custom_attributes: "Attribute"
    customer: "Customer"
    default_cursor: "String"
    discount_codes: "String"
    id: "ID"
    line_items: "AbandonedCheckoutLineItemConnection"
    line_items_quantity: "Int"
    name: "String"
    note: "String"
    shipping_address: "MailingAddress"
    subtotal_price_set: "MoneyBag"
    tax_lines: "TaxLine"
    taxes_included: "Boolean"
    total_discount_set: "MoneyBag"
    total_duties_set: "MoneyBag"
    total_line_items_price_set: "MoneyBag"
    total_price_set: "MoneyBag"
    total_tax_set: "MoneyBag"
    updated_at: "DateTime"

    