
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.string import String



class AccessScope(ObjectType):
    class Fields:
        description = ScalarField("description", "String")
        handle = ScalarField("handle", "String")

    description: "String"
    handle: "String"

    