
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.boolean import Boolean
    from schema.scalars.id import ID
    from schema.scalars.string import String



class AndroidApplication(ObjectType):
    class Fields:
        app_links_enabled = ScalarField("appLinksEnabled", "Boolean")
        application_id = ScalarField("applicationId", "String")
        id = ScalarField("id", "ID")
        sha256_cert_fingerprints = ScalarField("sha256CertFingerprints", "String")

    app_links_enabled: "Boolean"
    application_id: "String"
    id: "ID"
    sha256_cert_fingerprints: "String"

    