
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.boolean import Boolean
    from schema.scalars.string import String



class ApiVersion(ObjectType):
    class Fields:
        display_name = ScalarField("displayName", "String")
        handle = ScalarField("handle", "String")
        supported = ScalarField("supported", "Boolean")

    display_name: "String"
    handle: "String"
    supported: "Boolean"

    