
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.app_developer_type import AppDeveloperType
    from schema.enums.app_public_category import AppPublicCategory
    from schema.objects.access_scope import AccessScope
    from schema.objects.app_feedback import AppFeedback
    from schema.objects.app_installation import AppInstallation
    from schema.objects.failed_requirement import FailedRequirement
    from schema.objects.image import Image
    from schema.objects.navigation_item import NavigationItem
    from schema.scalars.boolean import Boolean
    from schema.scalars.id import ID
    from schema.scalars.string import String
    from schema.scalars.url import URL



class App(ObjectType):
    class Fields:
        api_key = ScalarField("apiKey", "String")
        app_store_app_url = ScalarField("appStoreAppUrl", "URL")
        app_store_developer_url = ScalarField("appStoreDeveloperUrl", "URL")
        available_access_scopes = ObjectField("availableAccessScopes", "AccessScope")
        banner = ObjectField("banner", "Image")
        description = ScalarField("description", "String")
        developer_name = ScalarField("developerName", "String")
        developer_type = EnumField("developerType", "AppDeveloperType")
        developer_url = ScalarField("developerUrl", "URL")
        embedded = ScalarField("embedded", "Boolean")
        failed_requirements = ObjectField("failedRequirements", "FailedRequirement")
        features = ScalarField("features", "String")
        feedback = ObjectField("feedback", "AppFeedback")
        handle = ScalarField("handle", "String")
        icon = ObjectField("icon", "Image")
        id = ScalarField("id", "ID")
        install_url = ScalarField("installUrl", "URL")
        installation = ObjectField("installation", "AppInstallation")
        is_post_purchase_app_in_use = ScalarField("isPostPurchaseAppInUse", "Boolean")
        launch_url = ScalarField("launchUrl", "URL")
        navigation_items = ObjectField("navigationItems", "NavigationItem")
        optional_access_scopes = ObjectField("optionalAccessScopes", "AccessScope")
        previously_installed = ScalarField("previouslyInstalled", "Boolean")
        pricing_details = ScalarField("pricingDetails", "String")
        pricing_details_summary = ScalarField("pricingDetailsSummary", "String")
        privacy_policy_url = ScalarField("privacyPolicyUrl", "URL")
        public_category = EnumField("publicCategory", "AppPublicCategory")
        published = ScalarField("published", "Boolean")
        requested_access_scopes = ObjectField("requestedAccessScopes", "AccessScope")
        screenshots = ObjectField("screenshots", "Image")
        shopify_developed = ScalarField("shopifyDeveloped", "Boolean")
        title = ScalarField("title", "String")
        uninstall_message = ScalarField("uninstallMessage", "String")
        uninstall_url = ScalarField("uninstallUrl", "URL")
        webhook_api_version = ScalarField("webhookApiVersion", "String")

    api_key: "String"
    app_store_app_url: "URL"
    app_store_developer_url: "URL"
    available_access_scopes: "AccessScope"
    banner: "Image"
    description: "String"
    developer_name: "String"
    developer_type: "AppDeveloperType"
    developer_url: "URL"
    embedded: "Boolean"
    failed_requirements: "FailedRequirement"
    features: "String"
    feedback: "AppFeedback"
    handle: "String"
    icon: "Image"
    id: "ID"
    install_url: "URL"
    installation: "AppInstallation"
    is_post_purchase_app_in_use: "Boolean"
    launch_url: "URL"
    navigation_items: "NavigationItem"
    optional_access_scopes: "AccessScope"
    previously_installed: "Boolean"
    pricing_details: "String"
    pricing_details_summary: "String"
    privacy_policy_url: "URL"
    public_category: "AppPublicCategory"
    published: "Boolean"
    requested_access_scopes: "AccessScope"
    screenshots: "Image"
    shopify_developed: "Boolean"
    title: "String"
    uninstall_message: "String"
    uninstall_url: "URL"
    webhook_api_version: "String"

    