
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.app_subscription_status import AppSubscriptionStatus
    from schema.objects.app_subscription_line_item import AppSubscriptionLineItem
    from schema.scalars.boolean import Boolean
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.string import String
    from schema.scalars.url import URL



class AppSubscription(ObjectType):
    class Fields:
        created_at = ScalarField("createdAt", "DateTime")
        current_period_end = ScalarField("currentPeriodEnd", "DateTime")
        id = ScalarField("id", "ID")
        line_items = ObjectField("lineItems", "AppSubscriptionLineItem")
        name = ScalarField("name", "String")
        return_url = ScalarField("returnUrl", "URL")
        status = EnumField("status", "AppSubscriptionStatus")
        test = ScalarField("test", "Boolean")
        trial_days = ScalarField("trialDays", "Int")

    created_at: "DateTime"
    current_period_end: "DateTime"
    id: "ID"
    line_items: "AppSubscriptionLineItem"
    name: "String"
    return_url: "URL"
    status: "AppSubscriptionStatus"
    test: "Boolean"
    trial_days: "Int"

    