
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.app_usage_record import AppUsageRecord
    from schema.objects.app_usage_record_edge import AppUsageRecordEdge
    from schema.objects.page_info import PageInfo



class AppUsageRecordConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "AppUsageRecordEdge")
        nodes = ObjectField("nodes", "AppUsageRecord")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "AppUsageRecordEdge"
    nodes: "AppUsageRecord"
    page_info: "PageInfo"

    