
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.app_purchase_one_time import AppPurchaseOneTime
    from schema.scalars.string import String



class AppPurchaseOneTimeEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "AppPurchaseOneTime")

    cursor: "String"
    node: "AppPurchaseOneTime"

    