
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, InterfaceField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.catalog_status import CatalogStatus
    from schema.interfaces.resource_operation import ResourceOperation
    from schema.objects.app_connection import AppConnection
    from schema.objects.price_list import PriceList
    from schema.objects.publication import Publication
    from schema.scalars.id import ID
    from schema.scalars.string import String



class AppCatalog(ObjectType):
    class Fields:
        apps = ObjectField("apps", "AppConnection")
        id = ScalarField("id", "ID")
        operations = InterfaceField("operations", "ResourceOperation")
        price_list = ObjectField("priceList", "PriceList")
        publication = ObjectField("publication", "Publication")
        status = EnumField("status", "CatalogStatus")
        title = ScalarField("title", "String")

    apps: "AppConnection"
    id: "ID"
    operations: "ResourceOperation"
    price_list: "PriceList"
    publication: "Publication"
    status: "CatalogStatus"
    title: "String"

    