
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.access_scope import AccessScope
    from schema.objects.app_revoke_access_scopes_app_revoke_scope_error import AppRevokeAccessScopesAppRevokeScopeError



class AppRevokeAccessScopesPayload(ObjectType):
    class Fields:
        revoked = ObjectField("revoked", "AccessScope")
        user_errors = ObjectField("userErrors", "AppRevokeAccessScopesAppRevokeScopeError")

    revoked: "AccessScope"
    user_errors: "AppRevokeAccessScopesAppRevokeScopeError"

    