
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.money_v2 import MoneyV2
    from schema.scalars.int import Int
    from schema.unions.app_subscription_discount_value import AppSubscriptionDiscountValue



class AppSubscriptionDiscount(ObjectType):
    class Fields:
        duration_limit_in_intervals = ScalarField("durationLimitInIntervals", "Int")
        price_after_discount = ObjectField("priceAfterDiscount", "MoneyV2")
        remaining_duration_in_intervals = ScalarField("remainingDurationInIntervals", "Int")
        value = UnionField("value", "AppSubscriptionDiscountValue")

    duration_limit_in_intervals: "Int"
    price_after_discount: "MoneyV2"
    remaining_duration_in_intervals: "Int"
    value: "AppSubscriptionDiscountValue"

    