
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.app_subscription import AppSubscription
    from schema.objects.user_error import UserError
    from schema.scalars.url import URL



class AppSubscriptionCreatePayload(ObjectType):
    class Fields:
        app_subscription = ObjectField("appSubscription", "AppSubscription")
        confirmation_url = ScalarField("confirmationUrl", "URL")
        user_errors = ObjectField("userErrors", "UserError")

    app_subscription: "AppSubscription"
    confirmation_url: "URL"
    user_errors: "UserError"

    