
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.app_subscription import AppSubscription
    from schema.scalars.string import String



class AppSubscriptionEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "AppSubscription")

    cursor: "String"
    node: "AppSubscription"

    