
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.access_scope import AccessScope
    from schema.objects.app import App
    from schema.objects.app_credit_connection import AppCreditConnection
    from schema.objects.app_purchase_one_time_connection import AppPurchaseOneTimeConnection
    from schema.objects.app_revenue_attribution_record_connection import AppRevenueAttributionRecordConnection
    from schema.objects.app_subscription import AppSubscription
    from schema.objects.app_subscription_connection import AppSubscriptionConnection
    from schema.objects.channel import Channel
    from schema.objects.metafield import Metafield
    from schema.objects.metafield_connection import MetafieldConnection
    from schema.objects.private_metafield import PrivateMetafield
    from schema.objects.private_metafield_connection import PrivateMetafieldConnection
    from schema.objects.publication import Publication
    from schema.scalars.id import ID
    from schema.scalars.url import URL



class AppInstallation(ObjectType):
    class Fields:
        access_scopes = ObjectField("accessScopes", "AccessScope")
        active_subscriptions = ObjectField("activeSubscriptions", "AppSubscription")
        all_subscriptions = ObjectField("allSubscriptions", "AppSubscriptionConnection")
        app = ObjectField("app", "App")
        channel = ObjectField("channel", "Channel")
        credits = ObjectField("credits", "AppCreditConnection")
        id = ScalarField("id", "ID")
        launch_url = ScalarField("launchUrl", "URL")
        metafield = ObjectField("metafield", "Metafield")
        metafields = ObjectField("metafields", "MetafieldConnection")
        one_time_purchases = ObjectField("oneTimePurchases", "AppPurchaseOneTimeConnection")
        private_metafield = ObjectField("privateMetafield", "PrivateMetafield")
        private_metafields = ObjectField("privateMetafields", "PrivateMetafieldConnection")
        publication = ObjectField("publication", "Publication")
        revenue_attribution_records = ObjectField("revenueAttributionRecords", "AppRevenueAttributionRecordConnection")
        subscriptions = ObjectField("subscriptions", "AppSubscription")
        uninstall_url = ScalarField("uninstallUrl", "URL")

    access_scopes: "AccessScope"
    active_subscriptions: "AppSubscription"
    all_subscriptions: "AppSubscriptionConnection"
    app: "App"
    channel: "Channel"
    credits: "AppCreditConnection"
    id: "ID"
    launch_url: "URL"
    metafield: "Metafield"
    metafields: "MetafieldConnection"
    one_time_purchases: "AppPurchaseOneTimeConnection"
    private_metafield: "PrivateMetafield"
    private_metafields: "PrivateMetafieldConnection"
    publication: "Publication"
    revenue_attribution_records: "AppRevenueAttributionRecordConnection"
    subscriptions: "AppSubscription"
    uninstall_url: "URL"

    