
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.unions.app_pricing_details import AppPricingDetails



class AppPlanV2(ObjectType):
    class Fields:
        pricing_details = UnionField("pricingDetails", "AppPricingDetails")

    pricing_details: "AppPricingDetails"

    