
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.app_purchase_one_time import AppPurchaseOneTime
    from schema.objects.app_purchase_one_time_edge import AppPurchaseOneTimeEdge
    from schema.objects.page_info import PageInfo



class AppPurchaseOneTimeConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "AppPurchaseOneTimeEdge")
        nodes = ObjectField("nodes", "AppPurchaseOneTime")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "AppPurchaseOneTimeEdge"
    nodes: "AppPurchaseOneTime"
    page_info: "PageInfo"

    