
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.article_delete_user_error_code import ArticleDeleteUserErrorCode
    from schema.scalars.string import String



class ArticleDeleteUserError(ObjectType):
    class Fields:
        code = EnumField("code", "ArticleDeleteUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "ArticleDeleteUserErrorCode"
    field: "String"
    message: "String"

    