
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.billing_attempt_user_error_code import BillingAttemptUserErrorCode
    from schema.scalars.string import String



class BillingAttemptUserError(ObjectType):
    class Fields:
        code = EnumField("code", "BillingAttemptUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "BillingAttemptUserErrorCode"
    field: "String"
    message: "String"

    