
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.blog_delete_user_error_code import BlogDeleteUserErrorCode
    from schema.scalars.string import String



class BlogDeleteUserError(ObjectType):
    class Fields:
        code = EnumField("code", "BlogDeleteUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "BlogDeleteUserErrorCode"
    field: "String"
    message: "String"

    