
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.blog_delete_user_error import BlogDeleteUserError
    from schema.scalars.id import ID



class BlogDeletePayload(ObjectType):
    class Fields:
        deleted_blog_id = ScalarField("deletedBlogId", "ID")
        user_errors = ObjectField("userErrors", "BlogDeleteUserError")

    deleted_blog_id: "ID"
    user_errors: "BlogDeleteUserError"

    