
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.blog_update_user_error_code import BlogUpdateUserErrorCode
    from schema.scalars.string import String



class BlogUpdateUserError(ObjectType):
    class Fields:
        code = EnumField("code", "BlogUpdateUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "BlogUpdateUserErrorCode"
    field: "String"
    message: "String"

    