
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.blog import Blog
    from schema.objects.blog_edge import BlogEdge
    from schema.objects.page_info import PageInfo



class BlogConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "BlogEdge")
        nodes = ObjectField("nodes", "Blog")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "BlogEdge"
    nodes: "Blog"
    page_info: "PageInfo"

    