
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.string import String
    from schema.scalars.url import URL



class BlogFeed(ObjectType):
    class Fields:
        location = ScalarField("location", "URL")
        path = ScalarField("path", "String")

    location: "URL"
    path: "String"

    