
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.blog_create_user_error_code import BlogCreateUserErrorCode
    from schema.scalars.string import String



class BlogCreateUserError(ObjectType):
    class Fields:
        code = EnumField("code", "BlogCreateUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "BlogCreateUserErrorCode"
    field: "String"
    message: "String"

    