
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.comment_policy import CommentPolicy
    from schema.objects.article_connection import ArticleConnection
    from schema.objects.blog_feed import BlogFeed
    from schema.objects.count import Count
    from schema.objects.event_connection import EventConnection
    from schema.objects.metafield import Metafield
    from schema.objects.metafield_connection import MetafieldConnection
    from schema.objects.metafield_definition_connection import MetafieldDefinitionConnection
    from schema.objects.private_metafield import PrivateMetafield
    from schema.objects.private_metafield_connection import PrivateMetafieldConnection
    from schema.objects.translation import Translation
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.string import String



class Blog(ObjectType):
    class Fields:
        articles = ObjectField("articles", "ArticleConnection")
        articles_count = ObjectField("articlesCount", "Count")
        comment_policy = EnumField("commentPolicy", "CommentPolicy")
        created_at = ScalarField("createdAt", "DateTime")
        events = ObjectField("events", "EventConnection")
        feed = ObjectField("feed", "BlogFeed")
        handle = ScalarField("handle", "String")
        id = ScalarField("id", "ID")
        metafield = ObjectField("metafield", "Metafield")
        metafield_definitions = ObjectField("metafieldDefinitions", "MetafieldDefinitionConnection")
        metafields = ObjectField("metafields", "MetafieldConnection")
        private_metafield = ObjectField("privateMetafield", "PrivateMetafield")
        private_metafields = ObjectField("privateMetafields", "PrivateMetafieldConnection")
        tags = ScalarField("tags", "String")
        template_suffix = ScalarField("templateSuffix", "String")
        title = ScalarField("title", "String")
        translations = ObjectField("translations", "Translation")
        updated_at = ScalarField("updatedAt", "DateTime")

    articles: "ArticleConnection"
    articles_count: "Count"
    comment_policy: "CommentPolicy"
    created_at: "DateTime"
    events: "EventConnection"
    feed: "BlogFeed"
    handle: "String"
    id: "ID"
    metafield: "Metafield"
    metafield_definitions: "MetafieldDefinitionConnection"
    metafields: "MetafieldConnection"
    private_metafield: "PrivateMetafield"
    private_metafields: "PrivateMetafieldConnection"
    tags: "String"
    template_suffix: "String"
    title: "String"
    translations: "Translation"
    updated_at: "DateTime"

    