
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.bulk_mutation_user_error import BulkMutationUserError
    from schema.objects.bulk_operation import BulkOperation



class BulkOperationRunMutationPayload(ObjectType):
    class Fields:
        bulk_operation = ObjectField("bulkOperation", "BulkOperation")
        user_errors = ObjectField("userErrors", "BulkMutationUserError")

    bulk_operation: "BulkOperation"
    user_errors: "BulkMutationUserError"

    