
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.bulk_operation_error_code import BulkOperationErrorCode
    from schema.enums.bulk_operation_status import BulkOperationStatus
    from schema.enums.bulk_operation_type import BulkOperationType
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.string import String
    from schema.scalars.unsigned_int64 import UnsignedInt64
    from schema.scalars.url import URL



class BulkOperation(ObjectType):
    class Fields:
        completed_at = ScalarField("completedAt", "DateTime")
        created_at = ScalarField("createdAt", "DateTime")
        error_code = EnumField("errorCode", "BulkOperationErrorCode")
        file_size = ScalarField("fileSize", "UnsignedInt64")
        id = ScalarField("id", "ID")
        object_count = ScalarField("objectCount", "UnsignedInt64")
        partial_data_url = ScalarField("partialDataUrl", "URL")
        query = ScalarField("query", "String")
        root_object_count = ScalarField("rootObjectCount", "UnsignedInt64")
        status = EnumField("status", "BulkOperationStatus")
        type = EnumField("type", "BulkOperationType")
        url = ScalarField("url", "URL")

    completed_at: "DateTime"
    created_at: "DateTime"
    error_code: "BulkOperationErrorCode"
    file_size: "UnsignedInt64"
    id: "ID"
    object_count: "UnsignedInt64"
    partial_data_url: "URL"
    query: "String"
    root_object_count: "UnsignedInt64"
    status: "BulkOperationStatus"
    type: "BulkOperationType"
    url: "URL"

    