
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.bulk_operation import BulkOperation
    from schema.objects.user_error import UserError



class BulkOperationCancelPayload(ObjectType):
    class Fields:
        bulk_operation = ObjectField("bulkOperation", "BulkOperation")
        user_errors = ObjectField("userErrors", "UserError")

    bulk_operation: "BulkOperation"
    user_errors: "UserError"

    