
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.country_code import CountryCode
    from schema.scalars.string import String



class BusinessEntityAddress(ObjectType):
    class Fields:
        address1 = ScalarField("address1", "String")
        address2 = ScalarField("address2", "String")
        city = ScalarField("city", "String")
        country_code = EnumField("countryCode", "CountryCode")
        province = ScalarField("province", "String")
        zip = ScalarField("zip", "String")

    address1: "String"
    address2: "String"
    city: "String"
    country_code: "CountryCode"
    province: "String"
    zip: "String"

    