
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.business_customer_error_code import BusinessCustomerErrorCode
    from schema.scalars.string import String



class BusinessCustomerUserError(ObjectType):
    class Fields:
        code = EnumField("code", "BusinessCustomerErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "BusinessCustomerErrorCode"
    field: "String"
    message: "String"

    