
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.money_bag import MoneyBag
    from schema.scalars.float import Float
    from schema.scalars.id import ID



class CalculatedRestockingFee(ObjectType):
    class Fields:
        amount_set = ObjectField("amountSet", "MoneyBag")
        id = ScalarField("id", "ID")
        percentage = ScalarField("percentage", "Float")

    amount_set: "MoneyBag"
    id: "ID"
    percentage: "Float"

    