
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, InterfaceField, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.interfaces.calculated_discount_application import CalculatedDiscountApplication
    from schema.objects.calculated_discount_application_edge import CalculatedDiscountApplicationEdge
    from schema.objects.page_info import PageInfo



class CalculatedDiscountApplicationConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "CalculatedDiscountApplicationEdge")
        nodes = InterfaceField("nodes", "CalculatedDiscountApplication")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "CalculatedDiscountApplicationEdge"
    nodes: "CalculatedDiscountApplication"
    page_info: "PageInfo"

    