
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, InterfaceField, ObjectField, ScalarField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.country_code import CountryCode
    from schema.enums.currency_code import CurrencyCode
    from schema.interfaces.draft_order_warning import DraftOrderWarning
    from schema.objects.calculated_draft_order_line_item import CalculatedDraftOrderLineItem
    from schema.objects.customer import Customer
    from schema.objects.draft_order_applied_discount import DraftOrderAppliedDiscount
    from schema.objects.draft_order_platform_discount import DraftOrderPlatformDiscount
    from schema.objects.money_bag import MoneyBag
    from schema.objects.resource_alert import ResourceAlert
    from schema.objects.shipping_line import ShippingLine
    from schema.objects.shipping_rate import ShippingRate
    from schema.objects.tax_line import TaxLine
    from schema.scalars.boolean import Boolean
    from schema.scalars.int import Int
    from schema.scalars.money import Money
    from schema.scalars.string import String
    from schema.unions.purchasing_entity import PurchasingEntity



class CalculatedDraftOrder(ObjectType):
    class Fields:
        accept_automatic_discounts = ScalarField("acceptAutomaticDiscounts", "Boolean")
        alerts = ObjectField("alerts", "ResourceAlert")
        applied_discount = ObjectField("appliedDiscount", "DraftOrderAppliedDiscount")
        available_shipping_rates = ObjectField("availableShippingRates", "ShippingRate")
        billing_address_matches_shipping_address = ScalarField("billingAddressMatchesShippingAddress", "Boolean")
        currency_code = EnumField("currencyCode", "CurrencyCode")
        customer = ObjectField("customer", "Customer")
        discount_codes = ScalarField("discountCodes", "String")
        line_items = ObjectField("lineItems", "CalculatedDraftOrderLineItem")
        line_items_subtotal_price = ObjectField("lineItemsSubtotalPrice", "MoneyBag")
        market_name = ScalarField("marketName", "String")
        market_region_country_code = EnumField("marketRegionCountryCode", "CountryCode")
        phone = ScalarField("phone", "String")
        platform_discounts = ObjectField("platformDiscounts", "DraftOrderPlatformDiscount")
        presentment_currency_code = EnumField("presentmentCurrencyCode", "CurrencyCode")
        purchasing_entity = UnionField("purchasingEntity", "PurchasingEntity")
        shipping_line = ObjectField("shippingLine", "ShippingLine")
        subtotal_price = ScalarField("subtotalPrice", "Money")
        subtotal_price_set = ObjectField("subtotalPriceSet", "MoneyBag")
        tax_lines = ObjectField("taxLines", "TaxLine")
        taxes_included = ScalarField("taxesIncluded", "Boolean")
        total_discounts_set = ObjectField("totalDiscountsSet", "MoneyBag")
        total_line_items_price_set = ObjectField("totalLineItemsPriceSet", "MoneyBag")
        total_price = ScalarField("totalPrice", "Money")
        total_price_set = ObjectField("totalPriceSet", "MoneyBag")
        total_quantity_of_line_items = ScalarField("totalQuantityOfLineItems", "Int")
        total_shipping_price = ScalarField("totalShippingPrice", "Money")
        total_shipping_price_set = ObjectField("totalShippingPriceSet", "MoneyBag")
        total_tax = ScalarField("totalTax", "Money")
        total_tax_set = ObjectField("totalTaxSet", "MoneyBag")
        transformer_fingerprint = ScalarField("transformerFingerprint", "String")
        warnings = InterfaceField("warnings", "DraftOrderWarning")

    accept_automatic_discounts: "Boolean"
    alerts: "ResourceAlert"
    applied_discount: "DraftOrderAppliedDiscount"
    available_shipping_rates: "ShippingRate"
    billing_address_matches_shipping_address: "Boolean"
    currency_code: "CurrencyCode"
    customer: "Customer"
    discount_codes: "String"
    line_items: "CalculatedDraftOrderLineItem"
    line_items_subtotal_price: "MoneyBag"
    market_name: "String"
    market_region_country_code: "CountryCode"
    phone: "String"
    platform_discounts: "DraftOrderPlatformDiscount"
    presentment_currency_code: "CurrencyCode"
    purchasing_entity: "PurchasingEntity"
    shipping_line: "ShippingLine"
    subtotal_price: "Money"
    subtotal_price_set: "MoneyBag"
    tax_lines: "TaxLine"
    taxes_included: "Boolean"
    total_discounts_set: "MoneyBag"
    total_line_items_price_set: "MoneyBag"
    total_price: "Money"
    total_price_set: "MoneyBag"
    total_quantity_of_line_items: "Int"
    total_shipping_price: "Money"
    total_shipping_price_set: "MoneyBag"
    total_tax: "Money"
    total_tax_set: "MoneyBag"
    transformer_fingerprint: "String"
    warnings: "DraftOrderWarning"

    