
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.attribute import Attribute
    from schema.objects.calculated_discount_allocation import CalculatedDiscountAllocation
    from schema.objects.discount_allocation import DiscountAllocation
    from schema.objects.image import Image
    from schema.objects.money_bag import MoneyBag
    from schema.objects.product_variant import ProductVariant
    from schema.scalars.boolean import Boolean
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.string import String
    from schema.unions.order_staged_change import OrderStagedChange



class CalculatedLineItem(ObjectType):
    class Fields:
        calculated_discount_allocations = ObjectField("calculatedDiscountAllocations", "CalculatedDiscountAllocation")
        custom_attributes = ObjectField("customAttributes", "Attribute")
        discount_allocations = ObjectField("discountAllocations", "DiscountAllocation")
        discounted_unit_price_set = ObjectField("discountedUnitPriceSet", "MoneyBag")
        editable_quantity = ScalarField("editableQuantity", "Int")
        editable_quantity_before_changes = ScalarField("editableQuantityBeforeChanges", "Int")
        editable_subtotal_set = ObjectField("editableSubtotalSet", "MoneyBag")
        has_staged_line_item_discount = ScalarField("hasStagedLineItemDiscount", "Boolean")
        id = ScalarField("id", "ID")
        image = ObjectField("image", "Image")
        original_unit_price_set = ObjectField("originalUnitPriceSet", "MoneyBag")
        quantity = ScalarField("quantity", "Int")
        restockable = ScalarField("restockable", "Boolean")
        restocking = ScalarField("restocking", "Boolean")
        sku = ScalarField("sku", "String")
        staged_changes = UnionField("stagedChanges", "OrderStagedChange")
        title = ScalarField("title", "String")
        uneditable_subtotal_set = ObjectField("uneditableSubtotalSet", "MoneyBag")
        variant = ObjectField("variant", "ProductVariant")
        variant_title = ScalarField("variantTitle", "String")

    calculated_discount_allocations: "CalculatedDiscountAllocation"
    custom_attributes: "Attribute"
    discount_allocations: "DiscountAllocation"
    discounted_unit_price_set: "MoneyBag"
    editable_quantity: "Int"
    editable_quantity_before_changes: "Int"
    editable_subtotal_set: "MoneyBag"
    has_staged_line_item_discount: "Boolean"
    id: "ID"
    image: "Image"
    original_unit_price_set: "MoneyBag"
    quantity: "Int"
    restockable: "Boolean"
    restocking: "Boolean"
    sku: "String"
    staged_changes: "OrderStagedChange"
    title: "String"
    uneditable_subtotal_set: "MoneyBag"
    variant: "ProductVariant"
    variant_title: "String"

    