
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.calculated_discount_allocation import CalculatedDiscountAllocation
    from schema.objects.money_bag import MoneyBag
    from schema.objects.product_variant import ProductVariant
    from schema.scalars.id import ID
    from schema.scalars.int import Int



class CalculatedExchangeLineItem(ObjectType):
    class Fields:
        calculated_discount_allocations = ObjectField("calculatedDiscountAllocations", "CalculatedDiscountAllocation")
        discounted_unit_price_set = ObjectField("discountedUnitPriceSet", "MoneyBag")
        id = ScalarField("id", "ID")
        original_unit_price_set = ObjectField("originalUnitPriceSet", "MoneyBag")
        quantity = ScalarField("quantity", "Int")
        subtotal_set = ObjectField("subtotalSet", "MoneyBag")
        total_tax_set = ObjectField("totalTaxSet", "MoneyBag")
        variant = ObjectField("variant", "ProductVariant")

    calculated_discount_allocations: "CalculatedDiscountAllocation"
    discounted_unit_price_set: "MoneyBag"
    id: "ID"
    original_unit_price_set: "MoneyBag"
    quantity: "Int"
    subtotal_set: "MoneyBag"
    total_tax_set: "MoneyBag"
    variant: "ProductVariant"

    