
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.calculated_restocking_fee import CalculatedRestockingFee
    from schema.objects.fulfillment_line_item import FulfillmentLineItem
    from schema.objects.money_bag import MoneyBag
    from schema.scalars.id import ID
    from schema.scalars.int import Int



class CalculatedReturnLineItem(ObjectType):
    class Fields:
        fulfillment_line_item = ObjectField("fulfillmentLineItem", "FulfillmentLineItem")
        id = ScalarField("id", "ID")
        quantity = ScalarField("quantity", "Int")
        restocking_fee = ObjectField("restockingFee", "CalculatedRestockingFee")
        subtotal_before_order_discounts_set = ObjectField("subtotalBeforeOrderDiscountsSet", "MoneyBag")
        subtotal_set = ObjectField("subtotalSet", "MoneyBag")
        total_tax_set = ObjectField("totalTaxSet", "MoneyBag")

    fulfillment_line_item: "FulfillmentLineItem"
    id: "ID"
    quantity: "Int"
    restocking_fee: "CalculatedRestockingFee"
    subtotal_before_order_discounts_set: "MoneyBag"
    subtotal_set: "MoneyBag"
    total_tax_set: "MoneyBag"

    