
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.carrier_service_create_user_error import CarrierServiceCreateUserError
    from schema.objects.delivery_carrier_service import DeliveryCarrierService



class CarrierServiceCreatePayload(ObjectType):
    class Fields:
        carrier_service = ObjectField("carrierService", "DeliveryCarrierService")
        user_errors = ObjectField("userErrors", "CarrierServiceCreateUserError")

    carrier_service: "DeliveryCarrierService"
    user_errors: "CarrierServiceCreateUserError"

    