
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.carrier_service_update_user_error_code import CarrierServiceUpdateUserErrorCode
    from schema.scalars.string import String



class CarrierServiceUpdateUserError(ObjectType):
    class Fields:
        code = EnumField("code", "CarrierServiceUpdateUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "CarrierServiceUpdateUserErrorCode"
    field: "String"
    message: "String"

    