
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.carrier_service_delete_user_error_code import CarrierServiceDeleteUserErrorCode
    from schema.scalars.string import String



class CarrierServiceDeleteUserError(ObjectType):
    class Fields:
        code = EnumField("code", "CarrierServiceDeleteUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "CarrierServiceDeleteUserErrorCode"
    field: "String"
    message: "String"

    