
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.cart_transform import CartTransform
    from schema.objects.cart_transform_create_user_error import CartTransformCreateUserError



class CartTransformCreatePayload(ObjectType):
    class Fields:
        cart_transform = ObjectField("cartTransform", "CartTransform")
        user_errors = ObjectField("userErrors", "CartTransformCreateUserError")

    cart_transform: "CartTransform"
    user_errors: "CartTransformCreateUserError"

    