
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.cart_transform import CartTransform
    from schema.objects.cart_transform_edge import CartTransformEdge
    from schema.objects.page_info import PageInfo



class CartTransformConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "CartTransformEdge")
        nodes = ObjectField("nodes", "CartTransform")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "CartTransformEdge"
    nodes: "CartTransform"
    page_info: "PageInfo"

    