
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.cart_transform_delete_user_error_code import CartTransformDeleteUserErrorCode
    from schema.scalars.string import String



class CartTransformDeleteUserError(ObjectType):
    class Fields:
        code = EnumField("code", "CartTransformDeleteUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "CartTransformDeleteUserErrorCode"
    field: "String"
    message: "String"

    