
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.cash_tracking_session import CashTrackingSession
    from schema.objects.cash_tracking_session_edge import CashTrackingSessionEdge
    from schema.objects.page_info import PageInfo



class CashTrackingSessionConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "CashTrackingSessionEdge")
        nodes = ObjectField("nodes", "CashTrackingSession")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "CashTrackingSessionEdge"
    nodes: "CashTrackingSession"
    page_info: "PageInfo"

    