
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.catalog_user_error import CatalogUserError
    from schema.scalars.id import ID



class CatalogDeletePayload(ObjectType):
    class Fields:
        deleted_id = ScalarField("deletedId", "ID")
        user_errors = ObjectField("userErrors", "CatalogUserError")

    deleted_id: "ID"
    user_errors: "CatalogUserError"

    