
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.channel import Channel
    from schema.objects.channel_edge import ChannelEdge
    from schema.objects.page_info import PageInfo



class ChannelConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "ChannelEdge")
        nodes = ObjectField("nodes", "Channel")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "ChannelEdge"
    nodes: "Channel"
    page_info: "PageInfo"

    