
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.checkout_branding_color_scheme_selection import CheckoutBrandingColorSchemeSelection
    from schema.objects.checkout_branding_container_divider import CheckoutBrandingContainerDivider
    from schema.objects.checkout_branding_image import CheckoutBrandingImage
    from schema.objects.checkout_branding_order_summary_section import CheckoutBrandingOrderSummarySection



class CheckoutBrandingOrderSummary(ObjectType):
    class Fields:
        background_image = ObjectField("backgroundImage", "CheckoutBrandingImage")
        color_scheme = EnumField("colorScheme", "CheckoutBrandingColorSchemeSelection")
        divider = ObjectField("divider", "CheckoutBrandingContainerDivider")
        section = ObjectField("section", "CheckoutBrandingOrderSummarySection")

    background_image: "CheckoutBrandingImage"
    color_scheme: "CheckoutBrandingColorSchemeSelection"
    divider: "CheckoutBrandingContainerDivider"
    section: "CheckoutBrandingOrderSummarySection"

    