
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.checkout_branding_border_style import CheckoutBrandingBorderStyle
    from schema.enums.checkout_branding_border_width import CheckoutBrandingBorderWidth
    from schema.enums.checkout_branding_visibility import CheckoutBrandingVisibility



class CheckoutBrandingContainerDivider(ObjectType):
    class Fields:
        border_style = EnumField("borderStyle", "CheckoutBrandingBorderStyle")
        border_width = EnumField("borderWidth", "CheckoutBrandingBorderWidth")
        visibility = EnumField("visibility", "CheckoutBrandingVisibility")

    border_style: "CheckoutBrandingBorderStyle"
    border_width: "CheckoutBrandingBorderWidth"
    visibility: "CheckoutBrandingVisibility"

    