
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.checkout_profile import CheckoutProfile
    from schema.scalars.string import String



class CheckoutProfileEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "CheckoutProfile")

    cursor: "String"
    node: "CheckoutProfile"

    