
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.checkout_branding import CheckoutBranding
    from schema.objects.checkout_branding_upsert_user_error import CheckoutBrandingUpsertUserError



class CheckoutBrandingUpsertPayload(ObjectType):
    class Fields:
        checkout_branding = ObjectField("checkoutBranding", "CheckoutBranding")
        user_errors = ObjectField("userErrors", "CheckoutBrandingUpsertUserError")

    checkout_branding: "CheckoutBranding"
    user_errors: "CheckoutBrandingUpsertUserError"

    