
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.float import Float



class CheckoutBrandingFontSize(ObjectType):
    class Fields:
        base = ScalarField("base", "Float")
        ratio = ScalarField("ratio", "Float")

    base: "Float"
    ratio: "Float"

    