
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.checkout_branding_typography_style import CheckoutBrandingTypographyStyle



class CheckoutBrandingHeadingLevel(ObjectType):
    class Fields:
        typography = ObjectField("typography", "CheckoutBrandingTypographyStyle")

    typography: "CheckoutBrandingTypographyStyle"

    