
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.checkout_branding_typography_kerning import CheckoutBrandingTypographyKerning
    from schema.enums.checkout_branding_typography_letter_case import CheckoutBrandingTypographyLetterCase



class CheckoutBrandingTypographyStyleGlobal(ObjectType):
    class Fields:
        kerning = EnumField("kerning", "CheckoutBrandingTypographyKerning")
        letter_case = EnumField("letterCase", "CheckoutBrandingTypographyLetterCase")

    kerning: "CheckoutBrandingTypographyKerning"
    letter_case: "CheckoutBrandingTypographyLetterCase"

    