
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.checkout_branding_border import CheckoutBrandingBorder
    from schema.objects.checkout_branding_typography_style import CheckoutBrandingTypographyStyle



class CheckoutBrandingTextField(ObjectType):
    class Fields:
        border = EnumField("border", "CheckoutBrandingBorder")
        typography = ObjectField("typography", "CheckoutBrandingTypographyStyle")

    border: "CheckoutBrandingBorder"
    typography: "CheckoutBrandingTypographyStyle"

    