
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.checkout_branding_container_divider import CheckoutBrandingContainerDivider



class CheckoutBrandingContent(ObjectType):
    class Fields:
        divider = ObjectField("divider", "CheckoutBrandingContainerDivider")

    divider: "CheckoutBrandingContainerDivider"

    