
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.int import Int



class CheckoutBrandingCornerRadiusVariables(ObjectType):
    class Fields:
        base = ScalarField("base", "Int")
        large = ScalarField("large", "Int")
        small = ScalarField("small", "Int")

    base: "Int"
    large: "Int"
    small: "Int"

    