
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.checkout_branding_font_group import CheckoutBrandingFontGroup
    from schema.objects.checkout_branding_font_size import CheckoutBrandingFontSize



class CheckoutBrandingTypography(ObjectType):
    class Fields:
        primary = ObjectField("primary", "CheckoutBrandingFontGroup")
        secondary = ObjectField("secondary", "CheckoutBrandingFontGroup")
        size = ObjectField("size", "CheckoutBrandingFontSize")

    primary: "CheckoutBrandingFontGroup"
    secondary: "CheckoutBrandingFontGroup"
    size: "CheckoutBrandingFontSize"

    