
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.checkout_branding_spacing_keyword import CheckoutBrandingSpacingKeyword



class CheckoutBrandingChoiceListGroup(ObjectType):
    class Fields:
        spacing = EnumField("spacing", "CheckoutBrandingSpacingKeyword")

    spacing: "CheckoutBrandingSpacingKeyword"

    