
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.shop import Shop
    from schema.objects.user_error import UserError
    from schema.scalars.id import ID



class CollectionDeletePayload(ObjectType):
    class Fields:
        deleted_collection_id = ScalarField("deletedCollectionId", "ID")
        shop = ObjectField("shop", "Shop")
        user_errors = ObjectField("userErrors", "UserError")

    deleted_collection_id: "ID"
    shop: "Shop"
    user_errors: "UserError"

    