
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.collection_sort_order import CollectionSortOrder
    from schema.objects.channel_connection import ChannelConnection
    from schema.objects.collection_publication_connection import CollectionPublicationConnection
    from schema.objects.collection_rule_set import CollectionRuleSet
    from schema.objects.count import Count
    from schema.objects.event_connection import EventConnection
    from schema.objects.image import Image
    from schema.objects.metafield import Metafield
    from schema.objects.metafield_connection import MetafieldConnection
    from schema.objects.metafield_definition_connection import MetafieldDefinitionConnection
    from schema.objects.private_metafield import PrivateMetafield
    from schema.objects.private_metafield_connection import PrivateMetafieldConnection
    from schema.objects.product_connection import ProductConnection
    from schema.objects.publication_connection import PublicationConnection
    from schema.objects.resource_feedback import ResourceFeedback
    from schema.objects.resource_publication_connection import ResourcePublicationConnection
    from schema.objects.resource_publication_v2_connection import ResourcePublicationV2Connection
    from schema.objects.seo import SEO
    from schema.objects.translation import Translation
    from schema.scalars.boolean import Boolean
    from schema.scalars.date_time import DateTime
    from schema.scalars.html import HTML
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.storefront_i_d import StorefrontID
    from schema.scalars.string import String
    from schema.scalars.unsigned_int64 import UnsignedInt64



class Collection(ObjectType):
    class Fields:
        available_publications_count = ObjectField("availablePublicationsCount", "Count")
        description = ScalarField("description", "String")
        description_html = ScalarField("descriptionHtml", "HTML")
        events = ObjectField("events", "EventConnection")
        feedback = ObjectField("feedback", "ResourceFeedback")
        handle = ScalarField("handle", "String")
        has_product = ScalarField("hasProduct", "Boolean")
        id = ScalarField("id", "ID")
        image = ObjectField("image", "Image")
        legacy_resource_id = ScalarField("legacyResourceId", "UnsignedInt64")
        metafield = ObjectField("metafield", "Metafield")
        metafield_definitions = ObjectField("metafieldDefinitions", "MetafieldDefinitionConnection")
        metafields = ObjectField("metafields", "MetafieldConnection")
        private_metafield = ObjectField("privateMetafield", "PrivateMetafield")
        private_metafields = ObjectField("privateMetafields", "PrivateMetafieldConnection")
        products = ObjectField("products", "ProductConnection")
        products_count = ObjectField("productsCount", "Count")
        publication_count = ScalarField("publicationCount", "Int")
        publications = ObjectField("publications", "CollectionPublicationConnection")
        published_on_channel = ScalarField("publishedOnChannel", "Boolean")
        published_on_current_channel = ScalarField("publishedOnCurrentChannel", "Boolean")
        published_on_current_publication = ScalarField("publishedOnCurrentPublication", "Boolean")
        published_on_publication = ScalarField("publishedOnPublication", "Boolean")
        resource_publications = ObjectField("resourcePublications", "ResourcePublicationConnection")
        resource_publications_count = ObjectField("resourcePublicationsCount", "Count")
        resource_publications_v2 = ObjectField("resourcePublicationsV2", "ResourcePublicationV2Connection")
        rule_set = ObjectField("ruleSet", "CollectionRuleSet")
        seo = ObjectField("seo", "SEO")
        sort_order = EnumField("sortOrder", "CollectionSortOrder")
        storefront_id = ScalarField("storefrontId", "StorefrontID")
        template_suffix = ScalarField("templateSuffix", "String")
        title = ScalarField("title", "String")
        translations = ObjectField("translations", "Translation")
        unpublished_channels = ObjectField("unpublishedChannels", "ChannelConnection")
        unpublished_publications = ObjectField("unpublishedPublications", "PublicationConnection")
        updated_at = ScalarField("updatedAt", "DateTime")

    available_publications_count: "Count"
    description: "String"
    description_html: "HTML"
    events: "EventConnection"
    feedback: "ResourceFeedback"
    handle: "String"
    has_product: "Boolean"
    id: "ID"
    image: "Image"
    legacy_resource_id: "UnsignedInt64"
    metafield: "Metafield"
    metafield_definitions: "MetafieldDefinitionConnection"
    metafields: "MetafieldConnection"
    private_metafield: "PrivateMetafield"
    private_metafields: "PrivateMetafieldConnection"
    products: "ProductConnection"
    products_count: "Count"
    publication_count: "Int"
    publications: "CollectionPublicationConnection"
    published_on_channel: "Boolean"
    published_on_current_channel: "Boolean"
    published_on_current_publication: "Boolean"
    published_on_publication: "Boolean"
    resource_publications: "ResourcePublicationConnection"
    resource_publications_count: "Count"
    resource_publications_v2: "ResourcePublicationV2Connection"
    rule_set: "CollectionRuleSet"
    seo: "SEO"
    sort_order: "CollectionSortOrder"
    storefront_id: "StorefrontID"
    template_suffix: "String"
    title: "String"
    translations: "Translation"
    unpublished_channels: "ChannelConnection"
    unpublished_publications: "PublicationConnection"
    updated_at: "DateTime"

    