
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.taxonomy_category import TaxonomyCategory



class CollectionRuleCategoryCondition(ObjectType):
    class Fields:
        value = ObjectField("value", "TaxonomyCategory")

    value: "TaxonomyCategory"

    