
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.channel import Channel
    from schema.objects.collection import Collection
    from schema.objects.publication import Publication
    from schema.scalars.boolean import Boolean
    from schema.scalars.date_time import DateTime



class CollectionPublication(ObjectType):
    class Fields:
        channel = ObjectField("channel", "Channel")
        collection = ObjectField("collection", "Collection")
        is_published = ScalarField("isPublished", "Boolean")
        publication = ObjectField("publication", "Publication")
        publish_date = ScalarField("publishDate", "DateTime")

    channel: "Channel"
    collection: "Collection"
    is_published: "Boolean"
    publication: "Publication"
    publish_date: "DateTime"

    