
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.combined_listing_child import CombinedListingChild
    from schema.objects.combined_listing_child_edge import CombinedListingChildEdge
    from schema.objects.page_info import PageInfo



class CombinedListingChildConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "CombinedListingChildEdge")
        nodes = ObjectField("nodes", "CombinedListingChild")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "CombinedListingChildEdge"
    nodes: "CombinedListingChild"
    page_info: "PageInfo"

    