
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.product import Product
    from schema.objects.product_variant import ProductVariant



class CombinedListingChild(ObjectType):
    class Fields:
        parent_variant = ObjectField("parentVariant", "ProductVariant")
        product = ObjectField("product", "Product")

    parent_variant: "ProductVariant"
    product: "Product"

    