
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.combined_listing_child_connection import CombinedListingChildConnection
    from schema.objects.product import Product



class CombinedListing(ObjectType):
    class Fields:
        combined_listing_children = ObjectField("combinedListingChildren", "CombinedListingChildConnection")
        parent_product = ObjectField("parentProduct", "Product")

    combined_listing_children: "CombinedListingChildConnection"
    parent_product: "Product"

    