
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.string import String



class CommentAuthor(ObjectType):
    class Fields:
        email = ScalarField("email", "String")
        name = ScalarField("name", "String")

    email: "String"
    name: "String"

    