
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.comment_delete_user_error import CommentDeleteUserError
    from schema.scalars.id import ID



class CommentDeletePayload(ObjectType):
    class Fields:
        deleted_comment_id = ScalarField("deletedCommentId", "ID")
        user_errors = ObjectField("userErrors", "CommentDeleteUserError")

    deleted_comment_id: "ID"
    user_errors: "CommentDeleteUserError"

    