
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.comment_not_spam_user_error_code import CommentNotSpamUserErrorCode
    from schema.scalars.string import String



class CommentNotSpamUserError(ObjectType):
    class Fields:
        code = EnumField("code", "CommentNotSpamUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "CommentNotSpamUserErrorCode"
    field: "String"
    message: "String"

    