
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.comment_status import CommentStatus
    from schema.objects.article import Article
    from schema.objects.comment_author import CommentAuthor
    from schema.objects.event_connection import EventConnection
    from schema.scalars.boolean import Boolean
    from schema.scalars.date_time import DateTime
    from schema.scalars.html import HTML
    from schema.scalars.id import ID
    from schema.scalars.string import String



class Comment(ObjectType):
    class Fields:
        article = ObjectField("article", "Article")
        author = ObjectField("author", "CommentAuthor")
        body = ScalarField("body", "String")
        body_html = ScalarField("bodyHtml", "HTML")
        created_at = ScalarField("createdAt", "DateTime")
        events = ObjectField("events", "EventConnection")
        id = ScalarField("id", "ID")
        ip = ScalarField("ip", "String")
        is_published = ScalarField("isPublished", "Boolean")
        published_at = ScalarField("publishedAt", "DateTime")
        status = EnumField("status", "CommentStatus")
        updated_at = ScalarField("updatedAt", "DateTime")
        user_agent = ScalarField("userAgent", "String")

    article: "Article"
    author: "CommentAuthor"
    body: "String"
    body_html: "HTML"
    created_at: "DateTime"
    events: "EventConnection"
    id: "ID"
    ip: "String"
    is_published: "Boolean"
    published_at: "DateTime"
    status: "CommentStatus"
    updated_at: "DateTime"
    user_agent: "String"

    