
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.company import Company
    from schema.objects.company_contact import CompanyContact
    from schema.objects.company_contact_role import CompanyContactRole
    from schema.objects.company_location import CompanyLocation
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID



class CompanyContactRoleAssignment(ObjectType):
    class Fields:
        company = ObjectField("company", "Company")
        company_contact = ObjectField("companyContact", "CompanyContact")
        company_location = ObjectField("companyLocation", "CompanyLocation")
        created_at = ScalarField("createdAt", "DateTime")
        id = ScalarField("id", "ID")
        role = ObjectField("role", "CompanyContactRole")
        updated_at = ScalarField("updatedAt", "DateTime")

    company: "Company"
    company_contact: "CompanyContact"
    company_location: "CompanyLocation"
    created_at: "DateTime"
    id: "ID"
    role: "CompanyContactRole"
    updated_at: "DateTime"

    