
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.company_contact_role_assignment import CompanyContactRoleAssignment
    from schema.objects.company_contact_role_assignment_edge import CompanyContactRoleAssignmentEdge
    from schema.objects.page_info import PageInfo



class CompanyContactRoleAssignmentConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "CompanyContactRoleAssignmentEdge")
        nodes = ObjectField("nodes", "CompanyContactRoleAssignment")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "CompanyContactRoleAssignmentEdge"
    nodes: "CompanyContactRoleAssignment"
    page_info: "PageInfo"

    