
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.company_location_staff_member_assignment import CompanyLocationStaffMemberAssignment
    from schema.scalars.string import String



class CompanyLocationStaffMemberAssignmentEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "CompanyLocationStaffMemberAssignment")

    cursor: "String"
    node: "CompanyLocationStaffMemberAssignment"

    