
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.company_contact import CompanyContact
    from schema.scalars.string import String



class CompanyContactEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "CompanyContact")

    cursor: "String"
    node: "CompanyContact"

    