
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.company_location import CompanyLocation
    from schema.objects.company_location_edge import CompanyLocationEdge
    from schema.objects.page_info import PageInfo



class CompanyLocationConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "CompanyLocationEdge")
        nodes = ObjectField("nodes", "CompanyLocation")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "CompanyLocationEdge"
    nodes: "CompanyLocation"
    page_info: "PageInfo"

    