
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.business_customer_user_error import BusinessCustomerUserError
    from schema.scalars.id import ID



class CompaniesDeletePayload(ObjectType):
    class Fields:
        deleted_company_ids = ScalarField("deletedCompanyIds", "ID")
        user_errors = ObjectField("userErrors", "BusinessCustomerUserError")

    deleted_company_ids: "ID"
    user_errors: "BusinessCustomerUserError"

    