
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.company_contact_role import CompanyContactRole
    from schema.scalars.string import String



class CompanyContactRoleEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "CompanyContactRole")

    cursor: "String"
    node: "CompanyContactRole"

    