
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.currency_code import CurrencyCode
    from schema.enums.tax_exemption import TaxExemption
    from schema.objects.buyer_experience_configuration import BuyerExperienceConfiguration
    from schema.objects.catalog_connection import CatalogConnection
    from schema.objects.company import Company
    from schema.objects.company_address import CompanyAddress
    from schema.objects.company_contact_role_assignment_connection import CompanyContactRoleAssignmentConnection
    from schema.objects.company_location_staff_member_assignment_connection import CompanyLocationStaffMemberAssignmentConnection
    from schema.objects.count import Count
    from schema.objects.draft_order_connection import DraftOrderConnection
    from schema.objects.event_connection import EventConnection
    from schema.objects.market import Market
    from schema.objects.metafield import Metafield
    from schema.objects.metafield_connection import MetafieldConnection
    from schema.objects.metafield_definition_connection import MetafieldDefinitionConnection
    from schema.objects.money_v2 import MoneyV2
    from schema.objects.order_connection import OrderConnection
    from schema.objects.private_metafield import PrivateMetafield
    from schema.objects.private_metafield_connection import PrivateMetafieldConnection
    from schema.scalars.boolean import Boolean
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.string import String



class CompanyLocation(ObjectType):
    class Fields:
        billing_address = ObjectField("billingAddress", "CompanyAddress")
        buyer_experience_configuration = ObjectField("buyerExperienceConfiguration", "BuyerExperienceConfiguration")
        catalogs = ObjectField("catalogs", "CatalogConnection")
        catalogs_count = ObjectField("catalogsCount", "Count")
        company = ObjectField("company", "Company")
        created_at = ScalarField("createdAt", "DateTime")
        currency = EnumField("currency", "CurrencyCode")
        default_cursor = ScalarField("defaultCursor", "String")
        draft_orders = ObjectField("draftOrders", "DraftOrderConnection")
        events = ObjectField("events", "EventConnection")
        external_id = ScalarField("externalId", "String")
        has_timeline_comment = ScalarField("hasTimelineComment", "Boolean")
        id = ScalarField("id", "ID")
        in_catalog = ScalarField("inCatalog", "Boolean")
        locale = ScalarField("locale", "String")
        market = ObjectField("market", "Market")
        metafield = ObjectField("metafield", "Metafield")
        metafield_definitions = ObjectField("metafieldDefinitions", "MetafieldDefinitionConnection")
        metafields = ObjectField("metafields", "MetafieldConnection")
        name = ScalarField("name", "String")
        note = ScalarField("note", "String")
        order_count = ScalarField("orderCount", "Int")
        orders = ObjectField("orders", "OrderConnection")
        orders_count = ObjectField("ordersCount", "Count")
        phone = ScalarField("phone", "String")
        private_metafield = ObjectField("privateMetafield", "PrivateMetafield")
        private_metafields = ObjectField("privateMetafields", "PrivateMetafieldConnection")
        role_assignments = ObjectField("roleAssignments", "CompanyContactRoleAssignmentConnection")
        shipping_address = ObjectField("shippingAddress", "CompanyAddress")
        staff_member_assignments = ObjectField("staffMemberAssignments", "CompanyLocationStaffMemberAssignmentConnection")
        tax_exemptions = EnumField("taxExemptions", "TaxExemption")
        tax_registration_id = ScalarField("taxRegistrationId", "String")
        total_spent = ObjectField("totalSpent", "MoneyV2")
        updated_at = ScalarField("updatedAt", "DateTime")

    billing_address: "CompanyAddress"
    buyer_experience_configuration: "BuyerExperienceConfiguration"
    catalogs: "CatalogConnection"
    catalogs_count: "Count"
    company: "Company"
    created_at: "DateTime"
    currency: "CurrencyCode"
    default_cursor: "String"
    draft_orders: "DraftOrderConnection"
    events: "EventConnection"
    external_id: "String"
    has_timeline_comment: "Boolean"
    id: "ID"
    in_catalog: "Boolean"
    locale: "String"
    market: "Market"
    metafield: "Metafield"
    metafield_definitions: "MetafieldDefinitionConnection"
    metafields: "MetafieldConnection"
    name: "String"
    note: "String"
    order_count: "Int"
    orders: "OrderConnection"
    orders_count: "Count"
    phone: "String"
    private_metafield: "PrivateMetafield"
    private_metafields: "PrivateMetafieldConnection"
    role_assignments: "CompanyContactRoleAssignmentConnection"
    shipping_address: "CompanyAddress"
    staff_member_assignments: "CompanyLocationStaffMemberAssignmentConnection"
    tax_exemptions: "TaxExemption"
    tax_registration_id: "String"
    total_spent: "MoneyV2"
    updated_at: "DateTime"

    