
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.business_customer_user_error import BusinessCustomerUserError
    from schema.objects.company_location import CompanyLocation



class CompanyLocationAssignTaxExemptionsPayload(ObjectType):
    class Fields:
        company_location = ObjectField("companyLocation", "CompanyLocation")
        user_errors = ObjectField("userErrors", "BusinessCustomerUserError")

    company_location: "CompanyLocation"
    user_errors: "BusinessCustomerUserError"

    