
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.business_customer_user_error import BusinessCustomerUserError
    from schema.objects.company import Company



class CompanyUpdatePayload(ObjectType):
    class Fields:
        company = ObjectField("company", "Company")
        user_errors = ObjectField("userErrors", "BusinessCustomerUserError")

    company: "Company"
    user_errors: "BusinessCustomerUserError"

    