
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.company_contact import CompanyContact
    from schema.objects.company_contact_edge import CompanyContactEdge
    from schema.objects.page_info import PageInfo



class CompanyContactConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "CompanyContactEdge")
        nodes = ObjectField("nodes", "CompanyContact")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "CompanyContactEdge"
    nodes: "CompanyContact"
    page_info: "PageInfo"

    