
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.company_contact import CompanyContact
    from schema.objects.company_contact_connection import CompanyContactConnection
    from schema.objects.company_contact_role import CompanyContactRole
    from schema.objects.company_contact_role_connection import CompanyContactRoleConnection
    from schema.objects.company_location_connection import CompanyLocationConnection
    from schema.objects.count import Count
    from schema.objects.draft_order_connection import DraftOrderConnection
    from schema.objects.event_connection import EventConnection
    from schema.objects.metafield import Metafield
    from schema.objects.metafield_connection import MetafieldConnection
    from schema.objects.metafield_definition_connection import MetafieldDefinitionConnection
    from schema.objects.money_v2 import MoneyV2
    from schema.objects.order_connection import OrderConnection
    from schema.objects.private_metafield import PrivateMetafield
    from schema.objects.private_metafield_connection import PrivateMetafieldConnection
    from schema.scalars.boolean import Boolean
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.string import String



class Company(ObjectType):
    class Fields:
        contact_count = ScalarField("contactCount", "Int")
        contact_roles = ObjectField("contactRoles", "CompanyContactRoleConnection")
        contacts = ObjectField("contacts", "CompanyContactConnection")
        contacts_count = ObjectField("contactsCount", "Count")
        created_at = ScalarField("createdAt", "DateTime")
        customer_since = ScalarField("customerSince", "DateTime")
        default_cursor = ScalarField("defaultCursor", "String")
        default_role = ObjectField("defaultRole", "CompanyContactRole")
        draft_orders = ObjectField("draftOrders", "DraftOrderConnection")
        events = ObjectField("events", "EventConnection")
        external_id = ScalarField("externalId", "String")
        has_timeline_comment = ScalarField("hasTimelineComment", "Boolean")
        id = ScalarField("id", "ID")
        lifetime_duration = ScalarField("lifetimeDuration", "String")
        locations = ObjectField("locations", "CompanyLocationConnection")
        locations_count = ObjectField("locationsCount", "Count")
        main_contact = ObjectField("mainContact", "CompanyContact")
        metafield = ObjectField("metafield", "Metafield")
        metafield_definitions = ObjectField("metafieldDefinitions", "MetafieldDefinitionConnection")
        metafields = ObjectField("metafields", "MetafieldConnection")
        name = ScalarField("name", "String")
        note = ScalarField("note", "String")
        orders = ObjectField("orders", "OrderConnection")
        orders_count = ObjectField("ordersCount", "Count")
        private_metafield = ObjectField("privateMetafield", "PrivateMetafield")
        private_metafields = ObjectField("privateMetafields", "PrivateMetafieldConnection")
        total_spent = ObjectField("totalSpent", "MoneyV2")
        updated_at = ScalarField("updatedAt", "DateTime")

    contact_count: "Int"
    contact_roles: "CompanyContactRoleConnection"
    contacts: "CompanyContactConnection"
    contacts_count: "Count"
    created_at: "DateTime"
    customer_since: "DateTime"
    default_cursor: "String"
    default_role: "CompanyContactRole"
    draft_orders: "DraftOrderConnection"
    events: "EventConnection"
    external_id: "String"
    has_timeline_comment: "Boolean"
    id: "ID"
    lifetime_duration: "String"
    locations: "CompanyLocationConnection"
    locations_count: "Count"
    main_contact: "CompanyContact"
    metafield: "Metafield"
    metafield_definitions: "MetafieldDefinitionConnection"
    metafields: "MetafieldConnection"
    name: "String"
    note: "String"
    orders: "OrderConnection"
    orders_count: "Count"
    private_metafield: "PrivateMetafield"
    private_metafields: "PrivateMetafieldConnection"
    total_spent: "MoneyV2"
    updated_at: "DateTime"

    