
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.country_harmonized_system_code import CountryHarmonizedSystemCode
    from schema.objects.country_harmonized_system_code_edge import CountryHarmonizedSystemCodeEdge
    from schema.objects.page_info import PageInfo



class CountryHarmonizedSystemCodeConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "CountryHarmonizedSystemCodeEdge")
        nodes = ObjectField("nodes", "CountryHarmonizedSystemCode")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "CountryHarmonizedSystemCodeEdge"
    nodes: "CountryHarmonizedSystemCode"
    page_info: "PageInfo"

    