
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.country_harmonized_system_code import CountryHarmonizedSystemCode
    from schema.scalars.string import String



class CountryHarmonizedSystemCodeEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "CountryHarmonizedSystemCode")

    cursor: "String"
    node: "CountryHarmonizedSystemCode"

    