
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.currency_setting import CurrencySetting
    from schema.scalars.string import String



class CurrencySettingEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "CurrencySetting")

    cursor: "String"
    node: "CurrencySetting"

    