
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.customer_visit_product_info import CustomerVisitProductInfo
    from schema.objects.customer_visit_product_info_edge import CustomerVisitProductInfoEdge
    from schema.objects.page_info import PageInfo



class CustomerVisitProductInfoConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "CustomerVisitProductInfoEdge")
        nodes = ObjectField("nodes", "CustomerVisitProductInfo")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "CustomerVisitProductInfoEdge"
    nodes: "CustomerVisitProductInfo"
    page_info: "PageInfo"

    