
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.customer_email_address import CustomerEmailAddress
    from schema.objects.customer_phone_number import CustomerPhoneNumber
    from schema.objects.discount_node_connection import DiscountNodeConnection
    from schema.objects.draft_order_connection import DraftOrderConnection
    from schema.objects.gift_card_connection import GiftCardConnection
    from schema.objects.mailing_address import MailingAddress
    from schema.objects.mailing_address_connection import MailingAddressConnection
    from schema.objects.order_connection import OrderConnection
    from schema.scalars.string import String
    from schema.scalars.unsigned_int64 import UnsignedInt64



class CustomerMergePreviewDefaultFields(ObjectType):
    class Fields:
        addresses = ObjectField("addresses", "MailingAddressConnection")
        default_address = ObjectField("defaultAddress", "MailingAddress")
        discount_node_count = ScalarField("discountNodeCount", "UnsignedInt64")
        discount_nodes = ObjectField("discountNodes", "DiscountNodeConnection")
        display_name = ScalarField("displayName", "String")
        draft_order_count = ScalarField("draftOrderCount", "UnsignedInt64")
        draft_orders = ObjectField("draftOrders", "DraftOrderConnection")
        email = ObjectField("email", "CustomerEmailAddress")
        first_name = ScalarField("firstName", "String")
        gift_card_count = ScalarField("giftCardCount", "UnsignedInt64")
        gift_cards = ObjectField("giftCards", "GiftCardConnection")
        last_name = ScalarField("lastName", "String")
        metafield_count = ScalarField("metafieldCount", "UnsignedInt64")
        note = ScalarField("note", "String")
        order_count = ScalarField("orderCount", "UnsignedInt64")
        orders = ObjectField("orders", "OrderConnection")
        phone_number = ObjectField("phoneNumber", "CustomerPhoneNumber")
        tags = ScalarField("tags", "String")

    addresses: "MailingAddressConnection"
    default_address: "MailingAddress"
    discount_node_count: "UnsignedInt64"
    discount_nodes: "DiscountNodeConnection"
    display_name: "String"
    draft_order_count: "UnsignedInt64"
    draft_orders: "DraftOrderConnection"
    email: "CustomerEmailAddress"
    first_name: "String"
    gift_card_count: "UnsignedInt64"
    gift_cards: "GiftCardConnection"
    last_name: "String"
    metafield_count: "UnsignedInt64"
    note: "String"
    order_count: "UnsignedInt64"
    orders: "OrderConnection"
    phone_number: "CustomerPhoneNumber"
    tags: "String"

    