
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.customer import Customer
    from schema.objects.customer_edge import CustomerEdge
    from schema.objects.page_info import PageInfo



class CustomerConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "CustomerEdge")
        nodes = ObjectField("nodes", "Customer")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "CustomerEdge"
    nodes: "Customer"
    page_info: "PageInfo"

    