
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.customer_request_data_erasure_user_error import CustomerRequestDataErasureUserError
    from schema.scalars.id import ID



class CustomerRequestDataErasurePayload(ObjectType):
    class Fields:
        customer_id = ScalarField("customerId", "ID")
        user_errors = ObjectField("userErrors", "CustomerRequestDataErasureUserError")

    customer_id: "ID"
    user_errors: "CustomerRequestDataErasureUserError"

    