
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.customer_accounts_version import CustomerAccountsVersion
    from schema.scalars.boolean import Boolean
    from schema.scalars.url import URL



class CustomerAccountsV2(ObjectType):
    class Fields:
        customer_accounts_version = EnumField("customerAccountsVersion", "CustomerAccountsVersion")
        login_links_visible_on_storefront_and_checkout = ScalarField("loginLinksVisibleOnStorefrontAndCheckout", "Boolean")
        login_required_at_checkout = ScalarField("loginRequiredAtCheckout", "Boolean")
        url = ScalarField("url", "URL")

    customer_accounts_version: "CustomerAccountsVersion"
    login_links_visible_on_storefront_and_checkout: "Boolean"
    login_required_at_checkout: "Boolean"
    url: "URL"

    