
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.customer_payment_method_get_duplication_data_user_error import CustomerPaymentMethodGetDuplicationDataUserError
    from schema.scalars.string import String



class CustomerPaymentMethodGetDuplicationDataPayload(ObjectType):
    class Fields:
        encrypted_duplication_data = ScalarField("encryptedDuplicationData", "String")
        user_errors = ObjectField("userErrors", "CustomerPaymentMethodGetDuplicationDataUserError")

    encrypted_duplication_data: "String"
    user_errors: "CustomerPaymentMethodGetDuplicationDataUserError"

    