
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.customer import Customer
    from schema.objects.customer_send_account_invite_email_user_error import CustomerSendAccountInviteEmailUserError



class CustomerSendAccountInviteEmailPayload(ObjectType):
    class Fields:
        customer = ObjectField("customer", "Customer")
        user_errors = ObjectField("userErrors", "CustomerSendAccountInviteEmailUserError")

    customer: "Customer"
    user_errors: "CustomerSendAccountInviteEmailUserError"

    