
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, InterfaceField, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.interfaces.customer_account_page import CustomerAccountPage
    from schema.objects.customer_account_page_edge import CustomerAccountPageEdge
    from schema.objects.page_info import PageInfo



class CustomerAccountPageConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "CustomerAccountPageEdge")
        nodes = InterfaceField("nodes", "CustomerAccountPage")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "CustomerAccountPageEdge"
    nodes: "CustomerAccountPage"
    page_info: "PageInfo"

    