
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.boolean import Boolean
    from schema.scalars.id import ID
    from schema.scalars.int import Int



class CustomerSegmentMembersQuery(ObjectType):
    class Fields:
        current_count = ScalarField("currentCount", "Int")
        done = ScalarField("done", "Boolean")
        id = ScalarField("id", "ID")

    current_count: "Int"
    done: "Boolean"
    id: "ID"

    