
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.customer_merge_request_status import CustomerMergeRequestStatus
    from schema.objects.customer_merge_error import CustomerMergeError
    from schema.scalars.id import ID



class CustomerMergeRequest(ObjectType):
    class Fields:
        customer_merge_errors = ObjectField("customerMergeErrors", "CustomerMergeError")
        job_id = ScalarField("jobId", "ID")
        resulting_customer_id = ScalarField("resultingCustomerId", "ID")
        status = EnumField("status", "CustomerMergeRequestStatus")

    customer_merge_errors: "CustomerMergeError"
    job_id: "ID"
    resulting_customer_id: "ID"
    status: "CustomerMergeRequestStatus"

    