
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.id import ID
    from schema.scalars.string import String



class CustomerAccountAppExtensionPage(ObjectType):
    class Fields:
        app_extension_uuid = ScalarField("appExtensionUuid", "String")
        default_cursor = ScalarField("defaultCursor", "String")
        handle = ScalarField("handle", "String")
        id = ScalarField("id", "ID")
        title = ScalarField("title", "String")

    app_extension_uuid: "String"
    default_cursor: "String"
    handle: "String"
    id: "ID"
    title: "String"

    