
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.customer_merge_error_code import CustomerMergeErrorCode
    from schema.scalars.string import String



class CustomerMergeUserError(ObjectType):
    class Fields:
        code = EnumField("code", "CustomerMergeErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "CustomerMergeErrorCode"
    field: "String"
    message: "String"

    