
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.product import Product
    from schema.objects.product_variant import ProductVariant
    from schema.scalars.int import Int



class CustomerVisitProductInfo(ObjectType):
    class Fields:
        product = ObjectField("product", "Product")
        quantity = ScalarField("quantity", "Int")
        variant = ObjectField("variant", "ProductVariant")

    product: "Product"
    quantity: "Int"
    variant: "ProductVariant"

    