
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.customer_credit_card_billing_address import CustomerCreditCardBillingAddress
    from schema.scalars.boolean import Boolean
    from schema.scalars.int import Int
    from schema.scalars.string import String



class CustomerShopPayAgreement(ObjectType):
    class Fields:
        billing_address = ObjectField("billingAddress", "CustomerCreditCardBillingAddress")
        expires_soon = ScalarField("expiresSoon", "Boolean")
        expiry_month = ScalarField("expiryMonth", "Int")
        expiry_year = ScalarField("expiryYear", "Int")
        inactive = ScalarField("inactive", "Boolean")
        is_revocable = ScalarField("isRevocable", "Boolean")
        last_digits = ScalarField("lastDigits", "String")
        masked_number = ScalarField("maskedNumber", "String")
        name = ScalarField("name", "String")

    billing_address: "CustomerCreditCardBillingAddress"
    expires_soon: "Boolean"
    expiry_month: "Int"
    expiry_year: "Int"
    inactive: "Boolean"
    is_revocable: "Boolean"
    last_digits: "String"
    masked_number: "String"
    name: "String"

    