
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.customer_payment_method import CustomerPaymentMethod
    from schema.objects.customer_payment_method_edge import CustomerPaymentMethodEdge
    from schema.objects.page_info import PageInfo



class CustomerPaymentMethodConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "CustomerPaymentMethodEdge")
        nodes = ObjectField("nodes", "CustomerPaymentMethod")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "CustomerPaymentMethodEdge"
    nodes: "CustomerPaymentMethod"
    page_info: "PageInfo"

    