
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.customer_sms_marketing_consent_error_code import CustomerSmsMarketingConsentErrorCode
    from schema.scalars.string import String



class CustomerSmsMarketingConsentError(ObjectType):
    class Fields:
        code = EnumField("code", "CustomerSmsMarketingConsentErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "CustomerSmsMarketingConsentErrorCode"
    field: "String"
    message: "String"

    