
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.customer_payment_method import CustomerPaymentMethod
    from schema.scalars.string import String



class CustomerPaymentMethodEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "CustomerPaymentMethod")

    cursor: "String"
    node: "CustomerPaymentMethod"

    