
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.customer_merge_user_error import CustomerMergeUserError
    from schema.objects.job import Job
    from schema.scalars.id import ID



class CustomerMergePayload(ObjectType):
    class Fields:
        job = ObjectField("job", "Job")
        resulting_customer_id = ScalarField("resultingCustomerId", "ID")
        user_errors = ObjectField("userErrors", "CustomerMergeUserError")

    job: "Job"
    resulting_customer_id: "ID"
    user_errors: "CustomerMergeUserError"

    