
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.customer import Customer
    from schema.objects.customer_email_marketing_consent_update_user_error import CustomerEmailMarketingConsentUpdateUserError



class CustomerEmailMarketingConsentUpdatePayload(ObjectType):
    class Fields:
        customer = ObjectField("customer", "Customer")
        user_errors = ObjectField("userErrors", "CustomerEmailMarketingConsentUpdateUserError")

    customer: "Customer"
    user_errors: "CustomerEmailMarketingConsentUpdateUserError"

    