
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.customer_segment_member_edge import CustomerSegmentMemberEdge
    from schema.objects.page_info import PageInfo
    from schema.objects.segment_statistics import SegmentStatistics
    from schema.scalars.int import Int



class CustomerSegmentMemberConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "CustomerSegmentMemberEdge")
        page_info = ObjectField("pageInfo", "PageInfo")
        statistics = ObjectField("statistics", "SegmentStatistics")
        total_count = ScalarField("totalCount", "Int")

    edges: "CustomerSegmentMemberEdge"
    page_info: "PageInfo"
    statistics: "SegmentStatistics"
    total_count: "Int"

    