
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.customer_cancel_data_erasure_user_error import CustomerCancelDataErasureUserError
    from schema.scalars.id import ID



class CustomerCancelDataErasurePayload(ObjectType):
    class Fields:
        customer_id = ScalarField("customerId", "ID")
        user_errors = ObjectField("userErrors", "CustomerCancelDataErasureUserError")

    customer_id: "ID"
    user_errors: "CustomerCancelDataErasureUserError"

    