
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.data_sale_opt_out_user_error import DataSaleOptOutUserError
    from schema.scalars.id import ID



class DataSaleOptOutPayload(ObjectType):
    class Fields:
        customer_id = ScalarField("customerId", "ID")
        user_errors = ObjectField("userErrors", "DataSaleOptOutUserError")

    customer_id: "ID"
    user_errors: "DataSaleOptOutUserError"

    