
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.delegate_access_token_destroy_user_error import DelegateAccessTokenDestroyUserError
    from schema.objects.shop import Shop
    from schema.scalars.boolean import Boolean



class DelegateAccessTokenDestroyPayload(ObjectType):
    class Fields:
        shop = ObjectField("shop", "Shop")
        status = ScalarField("status", "Boolean")
        user_errors = ObjectField("userErrors", "DelegateAccessTokenDestroyUserError")

    shop: "Shop"
    status: "Boolean"
    user_errors: "DelegateAccessTokenDestroyUserError"

    