
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.delegate_access_token_destroy_user_error_code import DelegateAccessTokenDestroyUserErrorCode
    from schema.scalars.string import String



class DelegateAccessTokenDestroyUserError(ObjectType):
    class Fields:
        code = EnumField("code", "DelegateAccessTokenDestroyUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "DelegateAccessTokenDestroyUserErrorCode"
    field: "String"
    message: "String"

    