
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.deletion_event import DeletionEvent
    from schema.objects.deletion_event_edge import DeletionEventEdge
    from schema.objects.page_info import PageInfo



class DeletionEventConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "DeletionEventEdge")
        nodes = ObjectField("nodes", "DeletionEvent")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "DeletionEventEdge"
    nodes: "DeletionEvent"
    page_info: "PageInfo"

    