
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.string import String



class DeliveryBrandedPromise(ObjectType):
    class Fields:
        handle = ScalarField("handle", "String")
        name = ScalarField("name", "String")

    handle: "String"
    name: "String"

    