
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.count import Count
    from schema.objects.location_connection import LocationConnection
    from schema.scalars.id import ID



class DeliveryLocationGroup(ObjectType):
    class Fields:
        id = ScalarField("id", "ID")
        locations = ObjectField("locations", "LocationConnection")
        locations_count = ObjectField("locationsCount", "Count")

    id: "ID"
    locations: "LocationConnection"
    locations_count: "Count"

    