
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.delivery_customization import DeliveryCustomization
    from schema.objects.delivery_customization_error import DeliveryCustomizationError



class DeliveryCustomizationUpdatePayload(ObjectType):
    class Fields:
        delivery_customization = ObjectField("deliveryCustomization", "DeliveryCustomization")
        user_errors = ObjectField("userErrors", "DeliveryCustomizationError")

    delivery_customization: "DeliveryCustomization"
    user_errors: "DeliveryCustomizationError"

    