
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.delivery_method_definition_connection import DeliveryMethodDefinitionConnection
    from schema.objects.delivery_method_definition_counts import DeliveryMethodDefinitionCounts
    from schema.objects.delivery_zone import DeliveryZone



class DeliveryLocationGroupZone(ObjectType):
    class Fields:
        method_definition_counts = ObjectField("methodDefinitionCounts", "DeliveryMethodDefinitionCounts")
        method_definitions = ObjectField("methodDefinitions", "DeliveryMethodDefinitionConnection")
        zone = ObjectField("zone", "DeliveryZone")

    method_definition_counts: "DeliveryMethodDefinitionCounts"
    method_definitions: "DeliveryMethodDefinitionConnection"
    zone: "DeliveryZone"

    