
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.string import String



class DeliveryMethodAdditionalInformation(ObjectType):
    class Fields:
        instructions = ScalarField("instructions", "String")
        phone = ScalarField("phone", "String")

    instructions: "String"
    phone: "String"

    