
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.location import Location
    from schema.scalars.boolean import Boolean
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.string import String



class DeliveryPromiseProvider(ObjectType):
    class Fields:
        active = ScalarField("active", "Boolean")
        fulfillment_delay = ScalarField("fulfillmentDelay", "Int")
        id = ScalarField("id", "ID")
        location = ObjectField("location", "Location")
        time_zone = ScalarField("timeZone", "String")

    active: "Boolean"
    fulfillment_delay: "Int"
    id: "ID"
    location: "Location"
    time_zone: "String"

    