
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.delivery_country_and_zone import DeliveryCountryAndZone
    from schema.objects.delivery_location_group import DeliveryLocationGroup
    from schema.objects.delivery_location_group_zone_connection import DeliveryLocationGroupZoneConnection



class DeliveryProfileLocationGroup(ObjectType):
    class Fields:
        countries_in_any_zone = ObjectField("countriesInAnyZone", "DeliveryCountryAndZone")
        location_group = ObjectField("locationGroup", "DeliveryLocationGroup")
        location_group_zones = ObjectField("locationGroupZones", "DeliveryLocationGroupZoneConnection")

    countries_in_any_zone: "DeliveryCountryAndZone"
    location_group: "DeliveryLocationGroup"
    location_group_zones: "DeliveryLocationGroupZoneConnection"

    