
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.delivery_carrier_service import DeliveryCarrierService
    from schema.scalars.string import String



class DeliveryCarrierServiceEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "DeliveryCarrierService")

    cursor: "String"
    node: "DeliveryCarrierService"

    