
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.delivery_customization_error import DeliveryCustomizationError
    from schema.scalars.string import String



class DeliveryCustomizationActivationPayload(ObjectType):
    class Fields:
        ids = ScalarField("ids", "String")
        user_errors = ObjectField("userErrors", "DeliveryCustomizationError")

    ids: "String"
    user_errors: "DeliveryCustomizationError"

    