
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.id import ID
    from schema.scalars.string import String



class DeliveryProvince(ObjectType):
    class Fields:
        code = ScalarField("code", "String")
        id = ScalarField("id", "ID")
        name = ScalarField("name", "String")
        translated_name = ScalarField("translatedName", "String")

    code: "String"
    id: "ID"
    name: "String"
    translated_name: "String"

    