
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.delivery_local_pickup_time import DeliveryLocalPickupTime
    from schema.scalars.string import String



class DeliveryLocalPickupSettings(ObjectType):
    class Fields:
        instructions = ScalarField("instructions", "String")
        pickup_time = EnumField("pickupTime", "DeliveryLocalPickupTime")

    instructions: "String"
    pickup_time: "DeliveryLocalPickupTime"

    