
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.boolean import Boolean
    from schema.scalars.string import String



class DeliveryParticipantService(ObjectType):
    class Fields:
        active = ScalarField("active", "Boolean")
        name = ScalarField("name", "String")

    active: "Boolean"
    name: "String"

    