
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.product import Product
    from schema.objects.product_variant_connection import ProductVariantConnection
    from schema.scalars.id import ID



class DeliveryProfileItem(ObjectType):
    class Fields:
        id = ScalarField("id", "ID")
        product = ObjectField("product", "Product")
        variants = ObjectField("variants", "ProductVariantConnection")

    id: "ID"
    product: "Product"
    variants: "ProductVariantConnection"

    