
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.delivery_carrier_service import DeliveryCarrierService
    from schema.objects.delivery_participant_service import DeliveryParticipantService
    from schema.objects.money_v2 import MoneyV2
    from schema.scalars.boolean import Boolean
    from schema.scalars.float import Float
    from schema.scalars.id import ID



class DeliveryParticipant(ObjectType):
    class Fields:
        adapt_to_new_services_flag = ScalarField("adaptToNewServicesFlag", "Boolean")
        carrier_service = ObjectField("carrierService", "DeliveryCarrierService")
        fixed_fee = ObjectField("fixedFee", "MoneyV2")
        id = ScalarField("id", "ID")
        participant_services = ObjectField("participantServices", "DeliveryParticipantService")
        percentage_of_rate_fee = ScalarField("percentageOfRateFee", "Float")

    adapt_to_new_services_flag: "Boolean"
    carrier_service: "DeliveryCarrierService"
    fixed_fee: "MoneyV2"
    id: "ID"
    participant_services: "DeliveryParticipantService"
    percentage_of_rate_fee: "Float"

    