
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.delivery_promise_provider import DeliveryPromiseProvider
    from schema.objects.delivery_promise_provider_upsert_user_error import DeliveryPromiseProviderUpsertUserError



class DeliveryPromiseProviderUpsertPayload(ObjectType):
    class Fields:
        delivery_promise_provider = ObjectField("deliveryPromiseProvider", "DeliveryPromiseProvider")
        user_errors = ObjectField("userErrors", "DeliveryPromiseProviderUpsertUserError")

    delivery_promise_provider: "DeliveryPromiseProvider"
    user_errors: "DeliveryPromiseProviderUpsertUserError"

    