
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.discount_code_app import DiscountCodeApp
    from schema.objects.discount_user_error import DiscountUserError



class DiscountCodeAppCreatePayload(ObjectType):
    class Fields:
        code_app_discount = ObjectField("codeAppDiscount", "DiscountCodeApp")
        user_errors = ObjectField("userErrors", "DiscountUserError")

    code_app_discount: "DiscountCodeApp"
    user_errors: "DiscountUserError"

    