
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.discount_code_node import DiscountCodeNode
    from schema.objects.discount_redeem_code_bulk_creation_code_connection import DiscountRedeemCodeBulkCreationCodeConnection
    from schema.scalars.boolean import Boolean
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.int import Int



class DiscountRedeemCodeBulkCreation(ObjectType):
    class Fields:
        codes = ObjectField("codes", "DiscountRedeemCodeBulkCreationCodeConnection")
        codes_count = ScalarField("codesCount", "Int")
        created_at = ScalarField("createdAt", "DateTime")
        discount_code = ObjectField("discountCode", "DiscountCodeNode")
        done = ScalarField("done", "Boolean")
        failed_count = ScalarField("failedCount", "Int")
        id = ScalarField("id", "ID")
        imported_count = ScalarField("importedCount", "Int")

    codes: "DiscountRedeemCodeBulkCreationCodeConnection"
    codes_count: "Int"
    created_at: "DateTime"
    discount_code: "DiscountCodeNode"
    done: "Boolean"
    failed_count: "Int"
    id: "ID"
    imported_count: "Int"

    