
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.discount_code_node import DiscountCodeNode
    from schema.objects.discount_code_node_edge import DiscountCodeNodeEdge
    from schema.objects.page_info import PageInfo



class DiscountCodeNodeConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "DiscountCodeNodeEdge")
        nodes = ObjectField("nodes", "DiscountCodeNode")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "DiscountCodeNodeEdge"
    nodes: "DiscountCodeNode"
    page_info: "PageInfo"

    