
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.money_v2 import MoneyV2



class DiscountMinimumSubtotal(ObjectType):
    class Fields:
        greater_than_or_equal_to_subtotal = ObjectField("greaterThanOrEqualToSubtotal", "MoneyV2")

    greater_than_or_equal_to_subtotal: "MoneyV2"

    