
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.product_connection import ProductConnection
    from schema.objects.product_variant_connection import ProductVariantConnection



class DiscountProducts(ObjectType):
    class Fields:
        product_variants = ObjectField("productVariants", "ProductVariantConnection")
        products = ObjectField("products", "ProductConnection")

    product_variants: "ProductVariantConnection"
    products: "ProductConnection"

    