
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.event_connection import EventConnection
    from schema.objects.metafield import Metafield
    from schema.objects.metafield_connection import MetafieldConnection
    from schema.objects.metafield_definition_connection import MetafieldDefinitionConnection
    from schema.objects.private_metafield import PrivateMetafield
    from schema.objects.private_metafield_connection import PrivateMetafieldConnection
    from schema.scalars.id import ID
    from schema.unions.discount import Discount



class DiscountNode(ObjectType):
    class Fields:
        discount = UnionField("discount", "Discount")
        events = ObjectField("events", "EventConnection")
        id = ScalarField("id", "ID")
        metafield = ObjectField("metafield", "Metafield")
        metafield_definitions = ObjectField("metafieldDefinitions", "MetafieldDefinitionConnection")
        metafields = ObjectField("metafields", "MetafieldConnection")
        private_metafield = ObjectField("privateMetafield", "PrivateMetafield")
        private_metafields = ObjectField("privateMetafields", "PrivateMetafieldConnection")

    discount: "Discount"
    events: "EventConnection"
    id: "ID"
    metafield: "Metafield"
    metafield_definitions: "MetafieldDefinitionConnection"
    metafields: "MetafieldConnection"
    private_metafield: "PrivateMetafield"
    private_metafields: "PrivateMetafieldConnection"

    