
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.discount_redeem_code import DiscountRedeemCode
    from schema.objects.discount_user_error import DiscountUserError
    from schema.scalars.string import String



class DiscountRedeemCodeBulkCreationCode(ObjectType):
    class Fields:
        code = ScalarField("code", "String")
        discount_redeem_code = ObjectField("discountRedeemCode", "DiscountRedeemCode")
        errors = ObjectField("errors", "DiscountUserError")

    code: "String"
    discount_redeem_code: "DiscountRedeemCode"
    errors: "DiscountUserError"

    