
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.country_code import CountryCode
    from schema.scalars.boolean import Boolean



class DiscountCountries(ObjectType):
    class Fields:
        countries = EnumField("countries", "CountryCode")
        include_rest_of_world = ScalarField("includeRestOfWorld", "Boolean")

    countries: "CountryCode"
    include_rest_of_world: "Boolean"

    