
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, InterfaceField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.interfaces.discount_application import DiscountApplication
    from schema.scalars.string import String



class DiscountApplicationEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = InterfaceField("node", "DiscountApplication")

    cursor: "String"
    node: "DiscountApplication"

    