
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.discount_status import DiscountStatus
    from schema.enums.shipping_discount_class import ShippingDiscountClass
    from schema.objects.discount_combines_with import DiscountCombinesWith
    from schema.objects.money_v2 import MoneyV2
    from schema.scalars.boolean import Boolean
    from schema.scalars.date_time import DateTime
    from schema.scalars.int import Int
    from schema.scalars.string import String
    from schema.unions.discount_minimum_requirement import DiscountMinimumRequirement
    from schema.unions.discount_shipping_destination_selection import DiscountShippingDestinationSelection



class DiscountAutomaticFreeShipping(ObjectType):
    class Fields:
        applies_on_one_time_purchase = ScalarField("appliesOnOneTimePurchase", "Boolean")
        applies_on_subscription = ScalarField("appliesOnSubscription", "Boolean")
        async_usage_count = ScalarField("asyncUsageCount", "Int")
        combines_with = ObjectField("combinesWith", "DiscountCombinesWith")
        created_at = ScalarField("createdAt", "DateTime")
        destination_selection = UnionField("destinationSelection", "DiscountShippingDestinationSelection")
        discount_class = EnumField("discountClass", "ShippingDiscountClass")
        ends_at = ScalarField("endsAt", "DateTime")
        has_timeline_comment = ScalarField("hasTimelineComment", "Boolean")
        maximum_shipping_price = ObjectField("maximumShippingPrice", "MoneyV2")
        minimum_requirement = UnionField("minimumRequirement", "DiscountMinimumRequirement")
        recurring_cycle_limit = ScalarField("recurringCycleLimit", "Int")
        short_summary = ScalarField("shortSummary", "String")
        starts_at = ScalarField("startsAt", "DateTime")
        status = EnumField("status", "DiscountStatus")
        summary = ScalarField("summary", "String")
        title = ScalarField("title", "String")
        total_sales = ObjectField("totalSales", "MoneyV2")
        updated_at = ScalarField("updatedAt", "DateTime")

    applies_on_one_time_purchase: "Boolean"
    applies_on_subscription: "Boolean"
    async_usage_count: "Int"
    combines_with: "DiscountCombinesWith"
    created_at: "DateTime"
    destination_selection: "DiscountShippingDestinationSelection"
    discount_class: "ShippingDiscountClass"
    ends_at: "DateTime"
    has_timeline_comment: "Boolean"
    maximum_shipping_price: "MoneyV2"
    minimum_requirement: "DiscountMinimumRequirement"
    recurring_cycle_limit: "Int"
    short_summary: "String"
    starts_at: "DateTime"
    status: "DiscountStatus"
    summary: "String"
    title: "String"
    total_sales: "MoneyV2"
    updated_at: "DateTime"

    