
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.discount_redeem_code_bulk_creation_code import DiscountRedeemCodeBulkCreationCode
    from schema.scalars.string import String



class DiscountRedeemCodeBulkCreationCodeEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "DiscountRedeemCodeBulkCreationCode")

    cursor: "String"
    node: "DiscountRedeemCodeBulkCreationCode"

    