
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.discount_class import DiscountClass
    from schema.enums.discount_status import DiscountStatus
    from schema.objects.app_discount_type import AppDiscountType
    from schema.objects.discount_combines_with import DiscountCombinesWith
    from schema.objects.functions_error_history import FunctionsErrorHistory
    from schema.scalars.boolean import Boolean
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.string import String



class DiscountAutomaticApp(ObjectType):
    class Fields:
        app_discount_type = ObjectField("appDiscountType", "AppDiscountType")
        applies_on_subscription = ScalarField("appliesOnSubscription", "Boolean")
        async_usage_count = ScalarField("asyncUsageCount", "Int")
        combines_with = ObjectField("combinesWith", "DiscountCombinesWith")
        created_at = ScalarField("createdAt", "DateTime")
        discount_class = EnumField("discountClass", "DiscountClass")
        discount_id = ScalarField("discountId", "ID")
        ends_at = ScalarField("endsAt", "DateTime")
        error_history = ObjectField("errorHistory", "FunctionsErrorHistory")
        recurring_cycle_limit = ScalarField("recurringCycleLimit", "Int")
        starts_at = ScalarField("startsAt", "DateTime")
        status = EnumField("status", "DiscountStatus")
        title = ScalarField("title", "String")
        updated_at = ScalarField("updatedAt", "DateTime")

    app_discount_type: "AppDiscountType"
    applies_on_subscription: "Boolean"
    async_usage_count: "Int"
    combines_with: "DiscountCombinesWith"
    created_at: "DateTime"
    discount_class: "DiscountClass"
    discount_id: "ID"
    ends_at: "DateTime"
    error_history: "FunctionsErrorHistory"
    recurring_cycle_limit: "Int"
    starts_at: "DateTime"
    status: "DiscountStatus"
    title: "String"
    updated_at: "DateTime"

    