
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.boolean import Boolean
    from schema.unions.discount_customer_gets_value import DiscountCustomerGetsValue
    from schema.unions.discount_items import DiscountItems



class DiscountCustomerGets(ObjectType):
    class Fields:
        applies_on_one_time_purchase = ScalarField("appliesOnOneTimePurchase", "Boolean")
        applies_on_subscription = ScalarField("appliesOnSubscription", "Boolean")
        items = UnionField("items", "DiscountItems")
        value = UnionField("value", "DiscountCustomerGetsValue")

    applies_on_one_time_purchase: "Boolean"
    applies_on_subscription: "Boolean"
    items: "DiscountItems"
    value: "DiscountCustomerGetsValue"

    