
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.discount_user_error import DiscountUserError
    from schema.scalars.id import ID



class DiscountAutomaticDeletePayload(ObjectType):
    class Fields:
        deleted_automatic_discount_id = ScalarField("deletedAutomaticDiscountId", "ID")
        user_errors = ObjectField("userErrors", "DiscountUserError")

    deleted_automatic_discount_id: "ID"
    user_errors: "DiscountUserError"

    