
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.discount_code_node import DiscountCodeNode
    from schema.objects.discount_user_error import DiscountUserError



class DiscountCodeFreeShippingCreatePayload(ObjectType):
    class Fields:
        code_discount_node = ObjectField("codeDiscountNode", "DiscountCodeNode")
        user_errors = ObjectField("userErrors", "DiscountUserError")

    code_discount_node: "DiscountCodeNode"
    user_errors: "DiscountUserError"

    