
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.discount_redeem_code_bulk_creation_code import DiscountRedeemCodeBulkCreationCode
    from schema.objects.discount_redeem_code_bulk_creation_code_edge import DiscountRedeemCodeBulkCreationCodeEdge
    from schema.objects.page_info import PageInfo



class DiscountRedeemCodeBulkCreationCodeConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "DiscountRedeemCodeBulkCreationCodeEdge")
        nodes = ObjectField("nodes", "DiscountRedeemCodeBulkCreationCode")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "DiscountRedeemCodeBulkCreationCodeEdge"
    nodes: "DiscountRedeemCodeBulkCreationCode"
    page_info: "PageInfo"

    