
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.discount_status import DiscountStatus
    from schema.enums.merchandise_discount_class import MerchandiseDiscountClass
    from schema.objects.discount_combines_with import DiscountCombinesWith
    from schema.objects.discount_customer_gets import DiscountCustomerGets
    from schema.scalars.date_time import DateTime
    from schema.scalars.int import Int
    from schema.scalars.string import String
    from schema.unions.discount_minimum_requirement import DiscountMinimumRequirement



class DiscountAutomaticBasic(ObjectType):
    class Fields:
        async_usage_count = ScalarField("asyncUsageCount", "Int")
        combines_with = ObjectField("combinesWith", "DiscountCombinesWith")
        created_at = ScalarField("createdAt", "DateTime")
        customer_gets = ObjectField("customerGets", "DiscountCustomerGets")
        discount_class = EnumField("discountClass", "MerchandiseDiscountClass")
        ends_at = ScalarField("endsAt", "DateTime")
        minimum_requirement = UnionField("minimumRequirement", "DiscountMinimumRequirement")
        recurring_cycle_limit = ScalarField("recurringCycleLimit", "Int")
        short_summary = ScalarField("shortSummary", "String")
        starts_at = ScalarField("startsAt", "DateTime")
        status = EnumField("status", "DiscountStatus")
        summary = ScalarField("summary", "String")
        title = ScalarField("title", "String")
        updated_at = ScalarField("updatedAt", "DateTime")
        usage_count = ScalarField("usageCount", "Int")

    async_usage_count: "Int"
    combines_with: "DiscountCombinesWith"
    created_at: "DateTime"
    customer_gets: "DiscountCustomerGets"
    discount_class: "MerchandiseDiscountClass"
    ends_at: "DateTime"
    minimum_requirement: "DiscountMinimumRequirement"
    recurring_cycle_limit: "Int"
    short_summary: "String"
    starts_at: "DateTime"
    status: "DiscountStatus"
    summary: "String"
    title: "String"
    updated_at: "DateTime"
    usage_count: "Int"

    