
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.collection_connection import CollectionConnection



class DiscountCollections(ObjectType):
    class Fields:
        collections = ObjectField("collections", "CollectionConnection")

    collections: "CollectionConnection"

    