
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.discount_status import DiscountStatus
    from schema.enums.merchandise_discount_class import MerchandiseDiscountClass
    from schema.objects.count import Count
    from schema.objects.discount_combines_with import DiscountCombinesWith
    from schema.objects.discount_customer_gets import DiscountCustomerGets
    from schema.objects.discount_redeem_code_connection import DiscountRedeemCodeConnection
    from schema.objects.discount_shareable_url import DiscountShareableUrl
    from schema.objects.money_v2 import MoneyV2
    from schema.scalars.boolean import Boolean
    from schema.scalars.date_time import DateTime
    from schema.scalars.int import Int
    from schema.scalars.string import String
    from schema.unions.discount_customer_selection import DiscountCustomerSelection
    from schema.unions.discount_minimum_requirement import DiscountMinimumRequirement



class DiscountCodeBasic(ObjectType):
    class Fields:
        applies_once_per_customer = ScalarField("appliesOncePerCustomer", "Boolean")
        async_usage_count = ScalarField("asyncUsageCount", "Int")
        codes = ObjectField("codes", "DiscountRedeemCodeConnection")
        codes_count = ObjectField("codesCount", "Count")
        combines_with = ObjectField("combinesWith", "DiscountCombinesWith")
        created_at = ScalarField("createdAt", "DateTime")
        customer_gets = ObjectField("customerGets", "DiscountCustomerGets")
        customer_selection = UnionField("customerSelection", "DiscountCustomerSelection")
        discount_class = EnumField("discountClass", "MerchandiseDiscountClass")
        ends_at = ScalarField("endsAt", "DateTime")
        has_timeline_comment = ScalarField("hasTimelineComment", "Boolean")
        minimum_requirement = UnionField("minimumRequirement", "DiscountMinimumRequirement")
        recurring_cycle_limit = ScalarField("recurringCycleLimit", "Int")
        shareable_urls = ObjectField("shareableUrls", "DiscountShareableUrl")
        short_summary = ScalarField("shortSummary", "String")
        starts_at = ScalarField("startsAt", "DateTime")
        status = EnumField("status", "DiscountStatus")
        summary = ScalarField("summary", "String")
        title = ScalarField("title", "String")
        total_sales = ObjectField("totalSales", "MoneyV2")
        updated_at = ScalarField("updatedAt", "DateTime")
        usage_limit = ScalarField("usageLimit", "Int")

    applies_once_per_customer: "Boolean"
    async_usage_count: "Int"
    codes: "DiscountRedeemCodeConnection"
    codes_count: "Count"
    combines_with: "DiscountCombinesWith"
    created_at: "DateTime"
    customer_gets: "DiscountCustomerGets"
    customer_selection: "DiscountCustomerSelection"
    discount_class: "MerchandiseDiscountClass"
    ends_at: "DateTime"
    has_timeline_comment: "Boolean"
    minimum_requirement: "DiscountMinimumRequirement"
    recurring_cycle_limit: "Int"
    shareable_urls: "DiscountShareableUrl"
    short_summary: "String"
    starts_at: "DateTime"
    status: "DiscountStatus"
    summary: "String"
    title: "String"
    total_sales: "MoneyV2"
    updated_at: "DateTime"
    usage_limit: "Int"

    