
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.discount_application_allocation_method import DiscountApplicationAllocationMethod
    from schema.enums.discount_application_target_selection import DiscountApplicationTargetSelection
    from schema.enums.discount_application_target_type import DiscountApplicationTargetType
    from schema.scalars.int import Int
    from schema.scalars.string import String
    from schema.unions.pricing_value import PricingValue



class DiscountCodeApplication(ObjectType):
    class Fields:
        allocation_method = EnumField("allocationMethod", "DiscountApplicationAllocationMethod")
        code = ScalarField("code", "String")
        index = ScalarField("index", "Int")
        target_selection = EnumField("targetSelection", "DiscountApplicationTargetSelection")
        target_type = EnumField("targetType", "DiscountApplicationTargetType")
        value = UnionField("value", "PricingValue")

    allocation_method: "DiscountApplicationAllocationMethod"
    code: "String"
    index: "Int"
    target_selection: "DiscountApplicationTargetSelection"
    target_type: "DiscountApplicationTargetType"
    value: "PricingValue"

    