
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.discount_code_node import DiscountCodeNode
    from schema.scalars.string import String



class DiscountCodeNodeEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "DiscountCodeNode")

    cursor: "String"
    node: "DiscountCodeNode"

    