
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.discount_redeem_code import DiscountRedeemCode
    from schema.objects.discount_redeem_code_edge import DiscountRedeemCodeEdge
    from schema.objects.page_info import PageInfo



class DiscountRedeemCodeConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "DiscountRedeemCodeEdge")
        nodes = ObjectField("nodes", "DiscountRedeemCode")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "DiscountRedeemCodeEdge"
    nodes: "DiscountRedeemCode"
    page_info: "PageInfo"

    