
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.dispute_evidence_update_user_error_code import DisputeEvidenceUpdateUserErrorCode
    from schema.scalars.string import String



class DisputeEvidenceUpdateUserError(ObjectType):
    class Fields:
        code = EnumField("code", "DisputeEvidenceUpdateUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "DisputeEvidenceUpdateUserErrorCode"
    field: "String"
    message: "String"

    