
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.draft_order_line_item import DraftOrderLineItem
    from schema.objects.draft_order_line_item_edge import DraftOrderLineItemEdge
    from schema.objects.page_info import PageInfo



class DraftOrderLineItemConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "DraftOrderLineItemEdge")
        nodes = ObjectField("nodes", "DraftOrderLineItem")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "DraftOrderLineItemEdge"
    nodes: "DraftOrderLineItem"
    page_info: "PageInfo"

    