
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.draft_order import DraftOrder
    from schema.objects.user_error import UserError



class DraftOrderUpdatePayload(ObjectType):
    class Fields:
        draft_order = ObjectField("draftOrder", "DraftOrder")
        user_errors = ObjectField("userErrors", "UserError")

    draft_order: "DraftOrder"
    user_errors: "UserError"

    