
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.string import String



class DraftOrderBundleAddedWarning(ObjectType):
    class Fields:
        error_code = ScalarField("errorCode", "String")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    error_code: "String"
    field: "String"
    message: "String"

    