
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.errors_web_pixel_user_error_code import ErrorsWebPixelUserErrorCode
    from schema.scalars.string import String



class ErrorsWebPixelUserError(ObjectType):
    class Fields:
        code = EnumField("code", "ErrorsWebPixelUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "ErrorsWebPixelUserErrorCode"
    field: "String"
    message: "String"

    