
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, InterfaceField, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.interfaces.event import Event
    from schema.objects.event_edge import EventEdge
    from schema.objects.page_info import PageInfo



class EventConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "EventEdge")
        nodes = InterfaceField("nodes", "Event")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "EventEdge"
    nodes: "Event"
    page_info: "PageInfo"

    