
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.exchange_v2_line_item import ExchangeV2LineItem
    from schema.objects.money_bag import MoneyBag
    from schema.objects.tax_line import TaxLine



class ExchangeV2Additions(ObjectType):
    class Fields:
        line_items = ObjectField("lineItems", "ExchangeV2LineItem")
        subtotal_price_set = ObjectField("subtotalPriceSet", "MoneyBag")
        tax_lines = ObjectField("taxLines", "TaxLine")
        total_price_set = ObjectField("totalPriceSet", "MoneyBag")

    line_items: "ExchangeV2LineItem"
    subtotal_price_set: "MoneyBag"
    tax_lines: "TaxLine"
    total_price_set: "MoneyBag"

    