
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.exchange_v2_additions import ExchangeV2Additions
    from schema.objects.exchange_v2_returns import ExchangeV2Returns
    from schema.objects.location import Location
    from schema.objects.money_bag import MoneyBag
    from schema.objects.order_transaction import OrderTransaction
    from schema.objects.refund import Refund
    from schema.objects.staff_member import StaffMember
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.string import String



class ExchangeV2(ObjectType):
    class Fields:
        additions = ObjectField("additions", "ExchangeV2Additions")
        completed_at = ScalarField("completedAt", "DateTime")
        created_at = ScalarField("createdAt", "DateTime")
        id = ScalarField("id", "ID")
        location = ObjectField("location", "Location")
        note = ScalarField("note", "String")
        refunds = ObjectField("refunds", "Refund")
        returns = ObjectField("returns", "ExchangeV2Returns")
        staff_member = ObjectField("staffMember", "StaffMember")
        total_amount_processed_set = ObjectField("totalAmountProcessedSet", "MoneyBag")
        total_price_set = ObjectField("totalPriceSet", "MoneyBag")
        transactions = ObjectField("transactions", "OrderTransaction")

    additions: "ExchangeV2Additions"
    completed_at: "DateTime"
    created_at: "DateTime"
    id: "ID"
    location: "Location"
    note: "String"
    refunds: "Refund"
    returns: "ExchangeV2Returns"
    staff_member: "StaffMember"
    total_amount_processed_set: "MoneyBag"
    total_price_set: "MoneyBag"
    transactions: "OrderTransaction"

    