
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.file_error_code import FileErrorCode
    from schema.scalars.string import String



class FileError(ObjectType):
    class Fields:
        code = EnumField("code", "FileErrorCode")
        details = ScalarField("details", "String")
        message = ScalarField("message", "String")

    code: "FileErrorCode"
    details: "String"
    message: "String"

    