
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.financial_summary_discount_application import FinancialSummaryDiscountApplication
    from schema.objects.money_bag import MoneyBag



class FinancialSummaryDiscountAllocation(ObjectType):
    class Fields:
        approximate_allocated_amount_per_item = ObjectField("approximateAllocatedAmountPerItem", "MoneyBag")
        discount_application = ObjectField("discountApplication", "FinancialSummaryDiscountApplication")

    approximate_allocated_amount_per_item: "MoneyBag"
    discount_application: "FinancialSummaryDiscountApplication"

    