
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.fulfillment_order_hold_user_error_code import FulfillmentOrderHoldUserErrorCode
    from schema.scalars.string import String



class FulfillmentOrderHoldUserError(ObjectType):
    class Fields:
        code = EnumField("code", "FulfillmentOrderHoldUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "FulfillmentOrderHoldUserErrorCode"
    field: "String"
    message: "String"

    