
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.fulfillment_order_action import FulfillmentOrderAction
    from schema.scalars.url import URL



class FulfillmentOrderSupportedAction(ObjectType):
    class Fields:
        action = EnumField("action", "FulfillmentOrderAction")
        external_url = ScalarField("externalUrl", "URL")

    action: "FulfillmentOrderAction"
    external_url: "URL"

    