
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.fulfillment_order_request_status import FulfillmentOrderRequestStatus
    from schema.enums.fulfillment_order_status import FulfillmentOrderStatus
    from schema.objects.delivery_method import DeliveryMethod
    from schema.objects.fulfillment_connection import FulfillmentConnection
    from schema.objects.fulfillment_hold import FulfillmentHold
    from schema.objects.fulfillment_order_assigned_location import FulfillmentOrderAssignedLocation
    from schema.objects.fulfillment_order_connection import FulfillmentOrderConnection
    from schema.objects.fulfillment_order_destination import FulfillmentOrderDestination
    from schema.objects.fulfillment_order_international_duties import FulfillmentOrderInternationalDuties
    from schema.objects.fulfillment_order_line_item_connection import FulfillmentOrderLineItemConnection
    from schema.objects.fulfillment_order_location_for_move_connection import FulfillmentOrderLocationForMoveConnection
    from schema.objects.fulfillment_order_merchant_request_connection import FulfillmentOrderMerchantRequestConnection
    from schema.objects.fulfillment_order_supported_action import FulfillmentOrderSupportedAction
    from schema.objects.order import Order
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.string import String



class FulfillmentOrder(ObjectType):
    class Fields:
        assigned_location = ObjectField("assignedLocation", "FulfillmentOrderAssignedLocation")
        channel_id = ScalarField("channelId", "ID")
        created_at = ScalarField("createdAt", "DateTime")
        delivery_method = ObjectField("deliveryMethod", "DeliveryMethod")
        destination = ObjectField("destination", "FulfillmentOrderDestination")
        fulfill_at = ScalarField("fulfillAt", "DateTime")
        fulfill_by = ScalarField("fulfillBy", "DateTime")
        fulfillment_holds = ObjectField("fulfillmentHolds", "FulfillmentHold")
        fulfillment_orders_for_merge = ObjectField("fulfillmentOrdersForMerge", "FulfillmentOrderConnection")
        fulfillments = ObjectField("fulfillments", "FulfillmentConnection")
        id = ScalarField("id", "ID")
        international_duties = ObjectField("internationalDuties", "FulfillmentOrderInternationalDuties")
        line_items = ObjectField("lineItems", "FulfillmentOrderLineItemConnection")
        locations_for_move = ObjectField("locationsForMove", "FulfillmentOrderLocationForMoveConnection")
        merchant_requests = ObjectField("merchantRequests", "FulfillmentOrderMerchantRequestConnection")
        order = ObjectField("order", "Order")
        order_id = ScalarField("orderId", "ID")
        order_name = ScalarField("orderName", "String")
        order_processed_at = ScalarField("orderProcessedAt", "DateTime")
        request_status = EnumField("requestStatus", "FulfillmentOrderRequestStatus")
        status = EnumField("status", "FulfillmentOrderStatus")
        supported_actions = ObjectField("supportedActions", "FulfillmentOrderSupportedAction")
        updated_at = ScalarField("updatedAt", "DateTime")

    assigned_location: "FulfillmentOrderAssignedLocation"
    channel_id: "ID"
    created_at: "DateTime"
    delivery_method: "DeliveryMethod"
    destination: "FulfillmentOrderDestination"
    fulfill_at: "DateTime"
    fulfill_by: "DateTime"
    fulfillment_holds: "FulfillmentHold"
    fulfillment_orders_for_merge: "FulfillmentOrderConnection"
    fulfillments: "FulfillmentConnection"
    id: "ID"
    international_duties: "FulfillmentOrderInternationalDuties"
    line_items: "FulfillmentOrderLineItemConnection"
    locations_for_move: "FulfillmentOrderLocationForMoveConnection"
    merchant_requests: "FulfillmentOrderMerchantRequestConnection"
    order: "Order"
    order_id: "ID"
    order_name: "String"
    order_processed_at: "DateTime"
    request_status: "FulfillmentOrderRequestStatus"
    status: "FulfillmentOrderStatus"
    supported_actions: "FulfillmentOrderSupportedAction"
    updated_at: "DateTime"

    