
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.fulfillment_order import FulfillmentOrder
    from schema.objects.user_error import UserError



class FulfillmentOrderMovePayload(ObjectType):
    class Fields:
        moved_fulfillment_order = ObjectField("movedFulfillmentOrder", "FulfillmentOrder")
        original_fulfillment_order = ObjectField("originalFulfillmentOrder", "FulfillmentOrder")
        remaining_fulfillment_order = ObjectField("remainingFulfillmentOrder", "FulfillmentOrder")
        user_errors = ObjectField("userErrors", "UserError")

    moved_fulfillment_order: "FulfillmentOrder"
    original_fulfillment_order: "FulfillmentOrder"
    remaining_fulfillment_order: "FulfillmentOrder"
    user_errors: "UserError"

    