
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.fulfillment import Fulfillment
    from schema.objects.fulfillment_edge import FulfillmentEdge
    from schema.objects.page_info import PageInfo



class FulfillmentConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "FulfillmentEdge")
        nodes = ObjectField("nodes", "Fulfillment")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "FulfillmentEdge"
    nodes: "Fulfillment"
    page_info: "PageInfo"

    