
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.fulfillment_order_reschedule_user_error_code import FulfillmentOrderRescheduleUserErrorCode
    from schema.scalars.string import String



class FulfillmentOrderRescheduleUserError(ObjectType):
    class Fields:
        code = EnumField("code", "FulfillmentOrderRescheduleUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "FulfillmentOrderRescheduleUserErrorCode"
    field: "String"
    message: "String"

    