
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.fulfillment_order_merchant_request import FulfillmentOrderMerchantRequest
    from schema.objects.fulfillment_order_merchant_request_edge import FulfillmentOrderMerchantRequestEdge
    from schema.objects.page_info import PageInfo



class FulfillmentOrderMerchantRequestConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "FulfillmentOrderMerchantRequestEdge")
        nodes = ObjectField("nodes", "FulfillmentOrderMerchantRequest")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "FulfillmentOrderMerchantRequestEdge"
    nodes: "FulfillmentOrderMerchantRequest"
    page_info: "PageInfo"

    