
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.fulfillment import Fulfillment
    from schema.objects.user_error import UserError



class FulfillmentCancelPayload(ObjectType):
    class Fields:
        fulfillment = ObjectField("fulfillment", "Fulfillment")
        user_errors = ObjectField("userErrors", "UserError")

    fulfillment: "Fulfillment"
    user_errors: "UserError"

    