
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.line_item import LineItem
    from schema.objects.money_bag import MoneyBag
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.money import Money



class FulfillmentLineItem(ObjectType):
    class Fields:
        discounted_total = ScalarField("discountedTotal", "Money")
        discounted_total_set = ObjectField("discountedTotalSet", "MoneyBag")
        id = ScalarField("id", "ID")
        line_item = ObjectField("lineItem", "LineItem")
        original_total = ScalarField("originalTotal", "Money")
        original_total_set = ObjectField("originalTotalSet", "MoneyBag")
        quantity = ScalarField("quantity", "Int")

    discounted_total: "Money"
    discounted_total_set: "MoneyBag"
    id: "ID"
    line_item: "LineItem"
    original_total: "Money"
    original_total_set: "MoneyBag"
    quantity: "Int"

    