
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.fulfillment_line_item import FulfillmentLineItem
    from schema.objects.fulfillment_line_item_edge import FulfillmentLineItemEdge
    from schema.objects.page_info import PageInfo



class FulfillmentLineItemConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "FulfillmentLineItemEdge")
        nodes = ObjectField("nodes", "FulfillmentLineItem")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "FulfillmentLineItemEdge"
    nodes: "FulfillmentLineItem"
    page_info: "PageInfo"

    