
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.financial_summary_discount_allocation import FinancialSummaryDiscountAllocation
    from schema.objects.money_bag import MoneyBag
    from schema.scalars.int import Int



class FulfillmentOrderLineItemFinancialSummary(ObjectType):
    class Fields:
        approximate_discounted_unit_price_set = ObjectField("approximateDiscountedUnitPriceSet", "MoneyBag")
        discount_allocations = ObjectField("discountAllocations", "FinancialSummaryDiscountAllocation")
        original_unit_price_set = ObjectField("originalUnitPriceSet", "MoneyBag")
        quantity = ScalarField("quantity", "Int")

    approximate_discounted_unit_price_set: "MoneyBag"
    discount_allocations: "FinancialSummaryDiscountAllocation"
    original_unit_price_set: "MoneyBag"
    quantity: "Int"

    