
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.fulfillment_constraint_rule_delete_user_error_code import FulfillmentConstraintRuleDeleteUserErrorCode
    from schema.scalars.string import String



class FulfillmentConstraintRuleDeleteUserError(ObjectType):
    class Fields:
        code = EnumField("code", "FulfillmentConstraintRuleDeleteUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "FulfillmentConstraintRuleDeleteUserErrorCode"
    field: "String"
    message: "String"

    