
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.fulfillment_constraint_rule_create_user_error_code import FulfillmentConstraintRuleCreateUserErrorCode
    from schema.scalars.string import String



class FulfillmentConstraintRuleCreateUserError(ObjectType):
    class Fields:
        code = EnumField("code", "FulfillmentConstraintRuleCreateUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "FulfillmentConstraintRuleCreateUserErrorCode"
    field: "String"
    message: "String"

    