
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.fulfillment_order_line_items_prepared_for_pickup_user_error import FulfillmentOrderLineItemsPreparedForPickupUserError



class FulfillmentOrderLineItemsPreparedForPickupPayload(ObjectType):
    class Fields:
        user_errors = ObjectField("userErrors", "FulfillmentOrderLineItemsPreparedForPickupUserError")

    user_errors: "FulfillmentOrderLineItemsPreparedForPickupUserError"

    