
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.fulfillment_order_split_user_error_code import FulfillmentOrderSplitUserErrorCode
    from schema.scalars.string import String



class FulfillmentOrderSplitUserError(ObjectType):
    class Fields:
        code = EnumField("code", "FulfillmentOrderSplitUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "FulfillmentOrderSplitUserErrorCode"
    field: "String"
    message: "String"

    