
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.fulfillment_hold_reason import FulfillmentHoldReason
    from schema.scalars.boolean import Boolean
    from schema.scalars.id import ID
    from schema.scalars.string import String



class FulfillmentHold(ObjectType):
    class Fields:
        display_reason = ScalarField("displayReason", "String")
        held_by = ScalarField("heldBy", "String")
        held_by_requesting_app = ScalarField("heldByRequestingApp", "Boolean")
        id = ScalarField("id", "ID")
        reason = EnumField("reason", "FulfillmentHoldReason")
        reason_notes = ScalarField("reasonNotes", "String")

    display_reason: "String"
    held_by: "String"
    held_by_requesting_app: "Boolean"
    id: "ID"
    reason: "FulfillmentHoldReason"
    reason_notes: "String"

    