
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.fulfillment_order import FulfillmentOrder
    from schema.scalars.string import String



class FulfillmentOrderEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "FulfillmentOrder")

    cursor: "String"
    node: "FulfillmentOrder"

    