
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.fulfillment_order_line_item import FulfillmentOrderLineItem
    from schema.objects.fulfillment_order_line_item_edge import FulfillmentOrderLineItemEdge
    from schema.objects.page_info import PageInfo



class FulfillmentOrderLineItemConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "FulfillmentOrderLineItemEdge")
        nodes = ObjectField("nodes", "FulfillmentOrderLineItem")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "FulfillmentOrderLineItemEdge"
    nodes: "FulfillmentOrderLineItem"
    page_info: "PageInfo"

    