
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.fulfillment_order_merge_result import FulfillmentOrderMergeResult
    from schema.objects.fulfillment_order_merge_user_error import FulfillmentOrderMergeUserError



class FulfillmentOrderMergePayload(ObjectType):
    class Fields:
        fulfillment_order_merges = ObjectField("fulfillmentOrderMerges", "FulfillmentOrderMergeResult")
        user_errors = ObjectField("userErrors", "FulfillmentOrderMergeUserError")

    fulfillment_order_merges: "FulfillmentOrderMergeResult"
    user_errors: "FulfillmentOrderMergeUserError"

    