
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.fulfillment_service import FulfillmentService
    from schema.objects.user_error import UserError



class FulfillmentServiceUpdatePayload(ObjectType):
    class Fields:
        fulfillment_service = ObjectField("fulfillmentService", "FulfillmentService")
        user_errors = ObjectField("userErrors", "UserError")

    fulfillment_service: "FulfillmentService"
    user_errors: "UserError"

    