
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.fulfillment_event_status import FulfillmentEventStatus
    from schema.scalars.date_time import DateTime
    from schema.scalars.float import Float
    from schema.scalars.id import ID
    from schema.scalars.string import String



class FulfillmentEvent(ObjectType):
    class Fields:
        address1 = ScalarField("address1", "String")
        city = ScalarField("city", "String")
        country = ScalarField("country", "String")
        created_at = ScalarField("createdAt", "DateTime")
        estimated_delivery_at = ScalarField("estimatedDeliveryAt", "DateTime")
        happened_at = ScalarField("happenedAt", "DateTime")
        id = ScalarField("id", "ID")
        latitude = ScalarField("latitude", "Float")
        longitude = ScalarField("longitude", "Float")
        message = ScalarField("message", "String")
        province = ScalarField("province", "String")
        status = EnumField("status", "FulfillmentEventStatus")
        zip = ScalarField("zip", "String")

    address1: "String"
    city: "String"
    country: "String"
    created_at: "DateTime"
    estimated_delivery_at: "DateTime"
    happened_at: "DateTime"
    id: "ID"
    latitude: "Float"
    longitude: "Float"
    message: "String"
    province: "String"
    status: "FulfillmentEventStatus"
    zip: "String"

    