
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.gift_card_deactivate_user_error_code import GiftCardDeactivateUserErrorCode
    from schema.scalars.string import String



class GiftCardDeactivateUserError(ObjectType):
    class Fields:
        code = EnumField("code", "GiftCardDeactivateUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "GiftCardDeactivateUserErrorCode"
    field: "String"
    message: "String"

    