
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.gift_card_send_notification_to_customer_user_error_code import GiftCardSendNotificationToCustomerUserErrorCode
    from schema.scalars.string import String



class GiftCardSendNotificationToCustomerUserError(ObjectType):
    class Fields:
        code = EnumField("code", "GiftCardSendNotificationToCustomerUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "GiftCardSendNotificationToCustomerUserErrorCode"
    field: "String"
    message: "String"

    