
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.gift_card import GiftCard
    from schema.objects.gift_card_user_error import GiftCardUserError
    from schema.scalars.string import String



class GiftCardCreatePayload(ObjectType):
    class Fields:
        gift_card = ObjectField("giftCard", "GiftCard")
        gift_card_code = ScalarField("giftCardCode", "String")
        user_errors = ObjectField("userErrors", "GiftCardUserError")

    gift_card: "GiftCard"
    gift_card_code: "String"
    user_errors: "GiftCardUserError"

    