
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.gift_card_error_code import GiftCardErrorCode
    from schema.scalars.string import String



class GiftCardUserError(ObjectType):
    class Fields:
        code = EnumField("code", "GiftCardErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "GiftCardErrorCode"
    field: "String"
    message: "String"

    