
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.gift_card import GiftCard
    from schema.objects.user_error import UserError



class GiftCardUpdatePayload(ObjectType):
    class Fields:
        gift_card = ObjectField("giftCard", "GiftCard")
        user_errors = ObjectField("userErrors", "UserError")

    gift_card: "GiftCard"
    user_errors: "UserError"

    