
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.gift_card import GiftCard
    from schema.scalars.string import String



class GiftCardEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "GiftCard")

    cursor: "String"
    node: "GiftCard"

    