
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.metafield import Metafield
    from schema.objects.metafield_connection import MetafieldConnection
    from schema.objects.private_metafield import PrivateMetafield
    from schema.objects.private_metafield_connection import PrivateMetafieldConnection
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.string import String
    from schema.scalars.url import URL



class Image(ObjectType):
    class Fields:
        alt_text = ScalarField("altText", "String")
        height = ScalarField("height", "Int")
        id = ScalarField("id", "ID")
        metafield = ObjectField("metafield", "Metafield")
        metafields = ObjectField("metafields", "MetafieldConnection")
        original_src = ScalarField("originalSrc", "URL")
        private_metafield = ObjectField("privateMetafield", "PrivateMetafield")
        private_metafields = ObjectField("privateMetafields", "PrivateMetafieldConnection")
        src = ScalarField("src", "URL")
        transformed_src = ScalarField("transformedSrc", "URL")
        url = ScalarField("url", "URL")
        width = ScalarField("width", "Int")

    alt_text: "String"
    height: "Int"
    id: "ID"
    metafield: "Metafield"
    metafields: "MetafieldConnection"
    original_src: "URL"
    private_metafield: "PrivateMetafield"
    private_metafields: "PrivateMetafieldConnection"
    src: "URL"
    transformed_src: "URL"
    url: "URL"
    width: "Int"

    