
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.inventory_scheduled_change import InventoryScheduledChange
    from schema.objects.inventory_set_scheduled_changes_user_error import InventorySetScheduledChangesUserError



class InventorySetScheduledChangesPayload(ObjectType):
    class Fields:
        scheduled_changes = ObjectField("scheduledChanges", "InventoryScheduledChange")
        user_errors = ObjectField("userErrors", "InventorySetScheduledChangesUserError")

    scheduled_changes: "InventoryScheduledChange"
    user_errors: "InventorySetScheduledChangesUserError"

    