
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.inventory_level import InventoryLevel
    from schema.scalars.string import String



class InventoryLevelEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "InventoryLevel")

    cursor: "String"
    node: "InventoryLevel"

    