
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.inventory_scheduled_change import InventoryScheduledChange
    from schema.scalars.string import String



class InventoryScheduledChangeEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "InventoryScheduledChange")

    cursor: "String"
    node: "InventoryScheduledChange"

    