
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.inventory_level import InventoryLevel
    from schema.objects.inventory_level_edge import InventoryLevelEdge
    from schema.objects.page_info import PageInfo



class InventoryLevelConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "InventoryLevelEdge")
        nodes = ObjectField("nodes", "InventoryLevel")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "InventoryLevelEdge"
    nodes: "InventoryLevel"
    page_info: "PageInfo"

    