
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.boolean import Boolean
    from schema.scalars.string import String



class InventoryQuantityName(ObjectType):
    class Fields:
        belongs_to = ScalarField("belongsTo", "String")
        comprises = ScalarField("comprises", "String")
        display_name = ScalarField("displayName", "String")
        is_in_use = ScalarField("isInUse", "Boolean")
        name = ScalarField("name", "String")

    belongs_to: "String"
    comprises: "String"
    display_name: "String"
    is_in_use: "Boolean"
    name: "String"

    