
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.inventory_bulk_toggle_activation_user_error_code import InventoryBulkToggleActivationUserErrorCode
    from schema.scalars.string import String



class InventoryBulkToggleActivationUserError(ObjectType):
    class Fields:
        code = EnumField("code", "InventoryBulkToggleActivationUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "InventoryBulkToggleActivationUserErrorCode"
    field: "String"
    message: "String"

    