
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.inventory_item import InventoryItem
    from schema.objects.location import Location
    from schema.scalars.int import Int
    from schema.scalars.string import String



class InventoryChange(ObjectType):
    class Fields:
        delta = ScalarField("delta", "Int")
        item = ObjectField("item", "InventoryItem")
        ledger_document_uri = ScalarField("ledgerDocumentUri", "String")
        location = ObjectField("location", "Location")
        name = ScalarField("name", "String")
        quantity_after_change = ScalarField("quantityAfterChange", "Int")

    delta: "Int"
    item: "InventoryItem"
    ledger_document_uri: "String"
    location: "Location"
    name: "String"
    quantity_after_change: "Int"

    