
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.inventory_set_on_hand_quantities_user_error_code import InventorySetOnHandQuantitiesUserErrorCode
    from schema.scalars.string import String



class InventorySetOnHandQuantitiesUserError(ObjectType):
    class Fields:
        code = EnumField("code", "InventorySetOnHandQuantitiesUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "InventorySetOnHandQuantitiesUserErrorCode"
    field: "String"
    message: "String"

    