
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.query_root import QueryRoot
    from schema.scalars.boolean import Boolean
    from schema.scalars.id import ID



class Job(ObjectType):
    class Fields:
        done = ScalarField("done", "Boolean")
        id = ScalarField("id", "ID")
        query = ObjectField("query", "QueryRoot")

    done: "Boolean"
    id: "ID"
    query: "QueryRoot"

    