
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.line_item import LineItem
    from schema.objects.line_item_edge import LineItemEdge
    from schema.objects.page_info import PageInfo



class LineItemConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "LineItemEdge")
        nodes = ObjectField("nodes", "LineItem")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "LineItemEdge"
    nodes: "LineItem"
    page_info: "PageInfo"

    