
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.id import ID
    from schema.scalars.string import String



class LineItemSellingPlan(ObjectType):
    class Fields:
        name = ScalarField("name", "String")
        selling_plan_id = ScalarField("sellingPlanId", "ID")

    name: "String"
    selling_plan_id: "ID"

    