
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.string import String



class LinkedMetafield(ObjectType):
    class Fields:
        key = ScalarField("key", "String")
        namespace = ScalarField("namespace", "String")

    key: "String"
    namespace: "String"

    