
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.localization_extension import LocalizationExtension
    from schema.scalars.string import String



class LocalizationExtensionEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "LocalizationExtension")

    cursor: "String"
    node: "LocalizationExtension"

    