
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.localization_extension import LocalizationExtension
    from schema.objects.localization_extension_edge import LocalizationExtensionEdge
    from schema.objects.page_info import PageInfo



class LocalizationExtensionConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "LocalizationExtensionEdge")
        nodes = ObjectField("nodes", "LocalizationExtension")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "LocalizationExtensionEdge"
    nodes: "LocalizationExtension"
    page_info: "PageInfo"

    