
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.location import Location
    from schema.objects.location_edit_user_error import LocationEditUserError



class LocationEditPayload(ObjectType):
    class Fields:
        location = ObjectField("location", "Location")
        user_errors = ObjectField("userErrors", "LocationEditUserError")

    location: "Location"
    user_errors: "LocationEditUserError"

    