
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.location import Location
    from schema.objects.location_edge import LocationEdge
    from schema.objects.page_info import PageInfo



class LocationConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "LocationEdge")
        nodes = ObjectField("nodes", "Location")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "LocationEdge"
    nodes: "Location"
    page_info: "PageInfo"

    