
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.string import String



class LocalPaymentMethodsPaymentDetails(ObjectType):
    class Fields:
        payment_descriptor = ScalarField("paymentDescriptor", "String")
        payment_method_name = ScalarField("paymentMethodName", "String")

    payment_descriptor: "String"
    payment_method_name: "String"

    