
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.country_code import CountryCode
    from schema.enums.localization_extension_key import LocalizationExtensionKey
    from schema.enums.localization_extension_purpose import LocalizationExtensionPurpose
    from schema.scalars.string import String



class LocalizationExtension(ObjectType):
    class Fields:
        country_code = EnumField("countryCode", "CountryCode")
        key = EnumField("key", "LocalizationExtensionKey")
        purpose = EnumField("purpose", "LocalizationExtensionPurpose")
        title = ScalarField("title", "String")
        value = ScalarField("value", "String")

    country_code: "CountryCode"
    key: "LocalizationExtensionKey"
    purpose: "LocalizationExtensionPurpose"
    title: "String"
    value: "String"

    