
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.delivery_local_pickup_settings import DeliveryLocalPickupSettings
    from schema.objects.delivery_location_local_pickup_settings_error import DeliveryLocationLocalPickupSettingsError



class LocationLocalPickupEnablePayload(ObjectType):
    class Fields:
        local_pickup_settings = ObjectField("localPickupSettings", "DeliveryLocalPickupSettings")
        user_errors = ObjectField("userErrors", "DeliveryLocationLocalPickupSettingsError")

    local_pickup_settings: "DeliveryLocalPickupSettings"
    user_errors: "DeliveryLocationLocalPickupSettingsError"

    