
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.location import Location
    from schema.objects.location_deactivate_user_error import LocationDeactivateUserError



class LocationDeactivatePayload(ObjectType):
    class Fields:
        location = ObjectField("location", "Location")
        location_deactivate_user_errors = ObjectField("locationDeactivateUserErrors", "LocationDeactivateUserError")

    location: "Location"
    location_deactivate_user_errors: "LocationDeactivateUserError"

    