
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.country_code import CountryCode
    from schema.scalars.string import String



class LocationSuggestedAddress(ObjectType):
    class Fields:
        address1 = ScalarField("address1", "String")
        address2 = ScalarField("address2", "String")
        city = ScalarField("city", "String")
        country = ScalarField("country", "String")
        country_code = EnumField("countryCode", "CountryCode")
        formatted = ScalarField("formatted", "String")
        province = ScalarField("province", "String")
        province_code = ScalarField("provinceCode", "String")
        zip = ScalarField("zip", "String")

    address1: "String"
    address2: "String"
    city: "String"
    country: "String"
    country_code: "CountryCode"
    formatted: "String"
    province: "String"
    province_code: "String"
    zip: "String"

    