
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.location import Location
    from schema.objects.location_activate_user_error import LocationActivateUserError



class LocationActivatePayload(ObjectType):
    class Fields:
        location = ObjectField("location", "Location")
        location_activate_user_errors = ObjectField("locationActivateUserErrors", "LocationActivateUserError")

    location: "Location"
    location_activate_user_errors: "LocationActivateUserError"

    