
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.location_delete_user_error_code import LocationDeleteUserErrorCode
    from schema.scalars.string import String



class LocationDeleteUserError(ObjectType):
    class Fields:
        code = EnumField("code", "LocationDeleteUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "LocationDeleteUserErrorCode"
    field: "String"
    message: "String"

    