
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.country_code import CountryCode
    from schema.enums.mailing_address_validation_result import MailingAddressValidationResult
    from schema.scalars.boolean import Boolean
    from schema.scalars.float import Float
    from schema.scalars.id import ID
    from schema.scalars.string import String



class MailingAddress(ObjectType):
    class Fields:
        address1 = ScalarField("address1", "String")
        address2 = ScalarField("address2", "String")
        city = ScalarField("city", "String")
        company = ScalarField("company", "String")
        coordinates_validated = ScalarField("coordinatesValidated", "Boolean")
        country = ScalarField("country", "String")
        country_code = ScalarField("countryCode", "String")
        country_code_v2 = EnumField("countryCodeV2", "CountryCode")
        first_name = ScalarField("firstName", "String")
        formatted = ScalarField("formatted", "String")
        formatted_area = ScalarField("formattedArea", "String")
        id = ScalarField("id", "ID")
        last_name = ScalarField("lastName", "String")
        latitude = ScalarField("latitude", "Float")
        longitude = ScalarField("longitude", "Float")
        name = ScalarField("name", "String")
        phone = ScalarField("phone", "String")
        province = ScalarField("province", "String")
        province_code = ScalarField("provinceCode", "String")
        time_zone = ScalarField("timeZone", "String")
        validation_result_summary = EnumField("validationResultSummary", "MailingAddressValidationResult")
        zip = ScalarField("zip", "String")

    address1: "String"
    address2: "String"
    city: "String"
    company: "String"
    coordinates_validated: "Boolean"
    country: "String"
    country_code: "String"
    country_code_v2: "CountryCode"
    first_name: "String"
    formatted: "String"
    formatted_area: "String"
    id: "ID"
    last_name: "String"
    latitude: "Float"
    longitude: "Float"
    name: "String"
    phone: "String"
    province: "String"
    province_code: "String"
    time_zone: "String"
    validation_result_summary: "MailingAddressValidationResult"
    zip: "String"

    