
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.badge_type import BadgeType
    from schema.enums.marketing_activity_hierarchy_level import MarketingActivityHierarchyLevel
    from schema.enums.marketing_activity_status import MarketingActivityStatus
    from schema.enums.marketing_activity_status_badge_type import MarketingActivityStatusBadgeType
    from schema.enums.marketing_channel import MarketingChannel
    from schema.enums.marketing_tactic import MarketingTactic
    from schema.objects.app import App
    from schema.objects.marketing_activity_extension_app_errors import MarketingActivityExtensionAppErrors
    from schema.objects.marketing_budget import MarketingBudget
    from schema.objects.marketing_event import MarketingEvent
    from schema.objects.money_v2 import MoneyV2
    from schema.objects.u_t_m_parameters import UTMParameters
    from schema.scalars.boolean import Boolean
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.string import String
    from schema.scalars.url import URL



class MarketingActivity(ObjectType):
    class Fields:
        activity_list_url = ScalarField("activityListUrl", "URL")
        ad_spend = ObjectField("adSpend", "MoneyV2")
        app = ObjectField("app", "App")
        app_errors = ObjectField("appErrors", "MarketingActivityExtensionAppErrors")
        budget = ObjectField("budget", "MarketingBudget")
        created_at = ScalarField("createdAt", "DateTime")
        form_data = ScalarField("formData", "String")
        hierarchy_level = EnumField("hierarchyLevel", "MarketingActivityHierarchyLevel")
        id = ScalarField("id", "ID")
        in_main_workflow_version = ScalarField("inMainWorkflowVersion", "Boolean")
        is_external = ScalarField("isExternal", "Boolean")
        marketing_channel = EnumField("marketingChannel", "MarketingChannel")
        marketing_channel_type = EnumField("marketingChannelType", "MarketingChannel")
        marketing_event = ObjectField("marketingEvent", "MarketingEvent")
        parent_activity_id = ScalarField("parentActivityId", "ID")
        parent_remote_id = ScalarField("parentRemoteId", "String")
        source_and_medium = ScalarField("sourceAndMedium", "String")
        status = EnumField("status", "MarketingActivityStatus")
        status_badge_type = EnumField("statusBadgeType", "MarketingActivityStatusBadgeType")
        status_badge_type_v2 = EnumField("statusBadgeTypeV2", "BadgeType")
        status_label = ScalarField("statusLabel", "String")
        status_transitioned_at = ScalarField("statusTransitionedAt", "DateTime")
        tactic = EnumField("tactic", "MarketingTactic")
        target_status = EnumField("targetStatus", "MarketingActivityStatus")
        title = ScalarField("title", "String")
        updated_at = ScalarField("updatedAt", "DateTime")
        url_parameter_value = ScalarField("urlParameterValue", "String")
        utm_parameters = ObjectField("utmParameters", "UTMParameters")

    activity_list_url: "URL"
    ad_spend: "MoneyV2"
    app: "App"
    app_errors: "MarketingActivityExtensionAppErrors"
    budget: "MarketingBudget"
    created_at: "DateTime"
    form_data: "String"
    hierarchy_level: "MarketingActivityHierarchyLevel"
    id: "ID"
    in_main_workflow_version: "Boolean"
    is_external: "Boolean"
    marketing_channel: "MarketingChannel"
    marketing_channel_type: "MarketingChannel"
    marketing_event: "MarketingEvent"
    parent_activity_id: "ID"
    parent_remote_id: "String"
    source_and_medium: "String"
    status: "MarketingActivityStatus"
    status_badge_type: "MarketingActivityStatusBadgeType"
    status_badge_type_v2: "BadgeType"
    status_label: "String"
    status_transitioned_at: "DateTime"
    tactic: "MarketingTactic"
    target_status: "MarketingActivityStatus"
    title: "String"
    updated_at: "DateTime"
    url_parameter_value: "String"
    utm_parameters: "UTMParameters"

    