
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.market_localizable_resource import MarketLocalizableResource
    from schema.scalars.string import String



class MarketLocalizableResourceEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "MarketLocalizableResource")

    cursor: "String"
    node: "MarketLocalizableResource"

    