
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, InterfaceField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.interfaces.market_region import MarketRegion
    from schema.scalars.string import String



class MarketRegionEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = InterfaceField("node", "MarketRegion")

    cursor: "String"
    node: "MarketRegion"

    