
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.market_user_error import MarketUserError
    from schema.scalars.id import ID



class MarketDeletePayload(ObjectType):
    class Fields:
        deleted_id = ScalarField("deletedId", "ID")
        user_errors = ObjectField("userErrors", "MarketUserError")

    deleted_id: "ID"
    user_errors: "MarketUserError"

    