
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.market_catalog import MarketCatalog
    from schema.objects.market_catalog_edge import MarketCatalogEdge
    from schema.objects.page_info import PageInfo



class MarketCatalogConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "MarketCatalogEdge")
        nodes = ObjectField("nodes", "MarketCatalog")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "MarketCatalogEdge"
    nodes: "MarketCatalog"
    page_info: "PageInfo"

    