
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.marketing_event import MarketingEvent
    from schema.objects.marketing_event_edge import MarketingEventEdge
    from schema.objects.page_info import PageInfo



class MarketingEventConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "MarketingEventEdge")
        nodes = ObjectField("nodes", "MarketingEvent")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "MarketingEventEdge"
    nodes: "MarketingEvent"
    page_info: "PageInfo"

    