
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.string import String
    from schema.scalars.url import URL



class MarketWebPresenceRootUrl(ObjectType):
    class Fields:
        locale = ScalarField("locale", "String")
        url = ScalarField("url", "URL")

    locale: "String"
    url: "URL"

    