
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.marketing_activity_extension_app_error_code import MarketingActivityExtensionAppErrorCode
    from schema.objects.user_error import UserError



class MarketingActivityExtensionAppErrors(ObjectType):
    class Fields:
        code = EnumField("code", "MarketingActivityExtensionAppErrorCode")
        user_errors = ObjectField("userErrors", "UserError")

    code: "MarketingActivityExtensionAppErrorCode"
    user_errors: "UserError"

    