
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.marketing_activity import MarketingActivity
    from schema.objects.user_error import UserError
    from schema.scalars.string import String



class MarketingActivityCreatePayload(ObjectType):
    class Fields:
        marketing_activity = ObjectField("marketingActivity", "MarketingActivity")
        redirect_path = ScalarField("redirectPath", "String")
        user_errors = ObjectField("userErrors", "UserError")

    marketing_activity: "MarketingActivity"
    redirect_path: "String"
    user_errors: "UserError"

    