
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.marketing_activity_user_error import MarketingActivityUserError
    from schema.objects.marketing_engagement import MarketingEngagement



class MarketingEngagementCreatePayload(ObjectType):
    class Fields:
        marketing_engagement = ObjectField("marketingEngagement", "MarketingEngagement")
        user_errors = ObjectField("userErrors", "MarketingActivityUserError")

    marketing_engagement: "MarketingEngagement"
    user_errors: "MarketingActivityUserError"

    