
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.job import Job
    from schema.objects.marketing_activity_user_error import MarketingActivityUserError



class MarketingActivitiesDeleteAllExternalPayload(ObjectType):
    class Fields:
        job = ObjectField("job", "Job")
        user_errors = ObjectField("userErrors", "MarketingActivityUserError")

    job: "Job"
    user_errors: "MarketingActivityUserError"

    