
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.market import Market
    from schema.scalars.boolean import Boolean
    from schema.scalars.date_time import DateTime
    from schema.scalars.string import String



class MarketLocalization(ObjectType):
    class Fields:
        key = ScalarField("key", "String")
        market = ObjectField("market", "Market")
        outdated = ScalarField("outdated", "Boolean")
        updated_at = ScalarField("updatedAt", "DateTime")
        value = ScalarField("value", "String")

    key: "String"
    market: "Market"
    outdated: "Boolean"
    updated_at: "DateTime"
    value: "String"

    