
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.media_warning_code import MediaWarningCode
    from schema.scalars.string import String



class MediaWarning(ObjectType):
    class Fields:
        code = EnumField("code", "MediaWarningCode")
        message = ScalarField("message", "String")

    code: "MediaWarningCode"
    message: "String"

    