
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.media_preview_image_status import MediaPreviewImageStatus
    from schema.objects.image import Image



class MediaPreviewImage(ObjectType):
    class Fields:
        image = ObjectField("image", "Image")
        status = EnumField("status", "MediaPreviewImageStatus")

    image: "Image"
    status: "MediaPreviewImageStatus"

    