
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.int import Int
    from schema.scalars.url import URL



class MediaImageOriginalSource(ObjectType):
    class Fields:
        file_size = ScalarField("fileSize", "Int")
        url = ScalarField("url", "URL")

    file_size: "Int"
    url: "URL"

    