
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.menu import Menu
    from schema.objects.menu_create_user_error import MenuCreateUserError



class MenuCreatePayload(ObjectType):
    class Fields:
        menu = ObjectField("menu", "Menu")
        user_errors = ObjectField("userErrors", "MenuCreateUserError")

    menu: "Menu"
    user_errors: "MenuCreateUserError"

    