
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.menu_item_type import MenuItemType
    from schema.objects.menu_item import MenuItem
    from schema.scalars.id import ID
    from schema.scalars.string import String



class MenuItem(ObjectType):
    class Fields:
        id = ScalarField("id", "ID")
        items = ObjectField("items", "MenuItem")
        resource_id = ScalarField("resourceId", "ID")
        tags = ScalarField("tags", "String")
        title = ScalarField("title", "String")
        type = EnumField("type", "MenuItemType")
        url = ScalarField("url", "String")

    id: "ID"
    items: "MenuItem"
    resource_id: "ID"
    tags: "String"
    title: "String"
    type: "MenuItemType"
    url: "String"

    