
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.menu_delete_user_error_code import MenuDeleteUserErrorCode
    from schema.scalars.string import String



class MenuDeleteUserError(ObjectType):
    class Fields:
        code = EnumField("code", "MenuDeleteUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "MenuDeleteUserErrorCode"
    field: "String"
    message: "String"

    