
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.boolean import Boolean
    from schema.scalars.string import String



class MerchantApprovalSignals(ObjectType):
    class Fields:
        identity_verified = ScalarField("identityVerified", "Boolean")
        verified_by_shopify = ScalarField("verifiedByShopify", "Boolean")
        verified_by_shopify_tier = ScalarField("verifiedByShopifyTier", "String")

    identity_verified: "Boolean"
    verified_by_shopify: "Boolean"
    verified_by_shopify_tier: "String"

    