
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.metafield_definition_constraint_value import MetafieldDefinitionConstraintValue
    from schema.scalars.string import String



class MetafieldDefinitionConstraintValueEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "MetafieldDefinitionConstraintValue")

    cursor: "String"
    node: "MetafieldDefinitionConstraintValue"

    