
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.metafield_definition_update_user_error_code import MetafieldDefinitionUpdateUserErrorCode
    from schema.scalars.int import Int
    from schema.scalars.string import String



class MetafieldDefinitionUpdateUserError(ObjectType):
    class Fields:
        code = EnumField("code", "MetafieldDefinitionUpdateUserErrorCode")
        element_index = ScalarField("elementIndex", "Int")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "MetafieldDefinitionUpdateUserErrorCode"
    element_index: "Int"
    field: "String"
    message: "String"

    