
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.metafield_definition import MetafieldDefinition
    from schema.objects.metafield_definition_pin_user_error import MetafieldDefinitionPinUserError



class MetafieldDefinitionPinPayload(ObjectType):
    class Fields:
        pinned_definition = ObjectField("pinnedDefinition", "MetafieldDefinition")
        user_errors = ObjectField("userErrors", "MetafieldDefinitionPinUserError")

    pinned_definition: "MetafieldDefinition"
    user_errors: "MetafieldDefinitionPinUserError"

    