
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.metaobject import Metaobject
    from schema.scalars.string import String



class MetaobjectEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "Metaobject")

    cursor: "String"
    node: "Metaobject"

    