
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.metafield_definition_admin_filter_status import MetafieldDefinitionAdminFilterStatus
    from schema.scalars.boolean import Boolean



class MetafieldCapabilityAdminFilterable(ObjectType):
    class Fields:
        eligible = ScalarField("eligible", "Boolean")
        enabled = ScalarField("enabled", "Boolean")
        status = EnumField("status", "MetafieldDefinitionAdminFilterStatus")

    eligible: "Boolean"
    enabled: "Boolean"
    status: "MetafieldDefinitionAdminFilterStatus"

    