
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.metafield_reference_connection import MetafieldReferenceConnection
    from schema.objects.metaobject_field_definition import MetaobjectFieldDefinition
    from schema.objects.metaobject_thumbnail import MetaobjectThumbnail
    from schema.scalars.json import JSON
    from schema.scalars.string import String
    from schema.unions.metafield_reference import MetafieldReference



class MetaobjectField(ObjectType):
    class Fields:
        definition = ObjectField("definition", "MetaobjectFieldDefinition")
        json_value = ScalarField("jsonValue", "JSON")
        key = ScalarField("key", "String")
        reference = UnionField("reference", "MetafieldReference")
        references = ObjectField("references", "MetafieldReferenceConnection")
        thumbnail = ObjectField("thumbnail", "MetaobjectThumbnail")
        type = ScalarField("type", "String")
        value = ScalarField("value", "String")

    definition: "MetaobjectFieldDefinition"
    json_value: "JSON"
    key: "String"
    reference: "MetafieldReference"
    references: "MetafieldReferenceConnection"
    thumbnail: "MetaobjectThumbnail"
    type: "String"
    value: "String"

    