
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.app import App
    from schema.objects.metaobject_access import MetaobjectAccess
    from schema.objects.metaobject_capabilities import MetaobjectCapabilities
    from schema.objects.metaobject_connection import MetaobjectConnection
    from schema.objects.metaobject_field_definition import MetaobjectFieldDefinition
    from schema.objects.staff_member import StaffMember
    from schema.scalars.boolean import Boolean
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.string import String



class MetaobjectDefinition(ObjectType):
    class Fields:
        access = ObjectField("access", "MetaobjectAccess")
        capabilities = ObjectField("capabilities", "MetaobjectCapabilities")
        created_by_app = ObjectField("createdByApp", "App")
        created_by_staff = ObjectField("createdByStaff", "StaffMember")
        description = ScalarField("description", "String")
        display_name_key = ScalarField("displayNameKey", "String")
        field_definitions = ObjectField("fieldDefinitions", "MetaobjectFieldDefinition")
        has_thumbnail_field = ScalarField("hasThumbnailField", "Boolean")
        id = ScalarField("id", "ID")
        metaobjects = ObjectField("metaobjects", "MetaobjectConnection")
        metaobjects_count = ScalarField("metaobjectsCount", "Int")
        name = ScalarField("name", "String")
        type = ScalarField("type", "String")

    access: "MetaobjectAccess"
    capabilities: "MetaobjectCapabilities"
    created_by_app: "App"
    created_by_staff: "StaffMember"
    description: "String"
    display_name_key: "String"
    field_definitions: "MetaobjectFieldDefinition"
    has_thumbnail_field: "Boolean"
    id: "ID"
    metaobjects: "MetaobjectConnection"
    metaobjects_count: "Int"
    name: "String"
    type: "String"

    