
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.metafield_definition_constraint_value import MetafieldDefinitionConstraintValue
    from schema.objects.metafield_definition_constraint_value_edge import MetafieldDefinitionConstraintValueEdge
    from schema.objects.page_info import PageInfo



class MetafieldDefinitionConstraintValueConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "MetafieldDefinitionConstraintValueEdge")
        nodes = ObjectField("nodes", "MetafieldDefinitionConstraintValue")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "MetafieldDefinitionConstraintValueEdge"
    nodes: "MetafieldDefinitionConstraintValue"
    page_info: "PageInfo"

    