
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.metaobject_capabilities_online_store import MetaobjectCapabilitiesOnlineStore
    from schema.objects.metaobject_capabilities_publishable import MetaobjectCapabilitiesPublishable
    from schema.objects.metaobject_capabilities_renderable import MetaobjectCapabilitiesRenderable
    from schema.objects.metaobject_capabilities_translatable import MetaobjectCapabilitiesTranslatable



class MetaobjectCapabilities(ObjectType):
    class Fields:
        online_store = ObjectField("onlineStore", "MetaobjectCapabilitiesOnlineStore")
        publishable = ObjectField("publishable", "MetaobjectCapabilitiesPublishable")
        renderable = ObjectField("renderable", "MetaobjectCapabilitiesRenderable")
        translatable = ObjectField("translatable", "MetaobjectCapabilitiesTranslatable")

    online_store: "MetaobjectCapabilitiesOnlineStore"
    publishable: "MetaobjectCapabilitiesPublishable"
    renderable: "MetaobjectCapabilitiesRenderable"
    translatable: "MetaobjectCapabilitiesTranslatable"

    