
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.metaobject_user_error_code import MetaobjectUserErrorCode
    from schema.scalars.int import Int
    from schema.scalars.string import String



class MetaobjectUserError(ObjectType):
    class Fields:
        code = EnumField("code", "MetaobjectUserErrorCode")
        element_index = ScalarField("elementIndex", "Int")
        element_key = ScalarField("elementKey", "String")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "MetaobjectUserErrorCode"
    element_index: "Int"
    element_key: "String"
    field: "String"
    message: "String"

    