
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.metafield import Metafield
    from schema.objects.metafields_set_user_error import MetafieldsSetUserError



class MetafieldsSetPayload(ObjectType):
    class Fields:
        metafields = ObjectField("metafields", "Metafield")
        user_errors = ObjectField("userErrors", "MetafieldsSetUserError")

    metafields: "Metafield"
    user_errors: "MetafieldsSetUserError"

    