
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.metafield_identifier import MetafieldIdentifier
    from schema.objects.user_error import UserError



class MetafieldsDeletePayload(ObjectType):
    class Fields:
        deleted_metafields = ObjectField("deletedMetafields", "MetafieldIdentifier")
        user_errors = ObjectField("userErrors", "UserError")

    deleted_metafields: "MetafieldIdentifier"
    user_errors: "UserError"

    