
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.metafield_storefront_visibility import MetafieldStorefrontVisibility
    from schema.objects.user_error import UserError



class MetafieldStorefrontVisibilityCreatePayload(ObjectType):
    class Fields:
        metafield_storefront_visibility = ObjectField("metafieldStorefrontVisibility", "MetafieldStorefrontVisibility")
        user_errors = ObjectField("userErrors", "UserError")

    metafield_storefront_visibility: "MetafieldStorefrontVisibility"
    user_errors: "UserError"

    