
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.string import String



class MetaobjectCapabilityDataOnlineStore(ObjectType):
    class Fields:
        template_suffix = ScalarField("templateSuffix", "String")

    template_suffix: "String"

    