
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.metafield_definition_delete_user_error_code import MetafieldDefinitionDeleteUserErrorCode
    from schema.scalars.string import String



class MetafieldDefinitionDeleteUserError(ObjectType):
    class Fields:
        code = EnumField("code", "MetafieldDefinitionDeleteUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "MetafieldDefinitionDeleteUserErrorCode"
    field: "String"
    message: "String"

    