
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.metaobject_user_error import MetaobjectUserError
    from schema.scalars.id import ID



class MetaobjectDeletePayload(ObjectType):
    class Fields:
        deleted_id = ScalarField("deletedId", "ID")
        user_errors = ObjectField("userErrors", "MetaobjectUserError")

    deleted_id: "ID"
    user_errors: "MetaobjectUserError"

    