
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, InterfaceField, ObjectField, ScalarField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.metafield_owner_type import MetafieldOwnerType
    from schema.interfaces.has_metafields import HasMetafields
    from schema.objects.metafield_definition import MetafieldDefinition
    from schema.objects.metafield_reference_connection import MetafieldReferenceConnection
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.json import JSON
    from schema.scalars.string import String
    from schema.scalars.unsigned_int64 import UnsignedInt64
    from schema.unions.metafield_reference import MetafieldReference



class Metafield(ObjectType):
    class Fields:
        compare_digest = ScalarField("compareDigest", "String")
        created_at = ScalarField("createdAt", "DateTime")
        definition = ObjectField("definition", "MetafieldDefinition")
        description = ScalarField("description", "String")
        id = ScalarField("id", "ID")
        json_value = ScalarField("jsonValue", "JSON")
        key = ScalarField("key", "String")
        legacy_resource_id = ScalarField("legacyResourceId", "UnsignedInt64")
        namespace = ScalarField("namespace", "String")
        owner = InterfaceField("owner", "HasMetafields")
        owner_type = EnumField("ownerType", "MetafieldOwnerType")
        reference = UnionField("reference", "MetafieldReference")
        references = ObjectField("references", "MetafieldReferenceConnection")
        type = ScalarField("type", "String")
        updated_at = ScalarField("updatedAt", "DateTime")
        value = ScalarField("value", "String")

    compare_digest: "String"
    created_at: "DateTime"
    definition: "MetafieldDefinition"
    description: "String"
    id: "ID"
    json_value: "JSON"
    key: "String"
    legacy_resource_id: "UnsignedInt64"
    namespace: "String"
    owner: "HasMetafields"
    owner_type: "MetafieldOwnerType"
    reference: "MetafieldReference"
    references: "MetafieldReferenceConnection"
    type: "String"
    updated_at: "DateTime"
    value: "String"

    