
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.metafield_definition import MetafieldDefinition
    from schema.objects.metafield_definition_edge import MetafieldDefinitionEdge
    from schema.objects.page_info import PageInfo



class MetafieldDefinitionConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "MetafieldDefinitionEdge")
        nodes = ObjectField("nodes", "MetafieldDefinition")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "MetafieldDefinitionEdge"
    nodes: "MetafieldDefinition"
    page_info: "PageInfo"

    