
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.metaobject_definition import MetaobjectDefinition
    from schema.objects.metaobject_definition_edge import MetaobjectDefinitionEdge
    from schema.objects.page_info import PageInfo



class MetaobjectDefinitionConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "MetaobjectDefinitionEdge")
        nodes = ObjectField("nodes", "MetaobjectDefinition")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "MetaobjectDefinitionEdge"
    nodes: "MetaobjectDefinition"
    page_info: "PageInfo"

    