
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.metafield_definition_type import MetafieldDefinitionType
    from schema.objects.metafield_definition_validation import MetafieldDefinitionValidation
    from schema.scalars.boolean import Boolean
    from schema.scalars.string import String



class MetaobjectFieldDefinition(ObjectType):
    class Fields:
        description = ScalarField("description", "String")
        key = ScalarField("key", "String")
        name = ScalarField("name", "String")
        required = ScalarField("required", "Boolean")
        type = ObjectField("type", "MetafieldDefinitionType")
        validations = ObjectField("validations", "MetafieldDefinitionValidation")

    description: "String"
    key: "String"
    name: "String"
    required: "Boolean"
    type: "MetafieldDefinitionType"
    validations: "MetafieldDefinitionValidation"

    