
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.metafield_storefront_visibility import MetafieldStorefrontVisibility
    from schema.objects.metafield_storefront_visibility_edge import MetafieldStorefrontVisibilityEdge
    from schema.objects.page_info import PageInfo



class MetafieldStorefrontVisibilityConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "MetafieldStorefrontVisibilityEdge")
        nodes = ObjectField("nodes", "MetafieldStorefrontVisibility")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "MetafieldStorefrontVisibilityEdge"
    nodes: "MetafieldStorefrontVisibility"
    page_info: "PageInfo"

    