
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.metafield_owner_type import MetafieldOwnerType
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.string import String
    from schema.scalars.unsigned_int64 import UnsignedInt64



class MetafieldStorefrontVisibility(ObjectType):
    class Fields:
        created_at = ScalarField("createdAt", "DateTime")
        id = ScalarField("id", "ID")
        key = ScalarField("key", "String")
        legacy_resource_id = ScalarField("legacyResourceId", "UnsignedInt64")
        namespace = ScalarField("namespace", "String")
        owner_type = EnumField("ownerType", "MetafieldOwnerType")
        updated_at = ScalarField("updatedAt", "DateTime")

    created_at: "DateTime"
    id: "ID"
    key: "String"
    legacy_resource_id: "UnsignedInt64"
    namespace: "String"
    owner_type: "MetafieldOwnerType"
    updated_at: "DateTime"

    