
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.metafield_definition_validation_status import MetafieldDefinitionValidationStatus
    from schema.enums.metafield_owner_type import MetafieldOwnerType
    from schema.objects.metafield_access import MetafieldAccess
    from schema.objects.metafield_capabilities import MetafieldCapabilities
    from schema.objects.metafield_connection import MetafieldConnection
    from schema.objects.metafield_definition_constraints import MetafieldDefinitionConstraints
    from schema.objects.metafield_definition_type import MetafieldDefinitionType
    from schema.objects.metafield_definition_validation import MetafieldDefinitionValidation
    from schema.objects.standard_metafield_definition_template import StandardMetafieldDefinitionTemplate
    from schema.scalars.boolean import Boolean
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.string import String



class MetafieldDefinition(ObjectType):
    class Fields:
        access = ObjectField("access", "MetafieldAccess")
        capabilities = ObjectField("capabilities", "MetafieldCapabilities")
        constraints = ObjectField("constraints", "MetafieldDefinitionConstraints")
        description = ScalarField("description", "String")
        id = ScalarField("id", "ID")
        key = ScalarField("key", "String")
        metafields = ObjectField("metafields", "MetafieldConnection")
        metafields_count = ScalarField("metafieldsCount", "Int")
        name = ScalarField("name", "String")
        namespace = ScalarField("namespace", "String")
        owner_type = EnumField("ownerType", "MetafieldOwnerType")
        pinned_position = ScalarField("pinnedPosition", "Int")
        standard_template = ObjectField("standardTemplate", "StandardMetafieldDefinitionTemplate")
        type = ObjectField("type", "MetafieldDefinitionType")
        use_as_collection_condition = ScalarField("useAsCollectionCondition", "Boolean")
        validation_status = EnumField("validationStatus", "MetafieldDefinitionValidationStatus")
        validations = ObjectField("validations", "MetafieldDefinitionValidation")
        visible_to_storefront_api = ScalarField("visibleToStorefrontApi", "Boolean")

    access: "MetafieldAccess"
    capabilities: "MetafieldCapabilities"
    constraints: "MetafieldDefinitionConstraints"
    description: "String"
    id: "ID"
    key: "String"
    metafields: "MetafieldConnection"
    metafields_count: "Int"
    name: "String"
    namespace: "String"
    owner_type: "MetafieldOwnerType"
    pinned_position: "Int"
    standard_template: "StandardMetafieldDefinitionTemplate"
    type: "MetafieldDefinitionType"
    use_as_collection_condition: "Boolean"
    validation_status: "MetafieldDefinitionValidationStatus"
    validations: "MetafieldDefinitionValidation"
    visible_to_storefront_api: "Boolean"

    