
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.metafield_definition import MetafieldDefinition
    from schema.scalars.string import String



class MetafieldDefinitionEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "MetafieldDefinition")

    cursor: "String"
    node: "MetafieldDefinition"

    