
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.metafield_relation import MetafieldRelation
    from schema.scalars.string import String



class MetafieldRelationEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "MetafieldRelation")

    cursor: "String"
    node: "MetafieldRelation"

    