
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.mobile_platform_application_user_error import MobilePlatformApplicationUserError
    from schema.scalars.id import ID



class MobilePlatformApplicationDeletePayload(ObjectType):
    class Fields:
        deleted_mobile_platform_application_id = ScalarField("deletedMobilePlatformApplicationId", "ID")
        user_errors = ObjectField("userErrors", "MobilePlatformApplicationUserError")

    deleted_mobile_platform_application_id: "ID"
    user_errors: "MobilePlatformApplicationUserError"

    