
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.currency_code import CurrencyCode
    from schema.scalars.decimal import Decimal



class MoneyV2(ObjectType):
    class Fields:
        amount = ScalarField("amount", "Decimal")
        currency_code = EnumField("currencyCode", "CurrencyCode")

    amount: "Decimal"
    currency_code: "CurrencyCode"

    