
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.string import String
    from schema.scalars.url import URL



class NavigationItem(ObjectType):
    class Fields:
        id = ScalarField("id", "String")
        title = ScalarField("title", "String")
        url = ScalarField("url", "URL")

    id: "String"
    title: "String"
    url: "URL"

    