
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.online_store_theme_files_user_errors_code import OnlineStoreThemeFilesUserErrorsCode
    from schema.scalars.string import String



class OnlineStoreThemeFilesUserErrors(ObjectType):
    class Fields:
        code = EnumField("code", "OnlineStoreThemeFilesUserErrorsCode")
        field = ScalarField("field", "String")
        filename = ScalarField("filename", "String")
        message = ScalarField("message", "String")

    code: "OnlineStoreThemeFilesUserErrorsCode"
    field: "String"
    filename: "String"
    message: "String"

    