
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.url import URL



class OnlineStoreThemeFileBodyUrl(ObjectType):
    class Fields:
        url = ScalarField("url", "URL")

    url: "URL"

    