
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.online_store_theme_file import OnlineStoreThemeFile
    from schema.scalars.string import String



class OnlineStoreThemeFileEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "OnlineStoreThemeFile")

    cursor: "String"
    node: "OnlineStoreThemeFile"

    