
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.theme_role import ThemeRole
    from schema.objects.online_store_theme_file_connection import OnlineStoreThemeFileConnection
    from schema.objects.translation import Translation
    from schema.scalars.boolean import Boolean
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.string import String



class OnlineStoreTheme(ObjectType):
    class Fields:
        created_at = ScalarField("createdAt", "DateTime")
        files = ObjectField("files", "OnlineStoreThemeFileConnection")
        id = ScalarField("id", "ID")
        name = ScalarField("name", "String")
        prefix = ScalarField("prefix", "String")
        processing = ScalarField("processing", "Boolean")
        processing_failed = ScalarField("processingFailed", "Boolean")
        role = EnumField("role", "ThemeRole")
        theme_store_id = ScalarField("themeStoreId", "Int")
        translations = ObjectField("translations", "Translation")
        updated_at = ScalarField("updatedAt", "DateTime")

    created_at: "DateTime"
    files: "OnlineStoreThemeFileConnection"
    id: "ID"
    name: "String"
    prefix: "String"
    processing: "Boolean"
    processing_failed: "Boolean"
    role: "ThemeRole"
    theme_store_id: "Int"
    translations: "Translation"
    updated_at: "DateTime"

    