
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.dispute_status import DisputeStatus
    from schema.enums.dispute_type import DisputeType
    from schema.scalars.id import ID



class OrderDisputeSummary(ObjectType):
    class Fields:
        id = ScalarField("id", "ID")
        initiated_as = EnumField("initiatedAs", "DisputeType")
        status = EnumField("status", "DisputeStatus")

    id: "ID"
    initiated_as: "DisputeType"
    status: "DisputeStatus"

    