
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.order_create_mandate_payment_user_error_code import OrderCreateMandatePaymentUserErrorCode
    from schema.scalars.string import String



class OrderCreateMandatePaymentUserError(ObjectType):
    class Fields:
        code = EnumField("code", "OrderCreateMandatePaymentUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "OrderCreateMandatePaymentUserErrorCode"
    field: "String"
    message: "String"

    