
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.order_adjustment import OrderAdjustment
    from schema.objects.order_adjustment_edge import OrderAdjustmentEdge
    from schema.objects.page_info import PageInfo



class OrderAdjustmentConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "OrderAdjustmentEdge")
        nodes = ObjectField("nodes", "OrderAdjustment")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "OrderAdjustmentEdge"
    nodes: "OrderAdjustment"
    page_info: "PageInfo"

    