
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.money_v2 import MoneyV2
    from schema.scalars.int import Int
    from schema.scalars.string import String



class OrderStagedChangeAddCustomItem(ObjectType):
    class Fields:
        original_unit_price = ObjectField("originalUnitPrice", "MoneyV2")
        quantity = ScalarField("quantity", "Int")
        title = ScalarField("title", "String")

    original_unit_price: "MoneyV2"
    quantity: "Int"
    title: "String"

    