
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.shipping_line import ShippingLine



class OrderStagedChangeRemoveShippingLine(ObjectType):
    class Fields:
        shipping_line = ObjectField("shippingLine", "ShippingLine")

    shipping_line: "ShippingLine"

    