
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.calculated_order import CalculatedOrder
    from schema.objects.order_edit_remove_discount_user_error import OrderEditRemoveDiscountUserError



class OrderEditRemoveDiscountPayload(ObjectType):
    class Fields:
        calculated_order = ObjectField("calculatedOrder", "CalculatedOrder")
        user_errors = ObjectField("userErrors", "OrderEditRemoveDiscountUserError")

    calculated_order: "CalculatedOrder"
    user_errors: "OrderEditRemoveDiscountUserError"

    