
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.image import Image
    from schema.scalars.id import ID
    from schema.scalars.string import String



class OrderApp(ObjectType):
    class Fields:
        icon = ObjectField("icon", "Image")
        id = ScalarField("id", "ID")
        name = ScalarField("name", "String")

    icon: "Image"
    id: "ID"
    name: "String"

    