
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.calculated_line_item import CalculatedLineItem
    from schema.objects.calculated_order import CalculatedOrder
    from schema.objects.user_error import UserError



class OrderEditAddVariantPayload(ObjectType):
    class Fields:
        calculated_line_item = ObjectField("calculatedLineItem", "CalculatedLineItem")
        calculated_order = ObjectField("calculatedOrder", "CalculatedOrder")
        user_errors = ObjectField("userErrors", "UserError")

    calculated_line_item: "CalculatedLineItem"
    calculated_order: "CalculatedOrder"
    user_errors: "UserError"

    