
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.order_edit_update_shipping_line_user_error_code import OrderEditUpdateShippingLineUserErrorCode
    from schema.scalars.string import String



class OrderEditUpdateShippingLineUserError(ObjectType):
    class Fields:
        code = EnumField("code", "OrderEditUpdateShippingLineUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "OrderEditUpdateShippingLineUserErrorCode"
    field: "String"
    message: "String"

    