
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.risk_assessment_result import RiskAssessmentResult
    from schema.objects.app import App
    from schema.objects.risk_fact import RiskFact



class OrderRiskAssessment(ObjectType):
    class Fields:
        facts = ObjectField("facts", "RiskFact")
        provider = ObjectField("provider", "App")
        risk_level = EnumField("riskLevel", "RiskAssessmentResult")

    facts: "RiskFact"
    provider: "App"
    risk_level: "RiskAssessmentResult"

    