
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.order_adjustment import OrderAdjustment
    from schema.scalars.string import String



class OrderAdjustmentEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "OrderAdjustment")

    cursor: "String"
    node: "OrderAdjustment"

    