
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.currency_code import CurrencyCode
    from schema.enums.order_cancel_reason import OrderCancelReason
    from schema.enums.order_display_financial_status import OrderDisplayFinancialStatus
    from schema.enums.order_display_fulfillment_status import OrderDisplayFulfillmentStatus
    from schema.enums.order_return_status import OrderReturnStatus
    from schema.enums.order_risk_level import OrderRiskLevel
    from schema.objects.additional_fee import AdditionalFee
    from schema.objects.attribute import Attribute
    from schema.objects.business_entity import BusinessEntity
    from schema.objects.cash_rounding_adjustment import CashRoundingAdjustment
    from schema.objects.channel import Channel
    from schema.objects.channel_information import ChannelInformation
    from schema.objects.count import Count
    from schema.objects.customer import Customer
    from schema.objects.customer_journey import CustomerJourney
    from schema.objects.customer_journey_summary import CustomerJourneySummary
    from schema.objects.discount_application_connection import DiscountApplicationConnection
    from schema.objects.event_connection import EventConnection
    from schema.objects.exchange_v2_connection import ExchangeV2Connection
    from schema.objects.fulfillment import Fulfillment
    from schema.objects.fulfillment_order_connection import FulfillmentOrderConnection
    from schema.objects.line_item_connection import LineItemConnection
    from schema.objects.localization_extension_connection import LocalizationExtensionConnection
    from schema.objects.location import Location
    from schema.objects.mailing_address import MailingAddress
    from schema.objects.metafield import Metafield
    from schema.objects.metafield_connection import MetafieldConnection
    from schema.objects.metafield_definition_connection import MetafieldDefinitionConnection
    from schema.objects.money_bag import MoneyBag
    from schema.objects.money_v2 import MoneyV2
    from schema.objects.order_app import OrderApp
    from schema.objects.order_cancellation import OrderCancellation
    from schema.objects.order_dispute_summary import OrderDisputeSummary
    from schema.objects.order_payment_collection_details import OrderPaymentCollectionDetails
    from schema.objects.order_risk import OrderRisk
    from schema.objects.order_risk_summary import OrderRiskSummary
    from schema.objects.order_transaction import OrderTransaction
    from schema.objects.payment_terms import PaymentTerms
    from schema.objects.private_metafield import PrivateMetafield
    from schema.objects.private_metafield_connection import PrivateMetafieldConnection
    from schema.objects.publication import Publication
    from schema.objects.refund import Refund
    from schema.objects.resource_alert import ResourceAlert
    from schema.objects.return_connection import ReturnConnection
    from schema.objects.sales_agreement_connection import SalesAgreementConnection
    from schema.objects.shipping_line import ShippingLine
    from schema.objects.shipping_line_connection import ShippingLineConnection
    from schema.objects.shopify_protect_order_summary import ShopifyProtectOrderSummary
    from schema.objects.staff_member import StaffMember
    from schema.objects.suggested_refund import SuggestedRefund
    from schema.objects.tax_line import TaxLine
    from schema.scalars.boolean import Boolean
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.money import Money
    from schema.scalars.string import String
    from schema.scalars.unsigned_int64 import UnsignedInt64
    from schema.scalars.url import URL
    from schema.unions.purchasing_entity import PurchasingEntity



class Order(ObjectType):
    class Fields:
        additional_fees = ObjectField("additionalFees", "AdditionalFee")
        agreements = ObjectField("agreements", "SalesAgreementConnection")
        alerts = ObjectField("alerts", "ResourceAlert")
        app = ObjectField("app", "OrderApp")
        billing_address = ObjectField("billingAddress", "MailingAddress")
        billing_address_matches_shipping_address = ScalarField("billingAddressMatchesShippingAddress", "Boolean")
        can_mark_as_paid = ScalarField("canMarkAsPaid", "Boolean")
        can_notify_customer = ScalarField("canNotifyCustomer", "Boolean")
        cancel_reason = EnumField("cancelReason", "OrderCancelReason")
        cancellation = ObjectField("cancellation", "OrderCancellation")
        cancelled_at = ScalarField("cancelledAt", "DateTime")
        capturable = ScalarField("capturable", "Boolean")
        cart_discount_amount = ScalarField("cartDiscountAmount", "Money")
        cart_discount_amount_set = ObjectField("cartDiscountAmountSet", "MoneyBag")
        channel = ObjectField("channel", "Channel")
        channel_information = ObjectField("channelInformation", "ChannelInformation")
        client_ip = ScalarField("clientIp", "String")
        closed = ScalarField("closed", "Boolean")
        closed_at = ScalarField("closedAt", "DateTime")
        confirmation_number = ScalarField("confirmationNumber", "String")
        confirmed = ScalarField("confirmed", "Boolean")
        created_at = ScalarField("createdAt", "DateTime")
        currency_code = EnumField("currencyCode", "CurrencyCode")
        current_cart_discount_amount_set = ObjectField("currentCartDiscountAmountSet", "MoneyBag")
        current_shipping_price_set = ObjectField("currentShippingPriceSet", "MoneyBag")
        current_subtotal_line_items_quantity = ScalarField("currentSubtotalLineItemsQuantity", "Int")
        current_subtotal_price_set = ObjectField("currentSubtotalPriceSet", "MoneyBag")
        current_tax_lines = ObjectField("currentTaxLines", "TaxLine")
        current_total_additional_fees_set = ObjectField("currentTotalAdditionalFeesSet", "MoneyBag")
        current_total_discounts_set = ObjectField("currentTotalDiscountsSet", "MoneyBag")
        current_total_duties_set = ObjectField("currentTotalDutiesSet", "MoneyBag")
        current_total_price_set = ObjectField("currentTotalPriceSet", "MoneyBag")
        current_total_tax_set = ObjectField("currentTotalTaxSet", "MoneyBag")
        current_total_weight = ScalarField("currentTotalWeight", "UnsignedInt64")
        custom_attributes = ObjectField("customAttributes", "Attribute")
        customer = ObjectField("customer", "Customer")
        customer_accepts_marketing = ScalarField("customerAcceptsMarketing", "Boolean")
        customer_journey = ObjectField("customerJourney", "CustomerJourney")
        customer_journey_summary = ObjectField("customerJourneySummary", "CustomerJourneySummary")
        customer_locale = ScalarField("customerLocale", "String")
        discount_applications = ObjectField("discountApplications", "DiscountApplicationConnection")
        discount_code = ScalarField("discountCode", "String")
        discount_codes = ScalarField("discountCodes", "String")
        display_address = ObjectField("displayAddress", "MailingAddress")
        display_financial_status = EnumField("displayFinancialStatus", "OrderDisplayFinancialStatus")
        display_fulfillment_status = EnumField("displayFulfillmentStatus", "OrderDisplayFulfillmentStatus")
        disputes = ObjectField("disputes", "OrderDisputeSummary")
        duties_included = ScalarField("dutiesIncluded", "Boolean")
        edited = ScalarField("edited", "Boolean")
        email = ScalarField("email", "String")
        estimated_taxes = ScalarField("estimatedTaxes", "Boolean")
        events = ObjectField("events", "EventConnection")
        exchange_v2s = ObjectField("exchangeV2s", "ExchangeV2Connection")
        fulfillable = ScalarField("fulfillable", "Boolean")
        fulfillment_orders = ObjectField("fulfillmentOrders", "FulfillmentOrderConnection")
        fulfillments = ObjectField("fulfillments", "Fulfillment")
        fulfillments_count = ObjectField("fulfillmentsCount", "Count")
        fully_paid = ScalarField("fullyPaid", "Boolean")
        has_timeline_comment = ScalarField("hasTimelineComment", "Boolean")
        id = ScalarField("id", "ID")
        landing_page_display_text = ScalarField("landingPageDisplayText", "String")
        landing_page_url = ScalarField("landingPageUrl", "URL")
        legacy_resource_id = ScalarField("legacyResourceId", "UnsignedInt64")
        line_items = ObjectField("lineItems", "LineItemConnection")
        localization_extensions = ObjectField("localizationExtensions", "LocalizationExtensionConnection")
        merchant_business_entity = ObjectField("merchantBusinessEntity", "BusinessEntity")
        merchant_editable = ScalarField("merchantEditable", "Boolean")
        merchant_editable_errors = ScalarField("merchantEditableErrors", "String")
        merchant_of_record_app = ObjectField("merchantOfRecordApp", "OrderApp")
        metafield = ObjectField("metafield", "Metafield")
        metafield_definitions = ObjectField("metafieldDefinitions", "MetafieldDefinitionConnection")
        metafields = ObjectField("metafields", "MetafieldConnection")
        name = ScalarField("name", "String")
        net_payment = ScalarField("netPayment", "Money")
        net_payment_set = ObjectField("netPaymentSet", "MoneyBag")
        non_fulfillable_line_items = ObjectField("nonFulfillableLineItems", "LineItemConnection")
        note = ScalarField("note", "String")
        original_total_additional_fees_set = ObjectField("originalTotalAdditionalFeesSet", "MoneyBag")
        original_total_duties_set = ObjectField("originalTotalDutiesSet", "MoneyBag")
        original_total_price_set = ObjectField("originalTotalPriceSet", "MoneyBag")
        payment_collection_details = ObjectField("paymentCollectionDetails", "OrderPaymentCollectionDetails")
        payment_gateway_names = ScalarField("paymentGatewayNames", "String")
        payment_terms = ObjectField("paymentTerms", "PaymentTerms")
        phone = ScalarField("phone", "String")
        physical_location = ObjectField("physicalLocation", "Location")
        po_number = ScalarField("poNumber", "String")
        presentment_currency_code = EnumField("presentmentCurrencyCode", "CurrencyCode")
        private_metafield = ObjectField("privateMetafield", "PrivateMetafield")
        private_metafields = ObjectField("privateMetafields", "PrivateMetafieldConnection")
        processed_at = ScalarField("processedAt", "DateTime")
        publication = ObjectField("publication", "Publication")
        purchasing_entity = UnionField("purchasingEntity", "PurchasingEntity")
        referral_code = ScalarField("referralCode", "String")
        referrer_display_text = ScalarField("referrerDisplayText", "String")
        referrer_url = ScalarField("referrerUrl", "URL")
        refund_discrepancy_set = ObjectField("refundDiscrepancySet", "MoneyBag")
        refundable = ScalarField("refundable", "Boolean")
        refunds = ObjectField("refunds", "Refund")
        registered_source_url = ScalarField("registeredSourceUrl", "URL")
        requires_shipping = ScalarField("requiresShipping", "Boolean")
        restockable = ScalarField("restockable", "Boolean")
        retail_location = ObjectField("retailLocation", "Location")
        return_status = EnumField("returnStatus", "OrderReturnStatus")
        returns = ObjectField("returns", "ReturnConnection")
        risk = ObjectField("risk", "OrderRiskSummary")
        risk_level = EnumField("riskLevel", "OrderRiskLevel")
        risks = ObjectField("risks", "OrderRisk")
        shipping_address = ObjectField("shippingAddress", "MailingAddress")
        shipping_line = ObjectField("shippingLine", "ShippingLine")
        shipping_lines = ObjectField("shippingLines", "ShippingLineConnection")
        shopify_protect = ObjectField("shopifyProtect", "ShopifyProtectOrderSummary")
        source_identifier = ScalarField("sourceIdentifier", "String")
        source_name = ScalarField("sourceName", "String")
        staff_member = ObjectField("staffMember", "StaffMember")
        status_page_url = ScalarField("statusPageUrl", "URL")
        subtotal_line_items_quantity = ScalarField("subtotalLineItemsQuantity", "Int")
        subtotal_price = ScalarField("subtotalPrice", "Money")
        subtotal_price_set = ObjectField("subtotalPriceSet", "MoneyBag")
        suggested_refund = ObjectField("suggestedRefund", "SuggestedRefund")
        tags = ScalarField("tags", "String")
        tax_exempt = ScalarField("taxExempt", "Boolean")
        tax_lines = ObjectField("taxLines", "TaxLine")
        taxes_included = ScalarField("taxesIncluded", "Boolean")
        test = ScalarField("test", "Boolean")
        total_capturable = ScalarField("totalCapturable", "Money")
        total_capturable_set = ObjectField("totalCapturableSet", "MoneyBag")
        total_cash_rounding_adjustment = ObjectField("totalCashRoundingAdjustment", "CashRoundingAdjustment")
        total_discounts = ScalarField("totalDiscounts", "Money")
        total_discounts_set = ObjectField("totalDiscountsSet", "MoneyBag")
        total_outstanding_set = ObjectField("totalOutstandingSet", "MoneyBag")
        total_price = ScalarField("totalPrice", "Money")
        total_price_set = ObjectField("totalPriceSet", "MoneyBag")
        total_received = ScalarField("totalReceived", "Money")
        total_received_set = ObjectField("totalReceivedSet", "MoneyBag")
        total_refunded = ScalarField("totalRefunded", "Money")
        total_refunded_set = ObjectField("totalRefundedSet", "MoneyBag")
        total_refunded_shipping_set = ObjectField("totalRefundedShippingSet", "MoneyBag")
        total_shipping_price = ScalarField("totalShippingPrice", "Money")
        total_shipping_price_set = ObjectField("totalShippingPriceSet", "MoneyBag")
        total_tax = ScalarField("totalTax", "Money")
        total_tax_set = ObjectField("totalTaxSet", "MoneyBag")
        total_tip_received = ObjectField("totalTipReceived", "MoneyV2")
        total_tip_received_set = ObjectField("totalTipReceivedSet", "MoneyBag")
        total_weight = ScalarField("totalWeight", "UnsignedInt64")
        transactions = ObjectField("transactions", "OrderTransaction")
        transactions_count = ObjectField("transactionsCount", "Count")
        unpaid = ScalarField("unpaid", "Boolean")
        updated_at = ScalarField("updatedAt", "DateTime")

    additional_fees: "AdditionalFee"
    agreements: "SalesAgreementConnection"
    alerts: "ResourceAlert"
    app: "OrderApp"
    billing_address: "MailingAddress"
    billing_address_matches_shipping_address: "Boolean"
    can_mark_as_paid: "Boolean"
    can_notify_customer: "Boolean"
    cancel_reason: "OrderCancelReason"
    cancellation: "OrderCancellation"
    cancelled_at: "DateTime"
    capturable: "Boolean"
    cart_discount_amount: "Money"
    cart_discount_amount_set: "MoneyBag"
    channel: "Channel"
    channel_information: "ChannelInformation"
    client_ip: "String"
    closed: "Boolean"
    closed_at: "DateTime"
    confirmation_number: "String"
    confirmed: "Boolean"
    created_at: "DateTime"
    currency_code: "CurrencyCode"
    current_cart_discount_amount_set: "MoneyBag"
    current_shipping_price_set: "MoneyBag"
    current_subtotal_line_items_quantity: "Int"
    current_subtotal_price_set: "MoneyBag"
    current_tax_lines: "TaxLine"
    current_total_additional_fees_set: "MoneyBag"
    current_total_discounts_set: "MoneyBag"
    current_total_duties_set: "MoneyBag"
    current_total_price_set: "MoneyBag"
    current_total_tax_set: "MoneyBag"
    current_total_weight: "UnsignedInt64"
    custom_attributes: "Attribute"
    customer: "Customer"
    customer_accepts_marketing: "Boolean"
    customer_journey: "CustomerJourney"
    customer_journey_summary: "CustomerJourneySummary"
    customer_locale: "String"
    discount_applications: "DiscountApplicationConnection"
    discount_code: "String"
    discount_codes: "String"
    display_address: "MailingAddress"
    display_financial_status: "OrderDisplayFinancialStatus"
    display_fulfillment_status: "OrderDisplayFulfillmentStatus"
    disputes: "OrderDisputeSummary"
    duties_included: "Boolean"
    edited: "Boolean"
    email: "String"
    estimated_taxes: "Boolean"
    events: "EventConnection"
    exchange_v2s: "ExchangeV2Connection"
    fulfillable: "Boolean"
    fulfillment_orders: "FulfillmentOrderConnection"
    fulfillments: "Fulfillment"
    fulfillments_count: "Count"
    fully_paid: "Boolean"
    has_timeline_comment: "Boolean"
    id: "ID"
    landing_page_display_text: "String"
    landing_page_url: "URL"
    legacy_resource_id: "UnsignedInt64"
    line_items: "LineItemConnection"
    localization_extensions: "LocalizationExtensionConnection"
    merchant_business_entity: "BusinessEntity"
    merchant_editable: "Boolean"
    merchant_editable_errors: "String"
    merchant_of_record_app: "OrderApp"
    metafield: "Metafield"
    metafield_definitions: "MetafieldDefinitionConnection"
    metafields: "MetafieldConnection"
    name: "String"
    net_payment: "Money"
    net_payment_set: "MoneyBag"
    non_fulfillable_line_items: "LineItemConnection"
    note: "String"
    original_total_additional_fees_set: "MoneyBag"
    original_total_duties_set: "MoneyBag"
    original_total_price_set: "MoneyBag"
    payment_collection_details: "OrderPaymentCollectionDetails"
    payment_gateway_names: "String"
    payment_terms: "PaymentTerms"
    phone: "String"
    physical_location: "Location"
    po_number: "String"
    presentment_currency_code: "CurrencyCode"
    private_metafield: "PrivateMetafield"
    private_metafields: "PrivateMetafieldConnection"
    processed_at: "DateTime"
    publication: "Publication"
    purchasing_entity: "PurchasingEntity"
    referral_code: "String"
    referrer_display_text: "String"
    referrer_url: "URL"
    refund_discrepancy_set: "MoneyBag"
    refundable: "Boolean"
    refunds: "Refund"
    registered_source_url: "URL"
    requires_shipping: "Boolean"
    restockable: "Boolean"
    retail_location: "Location"
    return_status: "OrderReturnStatus"
    returns: "ReturnConnection"
    risk: "OrderRiskSummary"
    risk_level: "OrderRiskLevel"
    risks: "OrderRisk"
    shipping_address: "MailingAddress"
    shipping_line: "ShippingLine"
    shipping_lines: "ShippingLineConnection"
    shopify_protect: "ShopifyProtectOrderSummary"
    source_identifier: "String"
    source_name: "String"
    staff_member: "StaffMember"
    status_page_url: "URL"
    subtotal_line_items_quantity: "Int"
    subtotal_price: "Money"
    subtotal_price_set: "MoneyBag"
    suggested_refund: "SuggestedRefund"
    tags: "String"
    tax_exempt: "Boolean"
    tax_lines: "TaxLine"
    taxes_included: "Boolean"
    test: "Boolean"
    total_capturable: "Money"
    total_capturable_set: "MoneyBag"
    total_cash_rounding_adjustment: "CashRoundingAdjustment"
    total_discounts: "Money"
    total_discounts_set: "MoneyBag"
    total_outstanding_set: "MoneyBag"
    total_price: "Money"
    total_price_set: "MoneyBag"
    total_received: "Money"
    total_received_set: "MoneyBag"
    total_refunded: "Money"
    total_refunded_set: "MoneyBag"
    total_refunded_shipping_set: "MoneyBag"
    total_shipping_price: "Money"
    total_shipping_price_set: "MoneyBag"
    total_tax: "Money"
    total_tax_set: "MoneyBag"
    total_tip_received: "MoneyV2"
    total_tip_received_set: "MoneyBag"
    total_weight: "UnsignedInt64"
    transactions: "OrderTransaction"
    transactions_count: "Count"
    unpaid: "Boolean"
    updated_at: "DateTime"

    