
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.order_transaction import OrderTransaction
    from schema.objects.order_transaction_edge import OrderTransactionEdge
    from schema.objects.page_info import PageInfo



class OrderTransactionConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "OrderTransactionEdge")
        nodes = ObjectField("nodes", "OrderTransaction")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "OrderTransactionEdge"
    nodes: "OrderTransaction"
    page_info: "PageInfo"

    