
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.id import ID
    from schema.scalars.string import String
    from schema.unions.pricing_value import PricingValue



class OrderStagedChangeAddLineItemDiscount(ObjectType):
    class Fields:
        description = ScalarField("description", "String")
        id = ScalarField("id", "ID")
        value = UnionField("value", "PricingValue")

    description: "String"
    id: "ID"
    value: "PricingValue"

    