
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.order_edit_update_discount_user_error_code import OrderEditUpdateDiscountUserErrorCode
    from schema.scalars.string import String



class OrderEditUpdateDiscountUserError(ObjectType):
    class Fields:
        code = EnumField("code", "OrderEditUpdateDiscountUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "OrderEditUpdateDiscountUserErrorCode"
    field: "String"
    message: "String"

    