
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.order_transaction import OrderTransaction
    from schema.objects.user_error import UserError



class OrderCapturePayload(ObjectType):
    class Fields:
        transaction = ObjectField("transaction", "OrderTransaction")
        user_errors = ObjectField("userErrors", "UserError")

    transaction: "OrderTransaction"
    user_errors: "UserError"

    