
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.boolean import Boolean
    from schema.scalars.string import String



class PageInfo(ObjectType):
    class Fields:
        end_cursor = ScalarField("endCursor", "String")
        has_next_page = ScalarField("hasNextPage", "Boolean")
        has_previous_page = ScalarField("hasPreviousPage", "Boolean")
        start_cursor = ScalarField("startCursor", "String")

    end_cursor: "String"
    has_next_page: "Boolean"
    has_previous_page: "Boolean"
    start_cursor: "String"

    