
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page import Page
    from schema.objects.page_edge import PageEdge
    from schema.objects.page_info import PageInfo



class PageConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "PageEdge")
        nodes = ObjectField("nodes", "Page")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "PageEdge"
    nodes: "Page"
    page_info: "PageInfo"

    