
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.page_update_user_error_code import PageUpdateUserErrorCode
    from schema.scalars.string import String



class PageUpdateUserError(ObjectType):
    class Fields:
        code = EnumField("code", "PageUpdateUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "PageUpdateUserErrorCode"
    field: "String"
    message: "String"

    