
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.payment_customization_error import PaymentCustomizationError
    from schema.scalars.string import String



class PaymentCustomizationActivationPayload(ObjectType):
    class Fields:
        ids = ScalarField("ids", "String")
        user_errors = ObjectField("userErrors", "PaymentCustomizationError")

    ids: "String"
    user_errors: "PaymentCustomizationError"

    