
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.payment_terms_delete_user_error_code import PaymentTermsDeleteUserErrorCode
    from schema.scalars.string import String



class PaymentTermsDeleteUserError(ObjectType):
    class Fields:
        code = EnumField("code", "PaymentTermsDeleteUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "PaymentTermsDeleteUserErrorCode"
    field: "String"
    message: "String"

    