
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.id import ID
    from schema.unions.payment_instrument import PaymentInstrument



class PaymentMandate(ObjectType):
    class Fields:
        id = ScalarField("id", "ID")
        payment_instrument = UnionField("paymentInstrument", "PaymentInstrument")

    id: "ID"
    payment_instrument: "PaymentInstrument"

    