
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.payment_terms_type import PaymentTermsType
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.string import String



class PaymentTermsTemplate(ObjectType):
    class Fields:
        description = ScalarField("description", "String")
        due_in_days = ScalarField("dueInDays", "Int")
        id = ScalarField("id", "ID")
        name = ScalarField("name", "String")
        payment_terms_type = EnumField("paymentTermsType", "PaymentTermsType")
        translated_name = ScalarField("translatedName", "String")

    description: "String"
    due_in_days: "Int"
    id: "ID"
    name: "String"
    payment_terms_type: "PaymentTermsType"
    translated_name: "String"

    