
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.payment_customization_error_code import PaymentCustomizationErrorCode
    from schema.scalars.string import String



class PaymentCustomizationError(ObjectType):
    class Fields:
        code = EnumField("code", "PaymentCustomizationErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "PaymentCustomizationErrorCode"
    field: "String"
    message: "String"

    