
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.payment_customization_error import PaymentCustomizationError
    from schema.scalars.id import ID



class PaymentCustomizationDeletePayload(ObjectType):
    class Fields:
        deleted_id = ScalarField("deletedId", "ID")
        user_errors = ObjectField("userErrors", "PaymentCustomizationError")

    deleted_id: "ID"
    user_errors: "PaymentCustomizationError"

    