
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.payment_customization import PaymentCustomization
    from schema.scalars.string import String



class PaymentCustomizationEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "PaymentCustomization")

    cursor: "String"
    node: "PaymentCustomization"

    