
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.money_v2 import MoneyV2
    from schema.objects.payment_terms import PaymentTerms
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID



class PaymentSchedule(ObjectType):
    class Fields:
        amount = ObjectField("amount", "MoneyV2")
        completed_at = ScalarField("completedAt", "DateTime")
        due_at = ScalarField("dueAt", "DateTime")
        id = ScalarField("id", "ID")
        issued_at = ScalarField("issuedAt", "DateTime")
        payment_terms = ObjectField("paymentTerms", "PaymentTerms")

    amount: "MoneyV2"
    completed_at: "DateTime"
    due_at: "DateTime"
    id: "ID"
    issued_at: "DateTime"
    payment_terms: "PaymentTerms"

    