
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.payment_customization import PaymentCustomization
    from schema.objects.payment_customization_error import PaymentCustomizationError



class PaymentCustomizationUpdatePayload(ObjectType):
    class Fields:
        payment_customization = ObjectField("paymentCustomization", "PaymentCustomization")
        user_errors = ObjectField("userErrors", "PaymentCustomizationError")

    payment_customization: "PaymentCustomization"
    user_errors: "PaymentCustomizationError"

    