
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.payment_terms import PaymentTerms
    from schema.objects.payment_terms_update_user_error import PaymentTermsUpdateUserError



class PaymentTermsUpdatePayload(ObjectType):
    class Fields:
        payment_terms = ObjectField("paymentTerms", "PaymentTerms")
        user_errors = ObjectField("userErrors", "PaymentTermsUpdateUserError")

    payment_terms: "PaymentTerms"
    user_errors: "PaymentTermsUpdateUserError"

    