
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.price_rule_discount_code import PriceRuleDiscountCode
    from schema.scalars.string import String



class PriceRuleDiscountCodeEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "PriceRuleDiscountCode")

    cursor: "String"
    node: "PriceRuleDiscountCode"

    