
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.money import Money



class PriceRuleFixedAmountValue(ObjectType):
    class Fields:
        amount = ScalarField("amount", "Money")

    amount: "Money"

    