
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.price_list_fixed_prices_by_product_bulk_update_user_error_code import PriceListFixedPricesByProductBulkUpdateUserErrorCode
    from schema.scalars.string import String



class PriceListFixedPricesByProductBulkUpdateUserError(ObjectType):
    class Fields:
        code = EnumField("code", "PriceListFixedPricesByProductBulkUpdateUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "PriceListFixedPricesByProductBulkUpdateUserErrorCode"
    field: "String"
    message: "String"

    