
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.price_list_adjustment_type import PriceListAdjustmentType
    from schema.scalars.float import Float



class PriceListAdjustment(ObjectType):
    class Fields:
        type = EnumField("type", "PriceListAdjustmentType")
        value = ScalarField("value", "Float")

    type: "PriceListAdjustmentType"
    value: "Float"

    