
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.price_list_price import PriceListPrice
    from schema.scalars.string import String



class PriceListPriceEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "PriceListPrice")

    cursor: "String"
    node: "PriceListPrice"

    