
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.price_list_user_error import PriceListUserError
    from schema.scalars.id import ID



class PriceListDeletePayload(ObjectType):
    class Fields:
        deleted_id = ScalarField("deletedId", "ID")
        user_errors = ObjectField("userErrors", "PriceListUserError")

    deleted_id: "ID"
    user_errors: "PriceListUserError"

    