
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, InterfaceField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.currency_code import CurrencyCode
    from schema.interfaces.catalog import Catalog
    from schema.objects.price_list_parent import PriceListParent
    from schema.objects.price_list_price_connection import PriceListPriceConnection
    from schema.objects.quantity_rule_connection import QuantityRuleConnection
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.string import String



class PriceList(ObjectType):
    class Fields:
        catalog = InterfaceField("catalog", "Catalog")
        currency = EnumField("currency", "CurrencyCode")
        fixed_prices_count = ScalarField("fixedPricesCount", "Int")
        id = ScalarField("id", "ID")
        name = ScalarField("name", "String")
        parent = ObjectField("parent", "PriceListParent")
        prices = ObjectField("prices", "PriceListPriceConnection")
        quantity_rules = ObjectField("quantityRules", "QuantityRuleConnection")

    catalog: "Catalog"
    currency: "CurrencyCode"
    fixed_prices_count: "Int"
    id: "ID"
    name: "String"
    parent: "PriceListParent"
    prices: "PriceListPriceConnection"
    quantity_rules: "QuantityRuleConnection"

    