
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.float import Float



class PricingPercentageValue(ObjectType):
    class Fields:
        percentage = ScalarField("percentage", "Float")

    percentage: "Float"

    