
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.price_list import PriceList
    from schema.scalars.string import String



class PriceListEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "PriceList")

    cursor: "String"
    node: "PriceList"

    