
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.price_list_price_user_error_code import PriceListPriceUserErrorCode
    from schema.scalars.string import String



class PriceListPriceUserError(ObjectType):
    class Fields:
        code = EnumField("code", "PriceListPriceUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "PriceListPriceUserErrorCode"
    field: "String"
    message: "String"

    