
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.price_rule_discount_code import PriceRuleDiscountCode
    from schema.objects.price_rule_discount_code_edge import PriceRuleDiscountCodeEdge



class PriceRuleDiscountCodeConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "PriceRuleDiscountCodeEdge")
        nodes = ObjectField("nodes", "PriceRuleDiscountCode")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "PriceRuleDiscountCodeEdge"
    nodes: "PriceRuleDiscountCode"
    page_info: "PageInfo"

    