
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.private_metafield import PrivateMetafield
    from schema.objects.user_error import UserError



class PrivateMetafieldUpsertPayload(ObjectType):
    class Fields:
        private_metafield = ObjectField("privateMetafield", "PrivateMetafield")
        user_errors = ObjectField("userErrors", "UserError")

    private_metafield: "PrivateMetafield"
    user_errors: "UserError"

    