
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.product_operation_status import ProductOperationStatus
    from schema.objects.product import Product
    from schema.objects.product_set_user_error import ProductSetUserError
    from schema.scalars.id import ID



class ProductSetOperation(ObjectType):
    class Fields:
        id = ScalarField("id", "ID")
        product = ObjectField("product", "Product")
        status = EnumField("status", "ProductOperationStatus")
        user_errors = ObjectField("userErrors", "ProductSetUserError")

    id: "ID"
    product: "Product"
    status: "ProductOperationStatus"
    user_errors: "ProductSetUserError"

    