
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.int import Int
    from schema.scalars.string import String



class ProductBundleComponentQuantityOptionValue(ObjectType):
    class Fields:
        name = ScalarField("name", "String")
        quantity = ScalarField("quantity", "Int")

    name: "String"
    quantity: "Int"

    