
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.product_variants_bulk_delete_user_error_code import ProductVariantsBulkDeleteUserErrorCode
    from schema.scalars.string import String



class ProductVariantsBulkDeleteUserError(ObjectType):
    class Fields:
        code = EnumField("code", "ProductVariantsBulkDeleteUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "ProductVariantsBulkDeleteUserErrorCode"
    field: "String"
    message: "String"

    