
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.money_v2 import MoneyV2
    from schema.objects.quantity_price_break_connection import QuantityPriceBreakConnection
    from schema.objects.quantity_rule import QuantityRule



class ProductVariantContextualPricing(ObjectType):
    class Fields:
        compare_at_price = ObjectField("compareAtPrice", "MoneyV2")
        price = ObjectField("price", "MoneyV2")
        quantity_price_breaks = ObjectField("quantityPriceBreaks", "QuantityPriceBreakConnection")
        quantity_rule = ObjectField("quantityRule", "QuantityRule")

    compare_at_price: "MoneyV2"
    price: "MoneyV2"
    quantity_price_breaks: "QuantityPriceBreakConnection"
    quantity_rule: "QuantityRule"

    