
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.product_operation_status import ProductOperationStatus
    from schema.objects.product import Product
    from schema.objects.user_error import UserError
    from schema.scalars.id import ID



class ProductDeleteOperation(ObjectType):
    class Fields:
        deleted_product_id = ScalarField("deletedProductId", "ID")
        id = ScalarField("id", "ID")
        product = ObjectField("product", "Product")
        status = EnumField("status", "ProductOperationStatus")
        user_errors = ObjectField("userErrors", "UserError")

    deleted_product_id: "ID"
    id: "ID"
    product: "Product"
    status: "ProductOperationStatus"
    user_errors: "UserError"

    