
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.product_variant_price_pair import ProductVariantPricePair
    from schema.scalars.string import String



class ProductVariantPricePairEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "ProductVariantPricePair")

    cursor: "String"
    node: "ProductVariantPricePair"

    