
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.boolean import Boolean
    from schema.scalars.id import ID
    from schema.scalars.string import String



class ProductTaxonomyNode(ObjectType):
    class Fields:
        full_name = ScalarField("fullName", "String")
        id = ScalarField("id", "ID")
        is_leaf = ScalarField("isLeaf", "Boolean")
        is_root = ScalarField("isRoot", "Boolean")
        name = ScalarField("name", "String")

    full_name: "String"
    id: "ID"
    is_leaf: "Boolean"
    is_root: "Boolean"
    name: "String"

    