
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.product_variant_price_pair import ProductVariantPricePair
    from schema.objects.product_variant_price_pair_edge import ProductVariantPricePairEdge



class ProductVariantPricePairConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "ProductVariantPricePairEdge")
        nodes = ObjectField("nodes", "ProductVariantPricePair")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "ProductVariantPricePairEdge"
    nodes: "ProductVariantPricePair"
    page_info: "PageInfo"

    