
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.product_set_user_error_code import ProductSetUserErrorCode
    from schema.scalars.string import String



class ProductSetUserError(ObjectType):
    class Fields:
        code = EnumField("code", "ProductSetUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "ProductSetUserErrorCode"
    field: "String"
    message: "String"

    