
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.count import Count
    from schema.objects.product import Product
    from schema.objects.product_bundle_component_option_selection import ProductBundleComponentOptionSelection
    from schema.objects.product_bundle_component_quantity_option import ProductBundleComponentQuantityOption
    from schema.objects.product_variant_connection import ProductVariantConnection
    from schema.scalars.int import Int



class ProductBundleComponent(ObjectType):
    class Fields:
        component_product = ObjectField("componentProduct", "Product")
        component_variants = ObjectField("componentVariants", "ProductVariantConnection")
        component_variants_count = ObjectField("componentVariantsCount", "Count")
        option_selections = ObjectField("optionSelections", "ProductBundleComponentOptionSelection")
        quantity = ScalarField("quantity", "Int")
        quantity_option = ObjectField("quantityOption", "ProductBundleComponentQuantityOption")

    component_product: "Product"
    component_variants: "ProductVariantConnection"
    component_variants_count: "Count"
    option_selections: "ProductBundleComponentOptionSelection"
    quantity: "Int"
    quantity_option: "ProductBundleComponentQuantityOption"

    