
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.product_bundle_component_option_selection_status import ProductBundleComponentOptionSelectionStatus
    from schema.scalars.string import String



class ProductBundleComponentOptionSelectionValue(ObjectType):
    class Fields:
        selection_status = EnumField("selectionStatus", "ProductBundleComponentOptionSelectionStatus")
        value = ScalarField("value", "String")

    selection_status: "ProductBundleComponentOptionSelectionStatus"
    value: "String"

    