
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.product import Product
    from schema.objects.selling_plan_group_user_error import SellingPlanGroupUserError



class ProductJoinSellingPlanGroupsPayload(ObjectType):
    class Fields:
        product = ObjectField("product", "Product")
        user_errors = ObjectField("userErrors", "SellingPlanGroupUserError")

    product: "Product"
    user_errors: "SellingPlanGroupUserError"

    