
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.product_feed_create_user_error_code import ProductFeedCreateUserErrorCode
    from schema.scalars.string import String



class ProductFeedCreateUserError(ObjectType):
    class Fields:
        code = EnumField("code", "ProductFeedCreateUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "ProductFeedCreateUserErrorCode"
    field: "String"
    message: "String"

    