
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.product_change_status_user_error_code import ProductChangeStatusUserErrorCode
    from schema.scalars.string import String



class ProductChangeStatusUserError(ObjectType):
    class Fields:
        code = EnumField("code", "ProductChangeStatusUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "ProductChangeStatusUserErrorCode"
    field: "String"
    message: "String"

    