
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.product import Product
    from schema.objects.product_change_status_user_error import ProductChangeStatusUserError



class ProductChangeStatusPayload(ObjectType):
    class Fields:
        product = ObjectField("product", "Product")
        user_errors = ObjectField("userErrors", "ProductChangeStatusUserError")

    product: "Product"
    user_errors: "ProductChangeStatusUserError"

    