
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.product_variants_bulk_update_user_error_code import ProductVariantsBulkUpdateUserErrorCode
    from schema.scalars.string import String



class ProductVariantsBulkUpdateUserError(ObjectType):
    class Fields:
        code = EnumField("code", "ProductVariantsBulkUpdateUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "ProductVariantsBulkUpdateUserErrorCode"
    field: "String"
    message: "String"

    