
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.media_user_error import MediaUserError
    from schema.objects.product import Product
    from schema.objects.product_variant import ProductVariant



class ProductVariantDetachMediaPayload(ObjectType):
    class Fields:
        product = ObjectField("product", "Product")
        product_variants = ObjectField("productVariants", "ProductVariant")
        user_errors = ObjectField("userErrors", "MediaUserError")

    product: "Product"
    product_variants: "ProductVariant"
    user_errors: "MediaUserError"

    