
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.product import Product
    from schema.objects.product_options_reorder_user_error import ProductOptionsReorderUserError



class ProductOptionsReorderPayload(ObjectType):
    class Fields:
        product = ObjectField("product", "Product")
        user_errors = ObjectField("userErrors", "ProductOptionsReorderUserError")

    product: "Product"
    user_errors: "ProductOptionsReorderUserError"

    