
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.product import Product
    from schema.objects.product_publication import ProductPublication
    from schema.objects.shop import Shop
    from schema.objects.user_error import UserError



class ProductPublishPayload(ObjectType):
    class Fields:
        product = ObjectField("product", "Product")
        product_publications = ObjectField("productPublications", "ProductPublication")
        shop = ObjectField("shop", "Shop")
        user_errors = ObjectField("userErrors", "UserError")

    product: "Product"
    product_publications: "ProductPublication"
    shop: "Shop"
    user_errors: "UserError"

    