
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.product_bundle_component import ProductBundleComponent
    from schema.objects.product_bundle_component_edge import ProductBundleComponentEdge



class ProductBundleComponentConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "ProductBundleComponentEdge")
        nodes = ObjectField("nodes", "ProductBundleComponent")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "ProductBundleComponentEdge"
    nodes: "ProductBundleComponent"
    page_info: "PageInfo"

    