
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.product_feed_delete_user_error_code import ProductFeedDeleteUserErrorCode
    from schema.scalars.string import String



class ProductFeedDeleteUserError(ObjectType):
    class Fields:
        code = EnumField("code", "ProductFeedDeleteUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "ProductFeedDeleteUserErrorCode"
    field: "String"
    message: "String"

    