
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.product_options_delete_user_error_code import ProductOptionsDeleteUserErrorCode
    from schema.scalars.string import String



class ProductOptionsDeleteUserError(ObjectType):
    class Fields:
        code = EnumField("code", "ProductOptionsDeleteUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "ProductOptionsDeleteUserErrorCode"
    field: "String"
    message: "String"

    