
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.boolean import Boolean
    from schema.scalars.id import ID



class ProductDuplicateJob(ObjectType):
    class Fields:
        done = ScalarField("done", "Boolean")
        id = ScalarField("id", "ID")

    done: "Boolean"
    id: "ID"

    