
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.product_variant import ProductVariant
    from schema.objects.product_variant_relationship_bulk_update_user_error import ProductVariantRelationshipBulkUpdateUserError



class ProductVariantRelationshipBulkUpdatePayload(ObjectType):
    class Fields:
        parent_product_variants = ObjectField("parentProductVariants", "ProductVariant")
        user_errors = ObjectField("userErrors", "ProductVariantRelationshipBulkUpdateUserError")

    parent_product_variants: "ProductVariant"
    user_errors: "ProductVariantRelationshipBulkUpdateUserError"

    