
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.product import Product
    from schema.objects.product_option_update_user_error import ProductOptionUpdateUserError



class ProductOptionUpdatePayload(ObjectType):
    class Fields:
        product = ObjectField("product", "Product")
        user_errors = ObjectField("userErrors", "ProductOptionUpdateUserError")

    product: "Product"
    user_errors: "ProductOptionUpdateUserError"

    