
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.product_variant import ProductVariant
    from schema.objects.selling_plan_group_user_error import SellingPlanGroupUserError



class ProductVariantJoinSellingPlanGroupsPayload(ObjectType):
    class Fields:
        product_variant = ObjectField("productVariant", "ProductVariant")
        user_errors = ObjectField("userErrors", "SellingPlanGroupUserError")

    product_variant: "ProductVariant"
    user_errors: "SellingPlanGroupUserError"

    