
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.pub_sub_webhook_subscription_create_user_error import PubSubWebhookSubscriptionCreateUserError
    from schema.objects.webhook_subscription import WebhookSubscription



class PubSubWebhookSubscriptionCreatePayload(ObjectType):
    class Fields:
        user_errors = ObjectField("userErrors", "PubSubWebhookSubscriptionCreateUserError")
        webhook_subscription = ObjectField("webhookSubscription", "WebhookSubscription")

    user_errors: "PubSubWebhookSubscriptionCreateUserError"
    webhook_subscription: "WebhookSubscription"

    