
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, InterfaceField, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.interfaces.publishable import Publishable
    from schema.objects.shop import Shop
    from schema.objects.user_error import UserError



class PublishableUnpublishToCurrentChannelPayload(ObjectType):
    class Fields:
        publishable = InterfaceField("publishable", "Publishable")
        shop = ObjectField("shop", "Shop")
        user_errors = ObjectField("userErrors", "UserError")

    publishable: "Publishable"
    shop: "Shop"
    user_errors: "UserError"

    