
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.publication import Publication
    from schema.objects.publication_user_error import PublicationUserError



class PublicationUpdatePayload(ObjectType):
    class Fields:
        publication = ObjectField("publication", "Publication")
        user_errors = ObjectField("userErrors", "PublicationUserError")

    publication: "Publication"
    user_errors: "PublicationUserError"

    