
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.company import Company
    from schema.objects.company_contact import CompanyContact
    from schema.objects.company_location import CompanyLocation



class PurchasingCompany(ObjectType):
    class Fields:
        company = ObjectField("company", "Company")
        contact = ObjectField("contact", "CompanyContact")
        location = ObjectField("location", "CompanyLocation")

    company: "Company"
    contact: "CompanyContact"
    location: "CompanyLocation"

    