
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.quantity_rule_user_error_code import QuantityRuleUserErrorCode
    from schema.scalars.string import String



class QuantityRuleUserError(ObjectType):
    class Fields:
        code = EnumField("code", "QuantityRuleUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "QuantityRuleUserErrorCode"
    field: "String"
    message: "String"

    