
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.quantity_rule import QuantityRule
    from schema.scalars.string import String



class QuantityRuleEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "QuantityRule")

    cursor: "String"
    node: "QuantityRule"

    