
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.quantity_rule import QuantityRule
    from schema.objects.quantity_rule_user_error import QuantityRuleUserError



class QuantityRulesAddPayload(ObjectType):
    class Fields:
        quantity_rules = ObjectField("quantityRules", "QuantityRule")
        user_errors = ObjectField("userErrors", "QuantityRuleUserError")

    quantity_rules: "QuantityRule"
    user_errors: "QuantityRuleUserError"

    