
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.quantity_price_break import QuantityPriceBreak
    from schema.objects.quantity_price_break_edge import QuantityPriceBreakEdge



class QuantityPriceBreakConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "QuantityPriceBreakEdge")
        nodes = ObjectField("nodes", "QuantityPriceBreak")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "QuantityPriceBreakEdge"
    nodes: "QuantityPriceBreak"
    page_info: "PageInfo"

    