
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.quantity_rule import QuantityRule
    from schema.objects.quantity_rule_edge import QuantityRuleEdge



class QuantityRuleConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "QuantityRuleEdge")
        nodes = ObjectField("nodes", "QuantityRule")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "QuantityRuleEdge"
    nodes: "QuantityRule"
    page_info: "PageInfo"

    