
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.quantity_price_break import QuantityPriceBreak
    from schema.scalars.string import String



class QuantityPriceBreakEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "QuantityPriceBreak")

    cursor: "String"
    node: "QuantityPriceBreak"

    