
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.refund_shipping_line import RefundShippingLine
    from schema.objects.refund_shipping_line_edge import RefundShippingLineEdge



class RefundShippingLineConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "RefundShippingLineEdge")
        nodes = ObjectField("nodes", "RefundShippingLine")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "RefundShippingLineEdge"
    nodes: "RefundShippingLine"
    page_info: "PageInfo"

    