
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.duty import Duty
    from schema.objects.money_bag import MoneyBag



class RefundDuty(ObjectType):
    class Fields:
        amount_set = ObjectField("amountSet", "MoneyBag")
        original_duty = ObjectField("originalDuty", "Duty")

    amount_set: "MoneyBag"
    original_duty: "Duty"

    