
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.resource_alert_icon import ResourceAlertIcon
    from schema.enums.resource_alert_severity import ResourceAlertSeverity
    from schema.objects.resource_alert_action import ResourceAlertAction
    from schema.scalars.html import HTML
    from schema.scalars.string import String



class ResourceAlert(ObjectType):
    class Fields:
        actions = ObjectField("actions", "ResourceAlertAction")
        content = ScalarField("content", "HTML")
        dismissible_handle = ScalarField("dismissibleHandle", "String")
        icon = EnumField("icon", "ResourceAlertIcon")
        severity = EnumField("severity", "ResourceAlertSeverity")
        title = ScalarField("title", "String")

    actions: "ResourceAlertAction"
    content: "HTML"
    dismissible_handle: "String"
    icon: "ResourceAlertIcon"
    severity: "ResourceAlertSeverity"
    title: "String"

    