
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.boolean import Boolean
    from schema.scalars.string import String
    from schema.scalars.url import URL



class ResourceAlertAction(ObjectType):
    class Fields:
        primary = ScalarField("primary", "Boolean")
        show = ScalarField("show", "String")
        title = ScalarField("title", "String")
        url = ScalarField("url", "URL")

    primary: "Boolean"
    show: "String"
    title: "String"
    url: "URL"

    