
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.resource_publication_v2 import ResourcePublicationV2
    from schema.objects.resource_publication_v2_edge import ResourcePublicationV2Edge



class ResourcePublicationV2Connection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "ResourcePublicationV2Edge")
        nodes = ObjectField("nodes", "ResourcePublicationV2")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "ResourcePublicationV2Edge"
    nodes: "ResourcePublicationV2"
    page_info: "PageInfo"

    