
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.app_feedback import AppFeedback
    from schema.scalars.string import String



class ResourceFeedback(ObjectType):
    class Fields:
        app_feedback = ObjectField("appFeedback", "AppFeedback")
        details = ObjectField("details", "AppFeedback")
        summary = ScalarField("summary", "String")

    app_feedback: "AppFeedback"
    details: "AppFeedback"
    summary: "String"

    