
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.return_decline_reason import ReturnDeclineReason
    from schema.scalars.string import String



class ReturnDecline(ObjectType):
    class Fields:
        note = ScalarField("note", "String")
        reason = EnumField("reason", "ReturnDeclineReason")

    note: "String"
    reason: "ReturnDeclineReason"

    