
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.returnable_fulfillment_line_item import ReturnableFulfillmentLineItem
    from schema.objects.returnable_fulfillment_line_item_edge import ReturnableFulfillmentLineItemEdge



class ReturnableFulfillmentLineItemConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "ReturnableFulfillmentLineItemEdge")
        nodes = ObjectField("nodes", "ReturnableFulfillmentLineItem")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "ReturnableFulfillmentLineItemEdge"
    nodes: "ReturnableFulfillmentLineItem"
    page_info: "PageInfo"

    