
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.order_action_type import OrderActionType
    from schema.objects.app import App
    from schema.objects.return import Return
    from schema.objects.sale_connection import SaleConnection
    from schema.objects.staff_member import StaffMember
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID



class ReturnAgreement(ObjectType):
    class Fields:
        app = ObjectField("app", "App")
        happened_at = ScalarField("happenedAt", "DateTime")
        id = ScalarField("id", "ID")
        reason = EnumField("reason", "OrderActionType")
        return = ObjectField("return", "Return")
        sales = ObjectField("sales", "SaleConnection")
        user = ObjectField("user", "StaffMember")

    app: "App"
    happened_at: "DateTime"
    id: "ID"
    reason: "OrderActionType"
    return: "Return"
    sales: "SaleConnection"
    user: "StaffMember"

    