
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.returnable_fulfillment import ReturnableFulfillment
    from schema.objects.returnable_fulfillment_edge import ReturnableFulfillmentEdge



class ReturnableFulfillmentConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "ReturnableFulfillmentEdge")
        nodes = ObjectField("nodes", "ReturnableFulfillment")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "ReturnableFulfillmentEdge"
    nodes: "ReturnableFulfillment"
    page_info: "PageInfo"

    