
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.fulfillment import Fulfillment
    from schema.objects.returnable_fulfillment_line_item_connection import ReturnableFulfillmentLineItemConnection
    from schema.scalars.id import ID



class ReturnableFulfillment(ObjectType):
    class Fields:
        fulfillment = ObjectField("fulfillment", "Fulfillment")
        id = ScalarField("id", "ID")
        returnable_fulfillment_line_items = ObjectField("returnableFulfillmentLineItems", "ReturnableFulfillmentLineItemConnection")

    fulfillment: "Fulfillment"
    id: "ID"
    returnable_fulfillment_line_items: "ReturnableFulfillmentLineItemConnection"

    