
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.reverse_fulfillment_order import ReverseFulfillmentOrder
    from schema.scalars.string import String



class ReverseFulfillmentOrderEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "ReverseFulfillmentOrder")

    cursor: "String"
    node: "ReverseFulfillmentOrder"

    