
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.reverse_delivery import ReverseDelivery
    from schema.scalars.string import String



class ReverseDeliveryEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "ReverseDelivery")

    cursor: "String"
    node: "ReverseDelivery"

    