
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.date_time import DateTime
    from schema.scalars.url import URL



class ReverseDeliveryLabelV2(ObjectType):
    class Fields:
        created_at = ScalarField("createdAt", "DateTime")
        public_file_url = ScalarField("publicFileUrl", "URL")
        updated_at = ScalarField("updatedAt", "DateTime")

    created_at: "DateTime"
    public_file_url: "URL"
    updated_at: "DateTime"

    