
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.return_user_error import ReturnUserError
    from schema.objects.reverse_fulfillment_order_line_item import ReverseFulfillmentOrderLineItem



class ReverseFulfillmentOrderDisposePayload(ObjectType):
    class Fields:
        reverse_fulfillment_order_line_items = ObjectField("reverseFulfillmentOrderLineItems", "ReverseFulfillmentOrderLineItem")
        user_errors = ObjectField("userErrors", "ReturnUserError")

    reverse_fulfillment_order_line_items: "ReverseFulfillmentOrderLineItem"
    user_errors: "ReturnUserError"

    