
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.reverse_delivery_line_item_connection import ReverseDeliveryLineItemConnection
    from schema.objects.reverse_fulfillment_order import ReverseFulfillmentOrder
    from schema.scalars.id import ID
    from schema.unions.reverse_delivery_deliverable import ReverseDeliveryDeliverable



class ReverseDelivery(ObjectType):
    class Fields:
        deliverable = UnionField("deliverable", "ReverseDeliveryDeliverable")
        id = ScalarField("id", "ID")
        reverse_delivery_line_items = ObjectField("reverseDeliveryLineItems", "ReverseDeliveryLineItemConnection")
        reverse_fulfillment_order = ObjectField("reverseFulfillmentOrder", "ReverseFulfillmentOrder")

    deliverable: "ReverseDeliveryDeliverable"
    id: "ID"
    reverse_delivery_line_items: "ReverseDeliveryLineItemConnection"
    reverse_fulfillment_order: "ReverseFulfillmentOrder"

    