
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.reverse_fulfillment_order_disposition_type import ReverseFulfillmentOrderDispositionType
    from schema.objects.location import Location
    from schema.scalars.id import ID
    from schema.scalars.int import Int



class ReverseFulfillmentOrderDisposition(ObjectType):
    class Fields:
        id = ScalarField("id", "ID")
        location = ObjectField("location", "Location")
        quantity = ScalarField("quantity", "Int")
        type = EnumField("type", "ReverseFulfillmentOrderDispositionType")

    id: "ID"
    location: "Location"
    quantity: "Int"
    type: "ReverseFulfillmentOrderDispositionType"

    