
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.reverse_delivery_line_item import ReverseDeliveryLineItem
    from schema.objects.reverse_delivery_line_item_edge import ReverseDeliveryLineItemEdge



class ReverseDeliveryLineItemConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "ReverseDeliveryLineItemEdge")
        nodes = ObjectField("nodes", "ReverseDeliveryLineItem")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "ReverseDeliveryLineItemEdge"
    nodes: "ReverseDeliveryLineItem"
    page_info: "PageInfo"

    