
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.boolean import Boolean
    from schema.scalars.int import Int



class RowCount(ObjectType):
    class Fields:
        count = ScalarField("count", "Int")
        exceeds_max = ScalarField("exceedsMax", "Boolean")

    count: "Int"
    exceeds_max: "Boolean"

    