
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, InterfaceField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.interfaces.sales_agreement import SalesAgreement
    from schema.scalars.string import String



class SalesAgreementEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = InterfaceField("node", "SalesAgreement")

    cursor: "String"
    node: "SalesAgreement"

    