
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.search_result_type import SearchResultType
    from schema.objects.search_filter import SearchFilter
    from schema.scalars.id import ID
    from schema.scalars.string import String
    from schema.scalars.unsigned_int64 import UnsignedInt64



class SavedSearch(ObjectType):
    class Fields:
        filters = ObjectField("filters", "SearchFilter")
        id = ScalarField("id", "ID")
        legacy_resource_id = ScalarField("legacyResourceId", "UnsignedInt64")
        name = ScalarField("name", "String")
        query = ScalarField("query", "String")
        resource_type = EnumField("resourceType", "SearchResultType")
        search_terms = ScalarField("searchTerms", "String")

    filters: "SearchFilter"
    id: "ID"
    legacy_resource_id: "UnsignedInt64"
    name: "String"
    query: "String"
    resource_type: "SearchResultType"
    search_terms: "String"

    