
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.saved_search import SavedSearch
    from schema.objects.user_error import UserError



class SavedSearchUpdatePayload(ObjectType):
    class Fields:
        saved_search = ObjectField("savedSearch", "SavedSearch")
        user_errors = ObjectField("userErrors", "UserError")

    saved_search: "SavedSearch"
    user_errors: "UserError"

    