
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.script_tag import ScriptTag
    from schema.scalars.string import String



class ScriptTagEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "ScriptTag")

    cursor: "String"
    node: "ScriptTag"

    