
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.filter_option import FilterOption



class SearchFilterOptions(ObjectType):
    class Fields:
        product_availability = ObjectField("productAvailability", "FilterOption")

    product_availability: "FilterOption"

    