
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.float import Float



class SegmentAttributeStatistics(ObjectType):
    class Fields:
        average = ScalarField("average", "Float")
        sum = ScalarField("sum", "Float")

    average: "Float"
    sum: "Float"

    