
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.segment_migration import SegmentMigration
    from schema.scalars.string import String



class SegmentMigrationEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "SegmentMigration")

    cursor: "String"
    node: "SegmentMigration"

    