
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.segment import Segment
    from schema.objects.user_error import UserError



class SegmentCreatePayload(ObjectType):
    class Fields:
        segment = ObjectField("segment", "Segment")
        user_errors = ObjectField("userErrors", "UserError")

    segment: "Segment"
    user_errors: "UserError"

    