
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.segment_migration import SegmentMigration
    from schema.objects.segment_migration_edge import SegmentMigrationEdge



class SegmentMigrationConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "SegmentMigrationEdge")
        nodes = ObjectField("nodes", "SegmentMigration")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "SegmentMigrationEdge"
    nodes: "SegmentMigration"
    page_info: "PageInfo"

    