
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, InterfaceField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.interfaces.segment_filter import SegmentFilter
    from schema.scalars.string import String



class SegmentFilterEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = InterfaceField("node", "SegmentFilter")

    cursor: "String"
    node: "SegmentFilter"

    