
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, InterfaceField, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.interfaces.segment_filter import SegmentFilter
    from schema.objects.page_info import PageInfo
    from schema.objects.segment_filter_edge import SegmentFilterEdge



class SegmentFilterConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "SegmentFilterEdge")
        nodes = InterfaceField("nodes", "SegmentFilter")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "SegmentFilterEdge"
    nodes: "SegmentFilter"
    page_info: "PageInfo"

    