
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.boolean import Boolean
    from schema.scalars.string import String



class SegmentDateFilter(ObjectType):
    class Fields:
        localized_name = ScalarField("localizedName", "String")
        multi_value = ScalarField("multiValue", "Boolean")
        query_name = ScalarField("queryName", "String")

    localized_name: "String"
    multi_value: "Boolean"
    query_name: "String"

    