
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.segment import Segment
    from schema.objects.segment_edge import SegmentEdge



class SegmentConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "SegmentEdge")
        nodes = ObjectField("nodes", "Segment")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "SegmentEdge"
    nodes: "Segment"
    page_info: "PageInfo"

    