
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.segment_value import SegmentValue
    from schema.objects.segment_value_edge import SegmentValueEdge



class SegmentValueConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "SegmentValueEdge")
        nodes = ObjectField("nodes", "SegmentValue")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "SegmentValueEdge"
    nodes: "SegmentValue"
    page_info: "PageInfo"

    