
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.selling_plan_remaining_balance_charge_trigger import SellingPlanRemainingBalanceChargeTrigger
    from schema.objects.selling_plan_checkout_charge import SellingPlanCheckoutCharge
    from schema.scalars.date_time import DateTime
    from schema.scalars.string import String



class SellingPlanFixedBillingPolicy(ObjectType):
    class Fields:
        checkout_charge = ObjectField("checkoutCharge", "SellingPlanCheckoutCharge")
        remaining_balance_charge_exact_time = ScalarField("remainingBalanceChargeExactTime", "DateTime")
        remaining_balance_charge_time_after_checkout = ScalarField("remainingBalanceChargeTimeAfterCheckout", "String")
        remaining_balance_charge_trigger = EnumField("remainingBalanceChargeTrigger", "SellingPlanRemainingBalanceChargeTrigger")

    checkout_charge: "SellingPlanCheckoutCharge"
    remaining_balance_charge_exact_time: "DateTime"
    remaining_balance_charge_time_after_checkout: "String"
    remaining_balance_charge_trigger: "SellingPlanRemainingBalanceChargeTrigger"

    