
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.selling_plan_pricing_policy_adjustment_type import SellingPlanPricingPolicyAdjustmentType
    from schema.scalars.date_time import DateTime
    from schema.scalars.int import Int
    from schema.unions.selling_plan_pricing_policy_adjustment_value import SellingPlanPricingPolicyAdjustmentValue



class SellingPlanRecurringPricingPolicy(ObjectType):
    class Fields:
        adjustment_type = EnumField("adjustmentType", "SellingPlanPricingPolicyAdjustmentType")
        adjustment_value = UnionField("adjustmentValue", "SellingPlanPricingPolicyAdjustmentValue")
        after_cycle = ScalarField("afterCycle", "Int")
        created_at = ScalarField("createdAt", "DateTime")

    adjustment_type: "SellingPlanPricingPolicyAdjustmentType"
    adjustment_value: "SellingPlanPricingPolicyAdjustmentValue"
    after_cycle: "Int"
    created_at: "DateTime"

    