
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.selling_plan_group import SellingPlanGroup
    from schema.scalars.string import String



class SellingPlanGroupEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "SellingPlanGroup")

    cursor: "String"
    node: "SellingPlanGroup"

    