
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.selling_plan_anchor_type import SellingPlanAnchorType
    from schema.scalars.int import Int



class SellingPlanAnchor(ObjectType):
    class Fields:
        cutoff_day = ScalarField("cutoffDay", "Int")
        day = ScalarField("day", "Int")
        month = ScalarField("month", "Int")
        type = EnumField("type", "SellingPlanAnchorType")

    cutoff_day: "Int"
    day: "Int"
    month: "Int"
    type: "SellingPlanAnchorType"

    