
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.selling_plan_group_user_error import SellingPlanGroupUserError
    from schema.scalars.id import ID



class SellingPlanGroupDeletePayload(ObjectType):
    class Fields:
        deleted_selling_plan_group_id = ScalarField("deletedSellingPlanGroupId", "ID")
        user_errors = ObjectField("userErrors", "SellingPlanGroupUserError")

    deleted_selling_plan_group_id: "ID"
    user_errors: "SellingPlanGroupUserError"

    