
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.count import Count
    from schema.objects.product_connection import ProductConnection
    from schema.objects.product_variant_connection import ProductVariantConnection
    from schema.objects.selling_plan_connection import SellingPlanConnection
    from schema.objects.translation import Translation
    from schema.scalars.boolean import Boolean
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.string import String



class SellingPlanGroup(ObjectType):
    class Fields:
        app_id = ScalarField("appId", "String")
        applies_to_product = ScalarField("appliesToProduct", "Boolean")
        applies_to_product_variant = ScalarField("appliesToProductVariant", "Boolean")
        applies_to_product_variants = ScalarField("appliesToProductVariants", "Boolean")
        created_at = ScalarField("createdAt", "DateTime")
        description = ScalarField("description", "String")
        id = ScalarField("id", "ID")
        merchant_code = ScalarField("merchantCode", "String")
        name = ScalarField("name", "String")
        options = ScalarField("options", "String")
        position = ScalarField("position", "Int")
        product_variants = ObjectField("productVariants", "ProductVariantConnection")
        product_variants_count = ObjectField("productVariantsCount", "Count")
        products = ObjectField("products", "ProductConnection")
        products_count = ObjectField("productsCount", "Count")
        selling_plans = ObjectField("sellingPlans", "SellingPlanConnection")
        summary = ScalarField("summary", "String")
        translations = ObjectField("translations", "Translation")

    app_id: "String"
    applies_to_product: "Boolean"
    applies_to_product_variant: "Boolean"
    applies_to_product_variants: "Boolean"
    created_at: "DateTime"
    description: "String"
    id: "ID"
    merchant_code: "String"
    name: "String"
    options: "String"
    position: "Int"
    product_variants: "ProductVariantConnection"
    product_variants_count: "Count"
    products: "ProductConnection"
    products_count: "Count"
    selling_plans: "SellingPlanConnection"
    summary: "String"
    translations: "Translation"

    