
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.selling_plan_group import SellingPlanGroup
    from schema.objects.selling_plan_group_edge import SellingPlanGroupEdge



class SellingPlanGroupConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "SellingPlanGroupEdge")
        nodes = ObjectField("nodes", "SellingPlanGroup")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "SellingPlanGroupEdge"
    nodes: "SellingPlanGroup"
    page_info: "PageInfo"

    