
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.selling_plan_group import SellingPlanGroup
    from schema.objects.selling_plan_group_user_error import SellingPlanGroupUserError



class SellingPlanGroupCreatePayload(ObjectType):
    class Fields:
        selling_plan_group = ObjectField("sellingPlanGroup", "SellingPlanGroup")
        user_errors = ObjectField("userErrors", "SellingPlanGroupUserError")

    selling_plan_group: "SellingPlanGroup"
    user_errors: "SellingPlanGroupUserError"

    