
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.selling_plan import SellingPlan
    from schema.objects.selling_plan_edge import SellingPlanEdge



class SellingPlanConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "SellingPlanEdge")
        nodes = ObjectField("nodes", "SellingPlan")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "SellingPlanEdge"
    nodes: "SellingPlan"
    page_info: "PageInfo"

    