
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.selling_plan_reserve import SellingPlanReserve



class SellingPlanInventoryPolicy(ObjectType):
    class Fields:
        reserve = EnumField("reserve", "SellingPlanReserve")

    reserve: "SellingPlanReserve"

    