
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.selling_plan_interval import SellingPlanInterval
    from schema.enums.selling_plan_recurring_delivery_policy_intent import SellingPlanRecurringDeliveryPolicyIntent
    from schema.enums.selling_plan_recurring_delivery_policy_pre_anchor_behavior import SellingPlanRecurringDeliveryPolicyPreAnchorBehavior
    from schema.objects.selling_plan_anchor import SellingPlanAnchor
    from schema.scalars.date_time import DateTime
    from schema.scalars.int import Int



class SellingPlanRecurringDeliveryPolicy(ObjectType):
    class Fields:
        anchors = ObjectField("anchors", "SellingPlanAnchor")
        created_at = ScalarField("createdAt", "DateTime")
        cutoff = ScalarField("cutoff", "Int")
        intent = EnumField("intent", "SellingPlanRecurringDeliveryPolicyIntent")
        interval = EnumField("interval", "SellingPlanInterval")
        interval_count = ScalarField("intervalCount", "Int")
        pre_anchor_behavior = EnumField("preAnchorBehavior", "SellingPlanRecurringDeliveryPolicyPreAnchorBehavior")

    anchors: "SellingPlanAnchor"
    created_at: "DateTime"
    cutoff: "Int"
    intent: "SellingPlanRecurringDeliveryPolicyIntent"
    interval: "SellingPlanInterval"
    interval_count: "Int"
    pre_anchor_behavior: "SellingPlanRecurringDeliveryPolicyPreAnchorBehavior"

    