
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.selling_plan import SellingPlan
    from schema.scalars.string import String



class SellingPlanEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "SellingPlan")

    cursor: "String"
    node: "SellingPlan"

    