
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.string import String



class SEO(ObjectType):
    class Fields:
        description = ScalarField("description", "String")
        title = ScalarField("title", "String")

    description: "String"
    title: "String"

    