
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.shop_policy_error_code import ShopPolicyErrorCode
    from schema.scalars.string import String



class ShopPolicyUserError(ObjectType):
    class Fields:
        code = EnumField("code", "ShopPolicyErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "ShopPolicyErrorCode"
    field: "String"
    message: "String"

    