
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.market_web_presence import MarketWebPresence
    from schema.scalars.boolean import Boolean
    from schema.scalars.string import String



class ShopLocale(ObjectType):
    class Fields:
        locale = ScalarField("locale", "String")
        market_web_presences = ObjectField("marketWebPresences", "MarketWebPresence")
        name = ScalarField("name", "String")
        primary = ScalarField("primary", "Boolean")
        published = ScalarField("published", "Boolean")

    locale: "String"
    market_web_presences: "MarketWebPresence"
    name: "String"
    primary: "Boolean"
    published: "Boolean"

    