
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.app_feedback import AppFeedback
    from schema.objects.shop_resource_feedback_create_user_error import ShopResourceFeedbackCreateUserError



class ShopResourceFeedbackCreatePayload(ObjectType):
    class Fields:
        feedback = ObjectField("feedback", "AppFeedback")
        user_errors = ObjectField("userErrors", "ShopResourceFeedbackCreateUserError")

    feedback: "AppFeedback"
    user_errors: "ShopResourceFeedbackCreateUserError"

    