
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.shopify_payments_source_type import ShopifyPaymentsSourceType
    from schema.enums.shopify_payments_transaction_type import ShopifyPaymentsTransactionType
    from schema.objects.money_v2 import MoneyV2
    from schema.objects.shopify_payments_adjustment_order import ShopifyPaymentsAdjustmentOrder
    from schema.objects.shopify_payments_associated_order import ShopifyPaymentsAssociatedOrder
    from schema.objects.shopify_payments_balance_transaction_associated_payout import ShopifyPaymentsBalanceTransactionAssociatedPayout
    from schema.scalars.big_int import BigInt
    from schema.scalars.boolean import Boolean
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.string import String



class ShopifyPaymentsBalanceTransaction(ObjectType):
    class Fields:
        adjustment_reason = ScalarField("adjustmentReason", "String")
        adjustments_orders = ObjectField("adjustmentsOrders", "ShopifyPaymentsAdjustmentOrder")
        amount = ObjectField("amount", "MoneyV2")
        associated_order = ObjectField("associatedOrder", "ShopifyPaymentsAssociatedOrder")
        associated_payout = ObjectField("associatedPayout", "ShopifyPaymentsBalanceTransactionAssociatedPayout")
        fee = ObjectField("fee", "MoneyV2")
        id = ScalarField("id", "ID")
        net = ObjectField("net", "MoneyV2")
        source_id = ScalarField("sourceId", "BigInt")
        source_order_transaction_id = ScalarField("sourceOrderTransactionId", "BigInt")
        source_type = EnumField("sourceType", "ShopifyPaymentsSourceType")
        test = ScalarField("test", "Boolean")
        transaction_date = ScalarField("transactionDate", "DateTime")
        type = EnumField("type", "ShopifyPaymentsTransactionType")

    adjustment_reason: "String"
    adjustments_orders: "ShopifyPaymentsAdjustmentOrder"
    amount: "MoneyV2"
    associated_order: "ShopifyPaymentsAssociatedOrder"
    associated_payout: "ShopifyPaymentsBalanceTransactionAssociatedPayout"
    fee: "MoneyV2"
    id: "ID"
    net: "MoneyV2"
    source_id: "BigInt"
    source_order_transaction_id: "BigInt"
    source_type: "ShopifyPaymentsSourceType"
    test: "Boolean"
    transaction_date: "DateTime"
    type: "ShopifyPaymentsTransactionType"

    