
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.day_of_the_week import DayOfTheWeek
    from schema.enums.shopify_payments_payout_interval import ShopifyPaymentsPayoutInterval
    from schema.scalars.int import Int



class ShopifyPaymentsPayoutSchedule(ObjectType):
    class Fields:
        interval = EnumField("interval", "ShopifyPaymentsPayoutInterval")
        monthly_anchor = ScalarField("monthlyAnchor", "Int")
        weekly_anchor = EnumField("weeklyAnchor", "DayOfTheWeek")

    interval: "ShopifyPaymentsPayoutInterval"
    monthly_anchor: "Int"
    weekly_anchor: "DayOfTheWeek"

    