
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.shopify_protect_status import ShopifyProtectStatus
    from schema.objects.shopify_protect_order_eligibility import ShopifyProtectOrderEligibility



class ShopifyProtectOrderSummary(ObjectType):
    class Fields:
        eligibility = ObjectField("eligibility", "ShopifyProtectOrderEligibility")
        status = EnumField("status", "ShopifyProtectStatus")

    eligibility: "ShopifyProtectOrderEligibility"
    status: "ShopifyProtectStatus"

    