
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.shop_policy_type import ShopPolicyType
    from schema.objects.translation import Translation
    from schema.scalars.date import Date
    from schema.scalars.html import HTML
    from schema.scalars.id import ID
    from schema.scalars.string import String
    from schema.scalars.url import URL



class ShopPolicy(ObjectType):
    class Fields:
        body = ScalarField("body", "HTML")
        created_at = ScalarField("createdAt", "Date")
        id = ScalarField("id", "ID")
        title = ScalarField("title", "String")
        translations = ObjectField("translations", "Translation")
        type = EnumField("type", "ShopPolicyType")
        updated_at = ScalarField("updatedAt", "Date")
        url = ScalarField("url", "URL")

    body: "HTML"
    created_at: "Date"
    id: "ID"
    title: "String"
    translations: "Translation"
    type: "ShopPolicyType"
    updated_at: "Date"
    url: "URL"

    