
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.string import String



class ShopifyPaymentsJpChargeStatementDescriptor(ObjectType):
    class Fields:
        default = ScalarField("default", "String")
        kana = ScalarField("kana", "String")
        kanji = ScalarField("kanji", "String")
        prefix = ScalarField("prefix", "String")

    default: "String"
    kana: "String"
    kanji: "String"
    prefix: "String"

    