
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.shopify_payments_dispute import ShopifyPaymentsDispute
    from schema.objects.shopify_payments_dispute_edge import ShopifyPaymentsDisputeEdge



class ShopifyPaymentsDisputeConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "ShopifyPaymentsDisputeEdge")
        nodes = ObjectField("nodes", "ShopifyPaymentsDispute")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "ShopifyPaymentsDisputeEdge"
    nodes: "ShopifyPaymentsDispute"
    page_info: "PageInfo"

    