
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.boolean import Boolean
    from schema.scalars.string import String



class ShopPlan(ObjectType):
    class Fields:
        display_name = ScalarField("displayName", "String")
        partner_development = ScalarField("partnerDevelopment", "Boolean")
        shopify_plus = ScalarField("shopifyPlus", "Boolean")

    display_name: "String"
    partner_development: "Boolean"
    shopify_plus: "Boolean"

    