
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.shop_policy import ShopPolicy
    from schema.objects.shop_policy_user_error import ShopPolicyUserError



class ShopPolicyUpdatePayload(ObjectType):
    class Fields:
        shop_policy = ObjectField("shopPolicy", "ShopPolicy")
        user_errors = ObjectField("userErrors", "ShopPolicyUserError")

    shop_policy: "ShopPolicy"
    user_errors: "ShopPolicyUserError"

    