
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.shopify_payments_verification_status import ShopifyPaymentsVerificationStatus
    from schema.objects.shopify_payments_verification_subject import ShopifyPaymentsVerificationSubject
    from schema.scalars.id import ID



class ShopifyPaymentsVerification(ObjectType):
    class Fields:
        id = ScalarField("id", "ID")
        status = EnumField("status", "ShopifyPaymentsVerificationStatus")
        subject = ObjectField("subject", "ShopifyPaymentsVerificationSubject")

    id: "ID"
    status: "ShopifyPaymentsVerificationStatus"
    subject: "ShopifyPaymentsVerificationSubject"

    