
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.date import Date
    from schema.scalars.id import ID
    from schema.scalars.string import String



class ShopifyPaymentsDisputeFulfillment(ObjectType):
    class Fields:
        id = ScalarField("id", "ID")
        shipping_carrier = ScalarField("shippingCarrier", "String")
        shipping_date = ScalarField("shippingDate", "Date")
        shipping_tracking_number = ScalarField("shippingTrackingNumber", "String")

    id: "ID"
    shipping_carrier: "String"
    shipping_date: "Date"
    shipping_tracking_number: "String"

    