
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.boolean import Boolean
    from schema.scalars.int import Int



class ShopResourceLimits(ObjectType):
    class Fields:
        location_limit = ScalarField("locationLimit", "Int")
        max_product_options = ScalarField("maxProductOptions", "Int")
        max_product_variants = ScalarField("maxProductVariants", "Int")
        redirect_limit_reached = ScalarField("redirectLimitReached", "Boolean")

    location_limit: "Int"
    max_product_options: "Int"
    max_product_variants: "Int"
    redirect_limit_reached: "Boolean"

    