
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.shop_alert_action import ShopAlertAction
    from schema.scalars.string import String



class ShopAlert(ObjectType):
    class Fields:
        action = ObjectField("action", "ShopAlertAction")
        description = ScalarField("description", "String")

    action: "ShopAlertAction"
    description: "String"

    