
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, InterfaceField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.currency_code import CurrencyCode
    from schema.interfaces.shopify_payments_charge_statement_descriptor import ShopifyPaymentsChargeStatementDescriptor
    from schema.objects.money_v2 import MoneyV2
    from schema.objects.shopify_payments_balance_transaction_connection import ShopifyPaymentsBalanceTransactionConnection
    from schema.objects.shopify_payments_bank_account_connection import ShopifyPaymentsBankAccountConnection
    from schema.objects.shopify_payments_dispute_connection import ShopifyPaymentsDisputeConnection
    from schema.objects.shopify_payments_payout_connection import ShopifyPaymentsPayoutConnection
    from schema.objects.shopify_payments_payout_schedule import ShopifyPaymentsPayoutSchedule
    from schema.scalars.boolean import Boolean
    from schema.scalars.id import ID
    from schema.scalars.string import String



class ShopifyPaymentsAccount(ObjectType):
    class Fields:
        activated = ScalarField("activated", "Boolean")
        balance = ObjectField("balance", "MoneyV2")
        balance_transactions = ObjectField("balanceTransactions", "ShopifyPaymentsBalanceTransactionConnection")
        bank_accounts = ObjectField("bankAccounts", "ShopifyPaymentsBankAccountConnection")
        charge_statement_descriptor = ScalarField("chargeStatementDescriptor", "String")
        charge_statement_descriptors = InterfaceField("chargeStatementDescriptors", "ShopifyPaymentsChargeStatementDescriptor")
        country = ScalarField("country", "String")
        default_currency = EnumField("defaultCurrency", "CurrencyCode")
        disputes = ObjectField("disputes", "ShopifyPaymentsDisputeConnection")
        id = ScalarField("id", "ID")
        onboardable = ScalarField("onboardable", "Boolean")
        payout_schedule = ObjectField("payoutSchedule", "ShopifyPaymentsPayoutSchedule")
        payout_statement_descriptor = ScalarField("payoutStatementDescriptor", "String")
        payouts = ObjectField("payouts", "ShopifyPaymentsPayoutConnection")

    activated: "Boolean"
    balance: "MoneyV2"
    balance_transactions: "ShopifyPaymentsBalanceTransactionConnection"
    bank_accounts: "ShopifyPaymentsBankAccountConnection"
    charge_statement_descriptor: "String"
    charge_statement_descriptors: "ShopifyPaymentsChargeStatementDescriptor"
    country: "String"
    default_currency: "CurrencyCode"
    disputes: "ShopifyPaymentsDisputeConnection"
    id: "ID"
    onboardable: "Boolean"
    payout_schedule: "ShopifyPaymentsPayoutSchedule"
    payout_statement_descriptor: "String"
    payouts: "ShopifyPaymentsPayoutConnection"

    