
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.shopify_payments_balance_transaction import ShopifyPaymentsBalanceTransaction
    from schema.scalars.string import String



class ShopifyPaymentsBalanceTransactionEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "ShopifyPaymentsBalanceTransaction")

    cursor: "String"
    node: "ShopifyPaymentsBalanceTransaction"

    