
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.staff_member_permission import StaffMemberPermission
    from schema.scalars.date_time import DateTime
    from schema.scalars.url import URL



class StaffMemberPrivateData(ObjectType):
    class Fields:
        account_settings_url = ScalarField("accountSettingsUrl", "URL")
        created_at = ScalarField("createdAt", "DateTime")
        permissions = EnumField("permissions", "StaffMemberPermission")

    account_settings_url: "URL"
    created_at: "DateTime"
    permissions: "StaffMemberPermission"

    