
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.mutations_staged_upload_target_generate_upload_parameter import MutationsStagedUploadTargetGenerateUploadParameter
    from schema.objects.user_error import UserError
    from schema.scalars.string import String



class StagedUploadTargetGeneratePayload(ObjectType):
    class Fields:
        parameters = ObjectField("parameters", "MutationsStagedUploadTargetGenerateUploadParameter")
        url = ScalarField("url", "String")
        user_errors = ObjectField("userErrors", "UserError")

    parameters: "MutationsStagedUploadTargetGenerateUploadParameter"
    url: "String"
    user_errors: "UserError"

    