
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.staged_upload_parameter import StagedUploadParameter
    from schema.scalars.url import URL



class StagedMediaUploadTarget(ObjectType):
    class Fields:
        parameters = ObjectField("parameters", "StagedUploadParameter")
        resource_url = ScalarField("resourceUrl", "URL")
        url = ScalarField("url", "URL")

    parameters: "StagedUploadParameter"
    resource_url: "URL"
    url: "URL"

    