
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.standard_metafield_definition_enable_user_error_code import StandardMetafieldDefinitionEnableUserErrorCode
    from schema.scalars.string import String



class StandardMetafieldDefinitionEnableUserError(ObjectType):
    class Fields:
        code = EnumField("code", "StandardMetafieldDefinitionEnableUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "StandardMetafieldDefinitionEnableUserErrorCode"
    field: "String"
    message: "String"

    