
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.standard_metafield_definition_template import StandardMetafieldDefinitionTemplate
    from schema.objects.standard_metafield_definition_template_edge import StandardMetafieldDefinitionTemplateEdge



class StandardMetafieldDefinitionTemplateConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "StandardMetafieldDefinitionTemplateEdge")
        nodes = ObjectField("nodes", "StandardMetafieldDefinitionTemplate")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "StandardMetafieldDefinitionTemplateEdge"
    nodes: "StandardMetafieldDefinitionTemplate"
    page_info: "PageInfo"

    