
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.access_scope import AccessScope
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.string import String



class StorefrontAccessToken(ObjectType):
    class Fields:
        access_scopes = ObjectField("accessScopes", "AccessScope")
        access_token = ScalarField("accessToken", "String")
        created_at = ScalarField("createdAt", "DateTime")
        id = ScalarField("id", "ID")
        title = ScalarField("title", "String")
        updated_at = ScalarField("updatedAt", "DateTime")

    access_scopes: "AccessScope"
    access_token: "String"
    created_at: "DateTime"
    id: "ID"
    title: "String"
    updated_at: "DateTime"

    