
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.store_credit_account import StoreCreditAccount
    from schema.objects.store_credit_account_edge import StoreCreditAccountEdge



class StoreCreditAccountConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "StoreCreditAccountEdge")
        nodes = ObjectField("nodes", "StoreCreditAccount")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "StoreCreditAccountEdge"
    nodes: "StoreCreditAccount"
    page_info: "PageInfo"

    