
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.money_v2 import MoneyV2
    from schema.objects.store_credit_account import StoreCreditAccount
    from schema.objects.store_credit_account_credit_transaction import StoreCreditAccountCreditTransaction
    from schema.scalars.date_time import DateTime



class StoreCreditAccountExpirationTransaction(ObjectType):
    class Fields:
        account = ObjectField("account", "StoreCreditAccount")
        amount = ObjectField("amount", "MoneyV2")
        balance_after_transaction = ObjectField("balanceAfterTransaction", "MoneyV2")
        created_at = ScalarField("createdAt", "DateTime")
        credit_transaction = ObjectField("creditTransaction", "StoreCreditAccountCreditTransaction")

    account: "StoreCreditAccount"
    amount: "MoneyV2"
    balance_after_transaction: "MoneyV2"
    created_at: "DateTime"
    credit_transaction: "StoreCreditAccountCreditTransaction"

    