
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.string_edge import StringEdge



class StringConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "StringEdge")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "StringEdge"
    page_info: "PageInfo"

    