
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.subscription_manual_discount import SubscriptionManualDiscount
    from schema.scalars.string import String



class SubscriptionManualDiscountEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "SubscriptionManualDiscount")

    cursor: "String"
    node: "SubscriptionManualDiscount"

    