
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.location import Location
    from schema.scalars.string import String



class SubscriptionDeliveryMethodPickupOption(ObjectType):
    class Fields:
        code = ScalarField("code", "String")
        description = ScalarField("description", "String")
        location = ObjectField("location", "Location")
        presentment_title = ScalarField("presentmentTitle", "String")
        title = ScalarField("title", "String")

    code: "String"
    description: "String"
    location: "Location"
    presentment_title: "String"
    title: "String"

    