
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.subscription_line import SubscriptionLine
    from schema.scalars.string import String



class SubscriptionLineEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "SubscriptionLine")

    cursor: "String"
    node: "SubscriptionLine"

    