
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.subscription_billing_cycle_error_code import SubscriptionBillingCycleErrorCode
    from schema.scalars.string import String



class SubscriptionBillingCycleUserError(ObjectType):
    class Fields:
        code = EnumField("code", "SubscriptionBillingCycleErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "SubscriptionBillingCycleErrorCode"
    field: "String"
    message: "String"

    