
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.money_v2 import MoneyV2
    from schema.scalars.boolean import Boolean
    from schema.scalars.string import String



class SubscriptionLocalDeliveryOption(ObjectType):
    class Fields:
        code = ScalarField("code", "String")
        description = ScalarField("description", "String")
        phone_required = ScalarField("phoneRequired", "Boolean")
        presentment_title = ScalarField("presentmentTitle", "String")
        price = ObjectField("price", "MoneyV2")
        title = ScalarField("title", "String")

    code: "String"
    description: "String"
    phone_required: "Boolean"
    presentment_title: "String"
    price: "MoneyV2"
    title: "String"

    