
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.selling_plan_interval import SellingPlanInterval
    from schema.objects.selling_plan_anchor import SellingPlanAnchor
    from schema.scalars.int import Int



class SubscriptionDeliveryPolicy(ObjectType):
    class Fields:
        anchors = ObjectField("anchors", "SellingPlanAnchor")
        interval = EnumField("interval", "SellingPlanInterval")
        interval_count = ScalarField("intervalCount", "Int")

    anchors: "SellingPlanAnchor"
    interval: "SellingPlanInterval"
    interval_count: "Int"

    