
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.subscription_delivery_method_shipping_option import SubscriptionDeliveryMethodShippingOption
    from schema.objects.subscription_mailing_address import SubscriptionMailingAddress



class SubscriptionDeliveryMethodShipping(ObjectType):
    class Fields:
        address = ObjectField("address", "SubscriptionMailingAddress")
        shipping_option = ObjectField("shippingOption", "SubscriptionDeliveryMethodShippingOption")

    address: "SubscriptionMailingAddress"
    shipping_option: "SubscriptionDeliveryMethodShippingOption"

    