
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.subscription_delivery_method_pickup_option import SubscriptionDeliveryMethodPickupOption



class SubscriptionDeliveryMethodPickup(ObjectType):
    class Fields:
        pickup_option = ObjectField("pickupOption", "SubscriptionDeliveryMethodPickupOption")

    pickup_option: "SubscriptionDeliveryMethodPickupOption"

    