
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.int import Int



class SubscriptionDiscountPercentageValue(ObjectType):
    class Fields:
        percentage = ScalarField("percentage", "Int")

    percentage: "Int"

    