
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.discount_target_type import DiscountTargetType
    from schema.enums.discount_type import DiscountType
    from schema.enums.subscription_discount_rejection_reason import SubscriptionDiscountRejectionReason
    from schema.objects.subscription_discount_entitled_lines import SubscriptionDiscountEntitledLines
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.string import String
    from schema.unions.subscription_discount_value import SubscriptionDiscountValue



class SubscriptionManualDiscount(ObjectType):
    class Fields:
        entitled_lines = ObjectField("entitledLines", "SubscriptionDiscountEntitledLines")
        id = ScalarField("id", "ID")
        recurring_cycle_limit = ScalarField("recurringCycleLimit", "Int")
        rejection_reason = EnumField("rejectionReason", "SubscriptionDiscountRejectionReason")
        target_type = EnumField("targetType", "DiscountTargetType")
        title = ScalarField("title", "String")
        type = EnumField("type", "DiscountType")
        usage_count = ScalarField("usageCount", "Int")
        value = UnionField("value", "SubscriptionDiscountValue")

    entitled_lines: "SubscriptionDiscountEntitledLines"
    id: "ID"
    recurring_cycle_limit: "Int"
    rejection_reason: "SubscriptionDiscountRejectionReason"
    target_type: "DiscountTargetType"
    title: "String"
    type: "DiscountType"
    usage_count: "Int"
    value: "SubscriptionDiscountValue"

    