
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.subscription_discount_rejection_reason import SubscriptionDiscountRejectionReason
    from schema.scalars.id import ID
    from schema.scalars.string import String



class SubscriptionAppliedCodeDiscount(ObjectType):
    class Fields:
        id = ScalarField("id", "ID")
        redeem_code = ScalarField("redeemCode", "String")
        rejection_reason = EnumField("rejectionReason", "SubscriptionDiscountRejectionReason")

    id: "ID"
    redeem_code: "String"
    rejection_reason: "SubscriptionDiscountRejectionReason"

    