
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.subscription_contract import SubscriptionContract
    from schema.objects.subscription_draft_user_error import SubscriptionDraftUserError



class SubscriptionContractAtomicCreatePayload(ObjectType):
    class Fields:
        contract = ObjectField("contract", "SubscriptionContract")
        user_errors = ObjectField("userErrors", "SubscriptionDraftUserError")

    contract: "SubscriptionContract"
    user_errors: "SubscriptionDraftUserError"

    