
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.attribute import Attribute
    from schema.objects.image import Image
    from schema.objects.money_v2 import MoneyV2
    from schema.objects.subscription_discount_allocation import SubscriptionDiscountAllocation
    from schema.objects.subscription_pricing_policy import SubscriptionPricingPolicy
    from schema.scalars.boolean import Boolean
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.string import String



class SubscriptionLine(ObjectType):
    class Fields:
        current_price = ObjectField("currentPrice", "MoneyV2")
        custom_attributes = ObjectField("customAttributes", "Attribute")
        discount_allocations = ObjectField("discountAllocations", "SubscriptionDiscountAllocation")
        id = ScalarField("id", "ID")
        line_discounted_price = ObjectField("lineDiscountedPrice", "MoneyV2")
        pricing_policy = ObjectField("pricingPolicy", "SubscriptionPricingPolicy")
        product_id = ScalarField("productId", "ID")
        quantity = ScalarField("quantity", "Int")
        requires_shipping = ScalarField("requiresShipping", "Boolean")
        selling_plan_id = ScalarField("sellingPlanId", "ID")
        selling_plan_name = ScalarField("sellingPlanName", "String")
        sku = ScalarField("sku", "String")
        taxable = ScalarField("taxable", "Boolean")
        title = ScalarField("title", "String")
        variant_id = ScalarField("variantId", "ID")
        variant_image = ObjectField("variantImage", "Image")
        variant_title = ScalarField("variantTitle", "String")

    current_price: "MoneyV2"
    custom_attributes: "Attribute"
    discount_allocations: "SubscriptionDiscountAllocation"
    id: "ID"
    line_discounted_price: "MoneyV2"
    pricing_policy: "SubscriptionPricingPolicy"
    product_id: "ID"
    quantity: "Int"
    requires_shipping: "Boolean"
    selling_plan_id: "ID"
    selling_plan_name: "String"
    sku: "String"
    taxable: "Boolean"
    title: "String"
    variant_id: "ID"
    variant_image: "Image"
    variant_title: "String"

    