
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.subscription_contract_error_code import SubscriptionContractErrorCode
    from schema.scalars.string import String



class SubscriptionContractUserError(ObjectType):
    class Fields:
        code = EnumField("code", "SubscriptionContractErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "SubscriptionContractErrorCode"
    field: "String"
    message: "String"

    