
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.subscription_line import SubscriptionLine
    from schema.objects.subscription_line_edge import SubscriptionLineEdge



class SubscriptionLineConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "SubscriptionLineEdge")
        nodes = ObjectField("nodes", "SubscriptionLine")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "SubscriptionLineEdge"
    nodes: "SubscriptionLine"
    page_info: "PageInfo"

    