
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.subscription_contract import SubscriptionContract
    from schema.objects.subscription_draft_user_error import SubscriptionDraftUserError
    from schema.objects.subscription_line import SubscriptionLine



class SubscriptionContractProductChangePayload(ObjectType):
    class Fields:
        contract = ObjectField("contract", "SubscriptionContract")
        line_updated = ObjectField("lineUpdated", "SubscriptionLine")
        user_errors = ObjectField("userErrors", "SubscriptionDraftUserError")

    contract: "SubscriptionContract"
    line_updated: "SubscriptionLine"
    user_errors: "SubscriptionDraftUserError"

    