
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.money_v2 import MoneyV2
    from schema.unions.subscription_discount import SubscriptionDiscount



class SubscriptionDiscountAllocation(ObjectType):
    class Fields:
        amount = ObjectField("amount", "MoneyV2")
        discount = UnionField("discount", "SubscriptionDiscount")

    amount: "MoneyV2"
    discount: "SubscriptionDiscount"

    