
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.subscription_billing_attempt_error_code import SubscriptionBillingAttemptErrorCode
    from schema.objects.order import Order
    from schema.objects.order_transaction_connection import OrderTransactionConnection
    from schema.objects.subscription_contract import SubscriptionContract
    from schema.scalars.boolean import Boolean
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.string import String
    from schema.scalars.url import URL



class SubscriptionBillingAttempt(ObjectType):
    class Fields:
        completed_at = ScalarField("completedAt", "DateTime")
        created_at = ScalarField("createdAt", "DateTime")
        error_code = EnumField("errorCode", "SubscriptionBillingAttemptErrorCode")
        error_message = ScalarField("errorMessage", "String")
        id = ScalarField("id", "ID")
        idempotency_key = ScalarField("idempotencyKey", "String")
        next_action_url = ScalarField("nextActionUrl", "URL")
        order = ObjectField("order", "Order")
        origin_time = ScalarField("originTime", "DateTime")
        payment_group_id = ScalarField("paymentGroupId", "String")
        payment_session_id = ScalarField("paymentSessionId", "String")
        ready = ScalarField("ready", "Boolean")
        subscription_contract = ObjectField("subscriptionContract", "SubscriptionContract")
        transactions = ObjectField("transactions", "OrderTransactionConnection")

    completed_at: "DateTime"
    created_at: "DateTime"
    error_code: "SubscriptionBillingAttemptErrorCode"
    error_message: "String"
    id: "ID"
    idempotency_key: "String"
    next_action_url: "URL"
    order: "Order"
    origin_time: "DateTime"
    payment_group_id: "String"
    payment_session_id: "String"
    ready: "Boolean"
    subscription_contract: "SubscriptionContract"
    transactions: "OrderTransactionConnection"

    