
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ObjectField, ScalarField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.currency_code import CurrencyCode
    from schema.enums.subscription_contract_last_billing_error_type import SubscriptionContractLastBillingErrorType
    from schema.enums.subscription_contract_last_payment_status import SubscriptionContractLastPaymentStatus
    from schema.enums.subscription_contract_subscription_status import SubscriptionContractSubscriptionStatus
    from schema.objects.app import App
    from schema.objects.attribute import Attribute
    from schema.objects.count import Count
    from schema.objects.customer import Customer
    from schema.objects.customer_payment_method import CustomerPaymentMethod
    from schema.objects.money_v2 import MoneyV2
    from schema.objects.order import Order
    from schema.objects.order_connection import OrderConnection
    from schema.objects.subscription_billing_attempt_connection import SubscriptionBillingAttemptConnection
    from schema.objects.subscription_billing_policy import SubscriptionBillingPolicy
    from schema.objects.subscription_delivery_policy import SubscriptionDeliveryPolicy
    from schema.objects.subscription_line_connection import SubscriptionLineConnection
    from schema.objects.subscription_manual_discount_connection import SubscriptionManualDiscountConnection
    from schema.scalars.date_time import DateTime
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.string import String
    from schema.scalars.unsigned_int64 import UnsignedInt64
    from schema.scalars.url import URL
    from schema.unions.subscription_delivery_method import SubscriptionDeliveryMethod



class SubscriptionContract(ObjectType):
    class Fields:
        app = ObjectField("app", "App")
        app_admin_url = ScalarField("appAdminUrl", "URL")
        billing_attempts = ObjectField("billingAttempts", "SubscriptionBillingAttemptConnection")
        billing_policy = ObjectField("billingPolicy", "SubscriptionBillingPolicy")
        created_at = ScalarField("createdAt", "DateTime")
        currency_code = EnumField("currencyCode", "CurrencyCode")
        custom_attributes = ObjectField("customAttributes", "Attribute")
        customer = ObjectField("customer", "Customer")
        customer_payment_method = ObjectField("customerPaymentMethod", "CustomerPaymentMethod")
        delivery_method = UnionField("deliveryMethod", "SubscriptionDeliveryMethod")
        delivery_policy = ObjectField("deliveryPolicy", "SubscriptionDeliveryPolicy")
        delivery_price = ObjectField("deliveryPrice", "MoneyV2")
        discounts = ObjectField("discounts", "SubscriptionManualDiscountConnection")
        id = ScalarField("id", "ID")
        last_billing_attempt_error_type = EnumField("lastBillingAttemptErrorType", "SubscriptionContractLastBillingErrorType")
        last_payment_status = EnumField("lastPaymentStatus", "SubscriptionContractLastPaymentStatus")
        line_count = ScalarField("lineCount", "Int")
        lines = ObjectField("lines", "SubscriptionLineConnection")
        lines_count = ObjectField("linesCount", "Count")
        next_billing_date = ScalarField("nextBillingDate", "DateTime")
        note = ScalarField("note", "String")
        orders = ObjectField("orders", "OrderConnection")
        origin_order = ObjectField("originOrder", "Order")
        revision_id = ScalarField("revisionId", "UnsignedInt64")
        status = EnumField("status", "SubscriptionContractSubscriptionStatus")
        updated_at = ScalarField("updatedAt", "DateTime")

    app: "App"
    app_admin_url: "URL"
    billing_attempts: "SubscriptionBillingAttemptConnection"
    billing_policy: "SubscriptionBillingPolicy"
    created_at: "DateTime"
    currency_code: "CurrencyCode"
    custom_attributes: "Attribute"
    customer: "Customer"
    customer_payment_method: "CustomerPaymentMethod"
    delivery_method: "SubscriptionDeliveryMethod"
    delivery_policy: "SubscriptionDeliveryPolicy"
    delivery_price: "MoneyV2"
    discounts: "SubscriptionManualDiscountConnection"
    id: "ID"
    last_billing_attempt_error_type: "SubscriptionContractLastBillingErrorType"
    last_payment_status: "SubscriptionContractLastPaymentStatus"
    line_count: "Int"
    lines: "SubscriptionLineConnection"
    lines_count: "Count"
    next_billing_date: "DateTime"
    note: "String"
    orders: "OrderConnection"
    origin_order: "Order"
    revision_id: "UnsignedInt64"
    status: "SubscriptionContractSubscriptionStatus"
    updated_at: "DateTime"

    