
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.subscription_draft import SubscriptionDraft
    from schema.objects.subscription_draft_user_error import SubscriptionDraftUserError
    from schema.objects.subscription_manual_discount import SubscriptionManualDiscount



class SubscriptionDraftFreeShippingDiscountAddPayload(ObjectType):
    class Fields:
        discount_added = ObjectField("discountAdded", "SubscriptionManualDiscount")
        draft = ObjectField("draft", "SubscriptionDraft")
        user_errors = ObjectField("userErrors", "SubscriptionDraftUserError")

    discount_added: "SubscriptionManualDiscount"
    draft: "SubscriptionDraft"
    user_errors: "SubscriptionDraftUserError"

    