
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.subscription_contract import SubscriptionContract
    from schema.objects.subscription_contract_user_error import SubscriptionContractUserError



class SubscriptionContractSetNextBillingDatePayload(ObjectType):
    class Fields:
        contract = ObjectField("contract", "SubscriptionContract")
        user_errors = ObjectField("userErrors", "SubscriptionContractUserError")

    contract: "SubscriptionContract"
    user_errors: "SubscriptionContractUserError"

    