
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.subscription_contract import SubscriptionContract
    from schema.objects.subscription_contract_edge import SubscriptionContractEdge



class SubscriptionContractConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "SubscriptionContractEdge")
        nodes = ObjectField("nodes", "SubscriptionContract")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "SubscriptionContractEdge"
    nodes: "SubscriptionContract"
    page_info: "PageInfo"

    