
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.id import ID
    from schema.scalars.string import String



class TaxonomyValue(ObjectType):
    class Fields:
        id = ScalarField("id", "ID")
        name = ScalarField("name", "String")

    id: "ID"
    name: "String"

    