
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.taxonomy_category import TaxonomyCategory
    from schema.objects.taxonomy_category_edge import TaxonomyCategoryEdge



class TaxonomyCategoryConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "TaxonomyCategoryEdge")
        nodes = ObjectField("nodes", "TaxonomyCategory")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "TaxonomyCategoryEdge"
    nodes: "TaxonomyCategory"
    page_info: "PageInfo"

    