
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, UnionField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.taxonomy_category_attribute_edge import TaxonomyCategoryAttributeEdge
    from schema.unions.taxonomy_category_attribute import TaxonomyCategoryAttribute



class TaxonomyCategoryAttributeConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "TaxonomyCategoryAttributeEdge")
        nodes = UnionField("nodes", "TaxonomyCategoryAttribute")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "TaxonomyCategoryAttributeEdge"
    nodes: "TaxonomyCategoryAttribute"
    page_info: "PageInfo"

    