
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.taxonomy_value_connection import TaxonomyValueConnection
    from schema.scalars.id import ID
    from schema.scalars.string import String



class TaxonomyChoiceListAttribute(ObjectType):
    class Fields:
        id = ScalarField("id", "ID")
        name = ScalarField("name", "String")
        values = ObjectField("values", "TaxonomyValueConnection")

    id: "ID"
    name: "String"
    values: "TaxonomyValueConnection"

    