
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.taxonomy_category_connection import TaxonomyCategoryConnection



class Taxonomy(ObjectType):
    class Fields:
        categories = ObjectField("categories", "TaxonomyCategoryConnection")

    categories: "TaxonomyCategoryConnection"

    