
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.id import ID



class TaxonomyAttribute(ObjectType):
    class Fields:
        id = ScalarField("id", "ID")

    id: "ID"

    