
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.taxonomy_category import TaxonomyCategory
    from schema.scalars.string import String



class TaxonomyCategoryEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "TaxonomyCategory")

    cursor: "String"
    node: "TaxonomyCategory"

    