
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.attribute import Attribute
    from schema.scalars.id import ID
    from schema.scalars.string import String



class TaxonomyMeasurementAttribute(ObjectType):
    class Fields:
        id = ScalarField("id", "ID")
        name = ScalarField("name", "String")
        options = ObjectField("options", "Attribute")

    id: "ID"
    name: "String"
    options: "Attribute"

    