
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.taxonomy_category_attribute_connection import TaxonomyCategoryAttributeConnection
    from schema.scalars.boolean import Boolean
    from schema.scalars.id import ID
    from schema.scalars.int import Int
    from schema.scalars.string import String



class TaxonomyCategory(ObjectType):
    class Fields:
        ancestor_ids = ScalarField("ancestorIds", "ID")
        attributes = ObjectField("attributes", "TaxonomyCategoryAttributeConnection")
        children_ids = ScalarField("childrenIds", "ID")
        full_name = ScalarField("fullName", "String")
        id = ScalarField("id", "ID")
        is_archived = ScalarField("isArchived", "Boolean")
        is_leaf = ScalarField("isLeaf", "Boolean")
        is_root = ScalarField("isRoot", "Boolean")
        level = ScalarField("level", "Int")
        name = ScalarField("name", "String")
        parent_id = ScalarField("parentId", "ID")

    ancestor_ids: "ID"
    attributes: "TaxonomyCategoryAttributeConnection"
    children_ids: "ID"
    full_name: "String"
    id: "ID"
    is_archived: "Boolean"
    is_leaf: "Boolean"
    is_root: "Boolean"
    level: "Int"
    name: "String"
    parent_id: "ID"

    