
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.taxonomy_value import TaxonomyValue
    from schema.objects.taxonomy_value_edge import TaxonomyValueEdge



class TaxonomyValueConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "TaxonomyValueEdge")
        nodes = ObjectField("nodes", "TaxonomyValue")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "TaxonomyValueEdge"
    nodes: "TaxonomyValue"
    page_info: "PageInfo"

    