
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.tender_transaction import TenderTransaction
    from schema.objects.tender_transaction_edge import TenderTransactionEdge



class TenderTransactionConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "TenderTransactionEdge")
        nodes = ObjectField("nodes", "TenderTransaction")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "TenderTransactionEdge"
    nodes: "TenderTransaction"
    page_info: "PageInfo"

    