
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.string import String



class TenderTransactionCreditCardDetails(ObjectType):
    class Fields:
        credit_card_company = ScalarField("creditCardCompany", "String")
        credit_card_number = ScalarField("creditCardNumber", "String")

    credit_card_company: "String"
    credit_card_number: "String"

    