
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.job import Job
    from schema.objects.online_store_theme_file_operation_result import OnlineStoreThemeFileOperationResult
    from schema.objects.online_store_theme_files_user_errors import OnlineStoreThemeFilesUserErrors



class ThemeFilesUpsertPayload(ObjectType):
    class Fields:
        job = ObjectField("job", "Job")
        upserted_theme_files = ObjectField("upsertedThemeFiles", "OnlineStoreThemeFileOperationResult")
        user_errors = ObjectField("userErrors", "OnlineStoreThemeFilesUserErrors")

    job: "Job"
    upserted_theme_files: "OnlineStoreThemeFileOperationResult"
    user_errors: "OnlineStoreThemeFilesUserErrors"

    