
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.theme_delete_user_error_code import ThemeDeleteUserErrorCode
    from schema.scalars.string import String



class ThemeDeleteUserError(ObjectType):
    class Fields:
        code = EnumField("code", "ThemeDeleteUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "ThemeDeleteUserErrorCode"
    field: "String"
    message: "String"

    