
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.theme_delete_user_error import ThemeDeleteUserError
    from schema.scalars.id import ID



class ThemeDeletePayload(ObjectType):
    class Fields:
        deleted_theme_id = ScalarField("deletedThemeId", "ID")
        user_errors = ObjectField("userErrors", "ThemeDeleteUserError")

    deleted_theme_id: "ID"
    user_errors: "ThemeDeleteUserError"

    