
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.translatable_resource import TranslatableResource
    from schema.objects.translatable_resource_edge import TranslatableResourceEdge



class TranslatableResourceConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "TranslatableResourceEdge")
        nodes = ObjectField("nodes", "TranslatableResource")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "TranslatableResourceEdge"
    nodes: "TranslatableResource"
    page_info: "PageInfo"

    