
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.transaction_void_user_error_code import TransactionVoidUserErrorCode
    from schema.scalars.string import String



class TransactionVoidUserError(ObjectType):
    class Fields:
        code = EnumField("code", "TransactionVoidUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "TransactionVoidUserErrorCode"
    field: "String"
    message: "String"

    