
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.translatable_resource import TranslatableResource
    from schema.scalars.string import String



class TranslatableResourceEdge(ObjectType):
    class Fields:
        cursor = ScalarField("cursor", "String")
        node = ObjectField("node", "TranslatableResource")

    cursor: "String"
    node: "TranslatableResource"

    