
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.money_v2 import MoneyV2
    from schema.scalars.decimal import Decimal
    from schema.scalars.id import ID
    from schema.scalars.string import String



class TransactionFee(ObjectType):
    class Fields:
        amount = ObjectField("amount", "MoneyV2")
        flat_fee = ObjectField("flatFee", "MoneyV2")
        flat_fee_name = ScalarField("flatFeeName", "String")
        id = ScalarField("id", "ID")
        rate = ScalarField("rate", "Decimal")
        rate_name = ScalarField("rateName", "String")
        tax_amount = ObjectField("taxAmount", "MoneyV2")
        type = ScalarField("type", "String")

    amount: "MoneyV2"
    flat_fee: "MoneyV2"
    flat_fee_name: "String"
    id: "ID"
    rate: "Decimal"
    rate_name: "String"
    tax_amount: "MoneyV2"
    type: "String"

    