
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.translation import Translation
    from schema.objects.translation_user_error import TranslationUserError



class TranslationsRegisterPayload(ObjectType):
    class Fields:
        translations = ObjectField("translations", "Translation")
        user_errors = ObjectField("userErrors", "TranslationUserError")

    translations: "Translation"
    user_errors: "TranslationUserError"

    