
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.url_redirect_bulk_delete_by_ids_user_error_code import UrlRedirectBulkDeleteByIdsUserErrorCode
    from schema.scalars.string import String



class UrlRedirectBulkDeleteByIdsUserError(ObjectType):
    class Fields:
        code = EnumField("code", "UrlRedirectBulkDeleteByIdsUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "UrlRedirectBulkDeleteByIdsUserErrorCode"
    field: "String"
    message: "String"

    