
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.job import Job
    from schema.objects.url_redirect_bulk_delete_by_ids_user_error import UrlRedirectBulkDeleteByIdsUserError



class UrlRedirectBulkDeleteByIdsPayload(ObjectType):
    class Fields:
        job = ObjectField("job", "Job")
        user_errors = ObjectField("userErrors", "UrlRedirectBulkDeleteByIdsUserError")

    job: "Job"
    user_errors: "UrlRedirectBulkDeleteByIdsUserError"

    