
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.string import String



class UrlRedirectImportPreview(ObjectType):
    class Fields:
        path = ScalarField("path", "String")
        target = ScalarField("target", "String")

    path: "String"
    target: "String"

    