
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.url_redirect_error_code import UrlRedirectErrorCode
    from schema.scalars.string import String



class UrlRedirectUserError(ObjectType):
    class Fields:
        code = EnumField("code", "UrlRedirectErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "UrlRedirectErrorCode"
    field: "String"
    message: "String"

    