
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.id import ID
    from schema.scalars.string import String



class UrlRedirect(ObjectType):
    class Fields:
        id = ScalarField("id", "ID")
        path = ScalarField("path", "String")
        target = ScalarField("target", "String")

    id: "ID"
    path: "String"
    target: "String"

    