
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.page_info import PageInfo
    from schema.objects.url_redirect import UrlRedirect
    from schema.objects.url_redirect_edge import UrlRedirectEdge



class UrlRedirectConnection(ObjectType):
    class Fields:
        edges = ObjectField("edges", "UrlRedirectEdge")
        nodes = ObjectField("nodes", "UrlRedirect")
        page_info = ObjectField("pageInfo", "PageInfo")

    edges: "UrlRedirectEdge"
    nodes: "UrlRedirect"
    page_info: "PageInfo"

    