
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.job import Job
    from schema.objects.url_redirect_import_user_error import UrlRedirectImportUserError



class UrlRedirectImportSubmitPayload(ObjectType):
    class Fields:
        job = ObjectField("job", "Job")
        user_errors = ObjectField("userErrors", "UrlRedirectImportUserError")

    job: "Job"
    user_errors: "UrlRedirectImportUserError"

    