
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, EnumField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.enums.url_redirect_bulk_delete_by_search_user_error_code import UrlRedirectBulkDeleteBySearchUserErrorCode
    from schema.scalars.string import String



class UrlRedirectBulkDeleteBySearchUserError(ObjectType):
    class Fields:
        code = EnumField("code", "UrlRedirectBulkDeleteBySearchUserErrorCode")
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    code: "UrlRedirectBulkDeleteBySearchUserErrorCode"
    field: "String"
    message: "String"

    