
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.string import String



class UserError(ObjectType):
    class Fields:
        field = ScalarField("field", "String")
        message = ScalarField("message", "String")

    field: "String"
    message: "String"

    