
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.validation import Validation
    from schema.objects.validation_user_error import ValidationUserError



class ValidationUpdatePayload(ObjectType):
    class Fields:
        user_errors = ObjectField("userErrors", "ValidationUserError")
        validation = ObjectField("validation", "Validation")

    user_errors: "ValidationUserError"
    validation: "Validation"

    