
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ObjectField, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.objects.customer_credit_card_billing_address import CustomerCreditCardBillingAddress
    from schema.scalars.boolean import Boolean
    from schema.scalars.int import Int
    from schema.scalars.string import String



class VaultCreditCard(ObjectType):
    class Fields:
        billing_address = ObjectField("billingAddress", "CustomerCreditCardBillingAddress")
        brand = ScalarField("brand", "String")
        expired = ScalarField("expired", "Boolean")
        expiry_month = ScalarField("expiryMonth", "Int")
        expiry_year = ScalarField("expiryYear", "Int")
        last_digits = ScalarField("lastDigits", "String")
        name = ScalarField("name", "String")

    billing_address: "CustomerCreditCardBillingAddress"
    brand: "String"
    expired: "Boolean"
    expiry_month: "Int"
    expiry_year: "Int"
    last_digits: "String"
    name: "String"

    