
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.boolean import Boolean
    from schema.scalars.string import String



class VaultPaypalBillingAgreement(ObjectType):
    class Fields:
        inactive = ScalarField("inactive", "Boolean")
        name = ScalarField("name", "String")
        paypal_account_email = ScalarField("paypalAccountEmail", "String")

    inactive: "Boolean"
    name: "String"
    paypal_account_email: "String"

    