
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.url import URL



class WebhookHttpEndpoint(ObjectType):
    class Fields:
        callback_url = ScalarField("callbackUrl", "URL")

    callback_url: "URL"

    