
"""
This is autogenerated code. Do not edit directly.
"""
from classes import ObjectType, ScalarField
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from schema.scalars.string import String



class WebhookPubSubEndpoint(ObjectType):
    class Fields:
        pub_sub_project = ScalarField("pubSubProject", "String")
        pub_sub_topic = ScalarField("pubSubTopic", "String")

    pub_sub_project: "String"
    pub_sub_topic: "String"

    