from generator.base import BaseGenerator

class EnumGenerator(BaseGenerator):
    kind_name = "ENUM"
    kind_dir_name = "enums"

    def _generate_class_code(self, type_data: dict):
        values_block = ""
        for enum_value in type_data["enumValues"]:
            values_block += f"    {enum_value['name']} = \"{enum_value['name']}\"\n"

        class_code = f"""\"\"\"
This is autogenerated code. Do not edit directly.
\"\"\"    
from base_types import EnumType

class {type_data["name"]}(EnumType):
{values_block}"""
        return class_code