from generator.object import ObjectGenerator
from utils import camel_to_snake

# TODO: Review generators inheriting from ObjectGenerator
class InterfaceGenerator(ObjectGenerator):
    kind_name = "INTERFACE"
    kind_dir_name = "interfaces"

    def _generate_class_code(self, type_data: dict):
        import_filed_kinds = set()
        import_argument_kinds = set()
        import_block = set()
        attributes_block = ""
        fields_block = ""
        for field_data in type_data["fields"]:
            field_name = self._normalize_identifier(field_data["name"])
            field_kind, field_type = self._get_field_kind_and_type(field_data["type"])
            field_kind = self._normalize_identifier(field_kind)
            field_type = self._normalize_identifier(field_type)
            field_arguments, argument_kinds = self._get_field_arguments(field_data["args"])
            arguments_block = "{\n            " + ",\n            ".join(field_arguments) + "\n        }" if field_arguments else ""
            import_filed_kinds.add(field_kind + "Field")
            import_argument_kinds.update(argument_kinds)
            fields_block += f"        {field_name} = {field_kind}Field(\"{field_data['name']}\", \"{field_type}\", {arguments_block})\n"
            import_block.add(f"    from schema.{field_kind.lower()}s.{camel_to_snake(field_type)} import {field_type}\n")
            attributes_block += f"    {field_name}: \"{field_type}\"\n"

        possible_types = []
        import_type_loaders = set()
        for possible_type in type_data["possibleTypes"]:
            possible_type_kind, possible_type_name = self._get_field_kind_and_type(possible_type)
            possible_type_name = self._normalize_identifier(possible_type_name)
            type_loader_name = possible_type_kind.capitalize() + "TypeLoader"
            import_type_loaders.add(type_loader_name)
            possible_types.append(f"\"{possible_type_name}\": {type_loader_name}")
        possible_types_block = ",\n        ".join(sorted(possible_types))
        class_code = f"""\"\"\"
This is autogenerated code. Do not edit directly.
\"\"\"
from base_types import InterfaceType
from type_loaders import {", ".join(sorted(import_type_loaders))}
from fields import {", ".join(sorted(import_filed_kinds))}
{f"from arguments import {', '.join(sorted(import_argument_kinds))}" if import_argument_kinds else ""}
from typing import TYPE_CHECKING

if TYPE_CHECKING:
{"".join(sorted(import_block))}


class {type_data["name"]}(InterfaceType):
    possible_type_loaders = {{
        {possible_types_block}
    }}
    class Fields:
{fields_block}
{attributes_block}"""
        return class_code
