from generator.base import BaseGenerator
from utils import camel_to_snake, snake_to_camel

class ObjectGenerator(BaseGenerator):
    kind_name = "OBJECT"
    kind_dir_name = "objects"

    def _generate_class_code(self, type_data: dict):
        import_filed_kinds = set()
        import_argument_kinds = set()
        import_types = set()
        attributes_block = ""
        fields_block = ""
        for field_data in type_data["fields"]:
            field_name = camel_to_snake(field_data["name"])
            field_name = self._normalize_identifier(field_name)
            field_kind, field_type, listed_type = self._get_field_kind_and_type(field_data["type"])
            field_kind = self._normalize_identifier(field_kind)
            snake_field_type = camel_to_snake(field_type)
            snake_field_type = self._normalize_identifier(snake_field_type)
            field_type = self._normalize_identifier(field_type)
            field_arguments, argument_kinds = self._get_field_arguments(field_data["args"])
            arguments_block = ", {\n            " + ",\n            ".join(field_arguments) + "\n        }" if field_arguments else ""
            import_filed_kinds.add(field_kind + "Field")
            import_argument_kinds.update(argument_kinds)
            fields_block += f"        {field_name} = {field_kind}Field(\"{field_data['name']}\", \"{field_type}\"{arguments_block})\n"
            import_types.add(f"    from schema.{field_kind.lower()}s.{snake_field_type} import {field_type}\n")
            attributes_block += f"    {field_name}: \"{field_type}\"\n" if not listed_type else f"    {field_name}: \"list[{field_type}]\"\n"
        class_code = f"""\"\"\"
This is autogenerated code. Do not edit directly.
\"\"\"
from base_types import ObjectType
from fields import {", ".join(sorted(import_filed_kinds))}
{f"from arguments import {', '.join(sorted(import_argument_kinds))}" if import_argument_kinds else ""}
from typing import TYPE_CHECKING

if TYPE_CHECKING:
{"".join(sorted(import_types))}


class {type_data["name"]}(ObjectType):
    class Fields:
{fields_block}
{attributes_block}"""
        return class_code

    def _get_field_arguments(self, arguments_data: list[dict]):
        arguemnt_kinds = set()
        arguments = []
        for argument_data in arguments_data:
            argument_name = self._normalize_identifier(argument_data["name"])
            argument_kind, argument_type, listed_type = self._get_field_kind_and_type(argument_data["type"])
            argument_type = self._normalize_identifier(argument_type)
            arguments.append(f"\"{camel_to_snake(argument_name)}\": {argument_kind}Argument(\"{argument_type}\")")
            arguemnt_kinds.add(argument_kind + "Argument")
        return arguments, arguemnt_kinds