
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class AbandonmentEmailStateUpdateUserErrorCode(EnumType):
    ABANDONMENT_NOT_FOUND = "ABANDONMENT_NOT_FOUND"

    