
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class AccountType(EnumType):
    REGULAR = "REGULAR"
    RESTRICTED = "RESTRICTED"
    INVITED = "INVITED"
    REQUESTED = "REQUESTED"
    COLLABORATOR = "COLLABORATOR"
    COLLABORATOR_TEAM_MEMBER = "COLLABORATOR_TEAM_MEMBER"
    SAML = "SAML"
    INVITED_STORE_OWNER = "INVITED_STORE_OWNER"

    