
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class AppRevenueAttributionType(EnumType):
    APPLICATION_PURCHASE = "APPLICATION_PURCHASE"
    APPLICATION_SUBSCRIPTION = "APPLICATION_SUBSCRIPTION"
    APPLICATION_USAGE = "APPLICATION_USAGE"
    OTHER = "OTHER"

    