
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class AppSubscriptionStatus(EnumType):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    ACTIVE = "ACTIVE"
    DECLINED = "DECLINED"
    EXPIRED = "EXPIRED"
    FROZEN = "FROZEN"
    CANCELLED = "CANCELLED"

    