
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class BalanceTransactionSortKeys(EnumType):
    PAYOUT_DATE = "PAYOUT_DATE"
    PAYOUT_STATUS = "PAYOUT_STATUS"
    PROCESSED_AT = "PROCESSED_AT"
    AMOUNT = "AMOUNT"
    FEE = "FEE"
    NET = "NET"
    TRANSACTION_TYPE = "TRANSACTION_TYPE"
    ORDER_NAME = "ORDER_NAME"
    PAYMENT_METHOD_NAME = "PAYMENT_METHOD_NAME"
    ID = "ID"
    RELEVANCE = "RELEVANCE"

    