
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class BlogUpdateUserErrorCode(EnumType):
    NOT_FOUND = "NOT_FOUND"
    INVALID = "INVALID"
    BLANK = "BLANK"
    TOO_LONG = "TOO_LONG"
    INCLUSION = "INCLUSION"

    