
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class BulkProductResourceFeedbackCreateUserErrorCode(EnumType):
    MAXIMUM_FEEDBACK_LIMIT_EXCEEDED = "MAXIMUM_FEEDBACK_LIMIT_EXCEEDED"
    OUTDATED_FEEDBACK = "OUTDATED_FEEDBACK"
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
    INVALID = "INVALID"
    BLANK = "BLANK"
    PRESENT = "PRESENT"
    LESS_THAN_OR_EQUAL_TO = "LESS_THAN_OR_EQUAL_TO"

    