
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class BulkOperationStatus(EnumType):
    CANCELED = "CANCELED"
    CANCELING = "CANCELING"
    COMPLETED = "COMPLETED"
    CREATED = "CREATED"
    EXPIRED = "EXPIRED"
    FAILED = "FAILED"
    RUNNING = "RUNNING"

    