
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class BulkMutationErrorCode(EnumType):
    OPERATION_IN_PROGRESS = "OPERATION_IN_PROGRESS"
    INVALID_MUTATION = "INVALID_MUTATION"
    INVALID_STAGED_UPLOAD_FILE = "INVALID_STAGED_UPLOAD_FILE"
    NO_SUCH_FILE = "NO_SUCH_FILE"
    INTERNAL_FILE_SERVER_ERROR = "INTERNAL_FILE_SERVER_ERROR"

    