
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class BusinessCustomerErrorCode(EnumType):
    INTERNAL_ERROR = "INTERNAL_ERROR"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    FAILED_TO_DELETE = "FAILED_TO_DELETE"
    REQUIRED = "REQUIRED"
    NO_INPUT = "NO_INPUT"
    INVALID_INPUT = "INVALID_INPUT"
    UNEXPECTED_TYPE = "UNEXPECTED_TYPE"
    TOO_LONG = "TOO_LONG"
    LIMIT_REACHED = "LIMIT_REACHED"
    INVALID = "INVALID"
    BLANK = "BLANK"
    TAKEN = "TAKEN"

    