
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CalculatedShippingLineStagedStatus(EnumType):
    NONE = "NONE"
    ADDED = "ADDED"
    REMOVED = "REMOVED"

    