
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CarrierServiceCreateUserErrorCode(EnumType):
    CARRIER_SERVICE_CREATE_FAILED = "CARRIER_SERVICE_CREATE_FAILED"

    