
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CarrierServiceDeleteUserErrorCode(EnumType):
    CARRIER_SERVICE_DELETE_FAILED = "CARRIER_SERVICE_DELETE_FAILED"

    