
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CashTrackingSessionsSortKeys(EnumType):
    OPENING_TIME_DESC = "OPENING_TIME_DESC"
    OPENING_TIME_ASC = "OPENING_TIME_ASC"
    CLOSING_TIME_DESC = "CLOSING_TIME_DESC"
    CLOSING_TIME_ASC = "CLOSING_TIME_ASC"
    TOTAL_DISCREPANCY_DESC = "TOTAL_DISCREPANCY_DESC"
    TOTAL_DISCREPANCY_ASC = "TOTAL_DISCREPANCY_ASC"
    ID = "ID"
    RELEVANCE = "RELEVANCE"

    