
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CheckoutBrandingSpacing(EnumType):
    NONE = "NONE"
    EXTRA_TIGHT = "EXTRA_TIGHT"
    TIGHT = "TIGHT"
    BASE = "BASE"
    LOOSE = "LOOSE"
    EXTRA_LOOSE = "EXTRA_LOOSE"

    