
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CheckoutBrandingTypographyKerning(EnumType):
    BASE = "BASE"
    LOOSE = "LOOSE"
    EXTRA_LOOSE = "EXTRA_LOOSE"

    