
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CheckoutBrandingBorderWidth(EnumType):
    BASE = "BASE"
    LARGE_100 = "LARGE_100"
    LARGE_200 = "LARGE_200"
    LARGE = "LARGE"

    