
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CheckoutBrandingFontLoadingStrategy(EnumType):
    AUTO = "AUTO"
    BLOCK = "BLOCK"
    SWAP = "SWAP"
    FALLBACK = "FALLBACK"
    OPTIONAL = "OPTIONAL"

    