
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CollectionAddProductsV2UserErrorCode(EnumType):
    CANT_ADD_TO_SMART_COLLECTION = "CANT_ADD_TO_SMART_COLLECTION"
    COLLECTION_DOES_NOT_EXIST = "COLLECTION_DOES_NOT_EXIST"

    