
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CommentPolicy(EnumType):
    AUTO_PUBLISHED = "AUTO_PUBLISHED"
    CLOSED = "CLOSED"
    MODERATED = "MODERATED"

    