
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CommentSortKeys(EnumType):
    CREATED_AT = "CREATED_AT"
    ID = "ID"
    RELEVANCE = "RELEVANCE"

    