
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CompanyContactSortKeys(EnumType):
    CREATED_AT = "CREATED_AT"
    UPDATED_AT = "UPDATED_AT"
    TITLE = "TITLE"
    COMPANY_ID = "COMPANY_ID"
    NAME = "NAME"
    EMAIL = "EMAIL"
    NAME_EMAIL = "NAME_EMAIL"
    ID = "ID"
    RELEVANCE = "RELEVANCE"

    