
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CompanyLocationSortKeys(EnumType):
    CREATED_AT = "CREATED_AT"
    UPDATED_AT = "UPDATED_AT"
    NAME = "NAME"
    COMPANY_ID = "COMPANY_ID"
    COMPANY_AND_LOCATION_NAME = "COMPANY_AND_LOCATION_NAME"
    ID = "ID"
    RELEVANCE = "RELEVANCE"

    