
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CropRegion(EnumType):
    CENTER = "CENTER"
    TOP = "TOP"
    BOTTOM = "BOTTOM"
    LEFT = "LEFT"
    RIGHT = "RIGHT"

    