
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CustomerPaymentMethodCreateFromDuplicationDataUserErrorCode(EnumType):
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"
    CUSTOMER_DOES_NOT_EXIST = "CUSTOMER_DOES_NOT_EXIST"
    INVALID_ENCRYPTED_DUPLICATION_DATA = "INVALID_ENCRYPTED_DUPLICATION_DATA"

    