
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CustomerPaymentMethodUserErrorCode(EnumType):
    INVALID = "INVALID"
    PRESENT = "PRESENT"
    TAKEN = "TAKEN"

    