
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CustomerPaymentMethodGetDuplicationDataUserErrorCode(EnumType):
    PAYMENT_METHOD_DOES_NOT_EXIST = "PAYMENT_METHOD_DOES_NOT_EXIST"
    INVALID_INSTRUMENT = "INVALID_INSTRUMENT"
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"
    CUSTOMER_DOES_NOT_EXIST = "CUSTOMER_DOES_NOT_EXIST"
    SAME_SHOP = "SAME_SHOP"
    INVALID_ORGANIZATION_SHOP = "INVALID_ORGANIZATION_SHOP"

    