
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CustomerEmailMarketingState(EnumType):
    NOT_SUBSCRIBED = "NOT_SUBSCRIBED"
    PENDING = "PENDING"
    SUBSCRIBED = "SUBSCRIBED"
    UNSUBSCRIBED = "UNSUBSCRIBED"
    REDACTED = "REDACTED"
    INVALID = "INVALID"

    