
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CustomerProductSubscriberStatus(EnumType):
    ACTIVE = "ACTIVE"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    FAILED = "FAILED"
    NEVER_SUBSCRIBED = "NEVER_SUBSCRIBED"
    PAUSED = "PAUSED"

    