
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class CustomerEmailAddressMarketingState(EnumType):
    INVALID = "INVALID"
    NOT_SUBSCRIBED = "NOT_SUBSCRIBED"
    PENDING = "PENDING"
    SUBSCRIBED = "SUBSCRIBED"
    UNSUBSCRIBED = "UNSUBSCRIBED"

    