
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class DelegateAccessTokenDestroyUserErrorCode(EnumType):
    PERSISTENCE_FAILED = "PERSISTENCE_FAILED"
    ACCESS_TOKEN_NOT_FOUND = "ACCESS_TOKEN_NOT_FOUND"
    CAN_ONLY_DELETE_DELEGATE_TOKENS = "CAN_ONLY_DELETE_DELEGATE_TOKENS"
    ACCESS_DENIED = "ACCESS_DENIED"

    