
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class DeliveryLocalPickupTime(EnumType):
    ONE_HOUR = "ONE_HOUR"
    TWO_HOURS = "TWO_HOURS"
    FOUR_HOURS = "FOUR_HOURS"
    TWENTY_FOUR_HOURS = "TWENTY_FOUR_HOURS"
    TWO_TO_FOUR_DAYS = "TWO_TO_FOUR_DAYS"
    FIVE_OR_MORE_DAYS = "FIVE_OR_MORE_DAYS"

    