
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class DeliveryLegacyModeBlockedReason(EnumType):
    MULTI_LOCATION_DISABLED = "MULTI_LOCATION_DISABLED"
    NO_LOCATIONS_FULFILLING_ONLINE_ORDERS = "NO_LOCATIONS_FULFILLING_ONLINE_ORDERS"

    