
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class DiscountStatus(EnumType):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    SCHEDULED = "SCHEDULED"

    