
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class DiscountApplicationTargetSelection(EnumType):
    ALL = "ALL"
    ENTITLED = "ENTITLED"
    EXPLICIT = "EXPLICIT"

    