
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class DraftOrderStatus(EnumType):
    COMPLETED = "COMPLETED"
    INVOICE_SENT = "INVOICE_SENT"
    OPEN = "OPEN"

    