
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class FileContentType(EnumType):
    IMAGE = "IMAGE"
    FILE = "FILE"
    VIDEO = "VIDEO"
    EXTERNAL_VIDEO = "EXTERNAL_VIDEO"
    MODEL_3D = "MODEL_3D"

    