
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class FileStatus(EnumType):
    UPLOADED = "UPLOADED"
    PROCESSING = "PROCESSING"
    READY = "READY"
    FAILED = "FAILED"

    