
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class FileSortKeys(EnumType):
    FILENAME = "FILENAME"
    ORIGINAL_UPLOAD_SIZE = "ORIGINAL_UPLOAD_SIZE"
    CREATED_AT = "CREATED_AT"
    UPDATED_AT = "UPDATED_AT"
    ID = "ID"
    RELEVANCE = "RELEVANCE"

    