
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class FulfillmentOrderSortKeys(EnumType):
    ID = "ID"
    UPDATED_AT = "UPDATED_AT"
    RELEVANCE = "RELEVANCE"

    