
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class FulfillmentOrderMerchantRequestKind(EnumType):
    FULFILLMENT_REQUEST = "FULFILLMENT_REQUEST"
    CANCELLATION_REQUEST = "CANCELLATION_REQUEST"

    