
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class FulfillmentStatus(EnumType):
    PENDING = "PENDING"
    OPEN = "OPEN"
    SUCCESS = "SUCCESS"
    CANCELLED = "CANCELLED"
    ERROR = "ERROR"
    FAILURE = "FAILURE"

    