
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class FulfillmentOrderRescheduleUserErrorCode(EnumType):
    FULFILLMENT_ORDER_NOT_FOUND = "FULFILLMENT_ORDER_NOT_FOUND"

    