
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class MarketingActivityStatusBadgeType(EnumType):
    DEFAULT = "DEFAULT"
    SUCCESS = "SUCCESS"
    ATTENTION = "ATTENTION"
    WARNING = "WARNING"
    INFO = "INFO"

    