
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class MarketingActivityExtensionAppErrorCode(EnumType):
    NOT_ONBOARDED_ERROR = "NOT_ONBOARDED_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    API_ERROR = "API_ERROR"
    PLATFORM_ERROR = "PLATFORM_ERROR"
    INSTALL_REQUIRED_ERROR = "INSTALL_REQUIRED_ERROR"

    