
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class MarketingChannel(EnumType):
    SEARCH = "SEARCH"
    DISPLAY = "DISPLAY"
    SOCIAL = "SOCIAL"
    EMAIL = "EMAIL"
    REFERRAL = "REFERRAL"

    