
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class MarketLocalizableResourceType(EnumType):
    METAFIELD = "METAFIELD"
    METAOBJECT = "METAOBJECT"

    