
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class MediaWarningCode(EnumType):
    MODEL_SMALL_PHYSICAL_SIZE = "MODEL_SMALL_PHYSICAL_SIZE"
    MODEL_LARGE_PHYSICAL_SIZE = "MODEL_LARGE_PHYSICAL_SIZE"

    