
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class MenuUpdateUserErrorCode(EnumType):
    NOT_FOUND = "NOT_FOUND"
    NESTING_TOO_DEEP = "NESTING_TOO_DEEP"

    