
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class MenuDeleteUserErrorCode(EnumType):
    MENU_DOES_NOT_EXIST = "MENU_DOES_NOT_EXIST"
    UNABLE_TO_DELETE_DEFAULT_MENU = "UNABLE_TO_DELETE_DEFAULT_MENU"

    