
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class MetafieldValueType(EnumType):
    STRING = "STRING"
    INTEGER = "INTEGER"
    JSON_STRING = "JSON_STRING"
    BOOLEAN = "BOOLEAN"

    