
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class MetafieldCustomerAccountAccessInput(EnumType):
    READ_WRITE = "READ_WRITE"
    READ = "READ"
    NONE = "NONE"

    