
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class MetafieldDefinitionPinUserErrorCode(EnumType):
    NOT_FOUND = "NOT_FOUND"
    PINNED_LIMIT_REACHED = "PINNED_LIMIT_REACHED"
    ALREADY_PINNED = "ALREADY_PINNED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    DISALLOWED_OWNER_TYPE = "DISALLOWED_OWNER_TYPE"

    