
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class MetafieldDefinitionSortKeys(EnumType):
    ID = "ID"
    NAME = "NAME"
    PINNED_POSITION = "PINNED_POSITION"
    RELEVANCE = "RELEVANCE"

    