
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class MetafieldDefinitionAdminFilterStatus(EnumType):
    NOT_FILTERABLE = "NOT_FILTERABLE"
    IN_PROGRESS = "IN_PROGRESS"
    FILTERABLE = "FILTERABLE"
    FAILED = "FAILED"

    