
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class OnlineStoreThemeFileBodyInputType(EnumType):
    TEXT = "TEXT"
    BASE64 = "BASE64"
    URL = "URL"

    