
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class OnlineStoreThemeFilesUserErrorsCode(EnumType):
    NOT_FOUND = "NOT_FOUND"
    LESS_THAN_OR_EQUAL_TO = "LESS_THAN_OR_EQUAL_TO"
    THEME_FILES_CONFLICT = "THEME_FILES_CONFLICT"
    DUPLICATE_FILE_INPUT = "DUPLICATE_FILE_INPUT"
    ACCESS_DENIED = "ACCESS_DENIED"
    THEME_LIMITED_PLAN = "THEME_LIMITED_PLAN"
    FILE_VALIDATION_ERROR = "FILE_VALIDATION_ERROR"
    ERROR = "ERROR"

    