
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class OrderDisplayFulfillmentStatus(EnumType):
    UNFULFILLED = "UNFULFILLED"
    PARTIALLY_FULFILLED = "PARTIALLY_FULFILLED"
    FULFILLED = "FULFILLED"
    RESTOCKED = "RESTOCKED"
    PENDING_FULFILLMENT = "PENDING_FULFILLMENT"
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    ON_HOLD = "ON_HOLD"
    SCHEDULED = "SCHEDULED"
    REQUEST_DECLINED = "REQUEST_DECLINED"

    