
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class OrderCreateMandatePaymentUserErrorCode(EnumType):
    ORDER_MANDATE_PAYMENT_ERROR_CODE = "ORDER_MANDATE_PAYMENT_ERROR_CODE"

    