
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class OrderAdjustmentInputDiscrepancyReason(EnumType):
    RESTOCK = "RESTOCK"
    DAMAGE = "DAMAGE"
    CUSTOMER = "CUSTOMER"
    OTHER = "OTHER"

    