
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class OrderCancelReason(EnumType):
    CUSTOMER = "CUSTOMER"
    DECLINED = "DECLINED"
    FRAUD = "FRAUD"
    INVENTORY = "INVENTORY"
    STAFF = "STAFF"
    OTHER = "OTHER"

    