
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class OrderInvoiceSendUserErrorCode(EnumType):
    ORDER_INVOICE_SEND_UNSUCCESSFUL = "ORDER_INVOICE_SEND_UNSUCCESSFUL"

    