
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class PaymentReminderSendUserErrorCode(EnumType):
    PAYMENT_REMINDER_SEND_UNSUCCESSFUL = "PAYMENT_REMINDER_SEND_UNSUCCESSFUL"

    