
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class PaymentTermsCreateUserErrorCode(EnumType):
    PAYMENT_TERMS_CREATION_UNSUCCESSFUL = "PAYMENT_TERMS_CREATION_UNSUCCESSFUL"

    