
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class PaypalExpressSubscriptionsGatewayStatus(EnumType):
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
    PENDING = "PENDING"

    