
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class PriceListPriceUserErrorCode(EnumType):
    BLANK = "BLANK"
    PRICE_LIST_NOT_FOUND = "PRICE_LIST_NOT_FOUND"
    PRICE_LIST_CURRENCY_MISMATCH = "PRICE_LIST_CURRENCY_MISMATCH"
    VARIANT_NOT_FOUND = "VARIANT_NOT_FOUND"
    PRICE_NOT_FIXED = "PRICE_NOT_FIXED"

    