
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class PriceRuleShareableUrlTargetType(EnumType):
    HOME = "HOME"
    PRODUCT = "PRODUCT"
    COLLECTION = "COLLECTION"

    