
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class ProductImageSortKeys(EnumType):
    CREATED_AT = "CREATED_AT"
    POSITION = "POSITION"
    ID = "ID"
    RELEVANCE = "RELEVANCE"

    