
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class ProductMediaSortKeys(EnumType):
    POSITION = "POSITION"
    ID = "ID"
    RELEVANCE = "RELEVANCE"

    