
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class ProductOptionUpdateVariantStrategy(EnumType):
    LEAVE_AS_IS = "LEAVE_AS_IS"
    MANAGE = "MANAGE"

    