
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class PublicationCreateInputPublicationDefaultState(EnumType):
    EMPTY = "EMPTY"
    ALL_PRODUCTS = "ALL_PRODUCTS"

    