
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class QuantityPriceBreakSortKeys(EnumType):
    MINIMUM_QUANTITY = "MINIMUM_QUANTITY"
    ID = "ID"
    RELEVANCE = "RELEVANCE"

    