
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class RefundLineItemRestockType(EnumType):
    RETURN = "RETURN"
    CANCEL = "CANCEL"
    LEGACY_RESTOCK = "LEGACY_RESTOCK"
    NO_RESTOCK = "NO_RESTOCK"

    