
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class ReturnStatus(EnumType):
    CANCELED = "CANCELED"
    CLOSED = "CLOSED"
    OPEN = "OPEN"
    REQUESTED = "REQUESTED"
    DECLINED = "DECLINED"

    