
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class ReverseFulfillmentOrderThirdPartyConfirmationStatus(EnumType):
    ACCEPTED = "ACCEPTED"
    CANCEL_ACCEPTED = "CANCEL_ACCEPTED"
    CANCEL_REJECTED = "CANCEL_REJECTED"
    PENDING_ACCEPTANCE = "PENDING_ACCEPTANCE"
    PENDING_CANCELATION = "PENDING_CANCELATION"
    REJECTED = "REJECTED"

    