
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class ReverseFulfillmentOrderDispositionType(EnumType):
    RESTOCKED = "RESTOCKED"
    PROCESSING_REQUIRED = "PROCESSING_REQUIRED"
    NOT_RESTOCKED = "NOT_RESTOCKED"
    MISSING = "MISSING"

    