
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class SaleActionType(EnumType):
    ORDER = "ORDER"
    RETURN = "RETURN"
    UPDATE = "UPDATE"
    UNKNOWN = "UNKNOWN"

    