
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class SellingPlanRecurringDeliveryPolicyIntent(EnumType):
    FULFILLMENT_BEGIN = "FULFILLMENT_BEGIN"

    