
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class SellingPlanAnchorType(EnumType):
    WEEKDAY = "WEEKDAY"
    MONTHDAY = "MONTHDAY"
    YEARDAY = "YEARDAY"

    