
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class SellingPlanInterval(EnumType):
    DAY = "DAY"
    WEEK = "WEEK"
    MONTH = "MONTH"
    YEAR = "YEAR"

    