
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class SellingPlanGroupSortKeys(EnumType):
    NAME = "NAME"
    UPDATED_AT = "UPDATED_AT"
    CREATED_AT = "CREATED_AT"
    ID = "ID"
    RELEVANCE = "RELEVANCE"

    