
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class SellingPlanPricingPolicyAdjustmentType(EnumType):
    PERCENTAGE = "PERCENTAGE"
    FIXED_AMOUNT = "FIXED_AMOUNT"
    PRICE = "PRICE"

    