
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class ShippingPackageType(EnumType):
    BOX = "BOX"
    FLAT_RATE = "FLAT_RATE"
    ENVELOPE = "ENVELOPE"
    SOFT_PACK = "SOFT_PACK"

    