
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class ShopifyProtectEligibilityStatus(EnumType):
    PENDING = "PENDING"
    ELIGIBLE = "ELIGIBLE"
    NOT_ELIGIBLE = "NOT_ELIGIBLE"

    