
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class ShopBranding(EnumType):
    SHOPIFY_GOLD = "SHOPIFY_GOLD"
    SHOPIFY_PLUS = "SHOPIFY_PLUS"
    ROGERS = "ROGERS"
    SHOPIFY = "SHOPIFY"

    