
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class ShopifyProtectStatus(EnumType):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    PROTECTED = "PROTECTED"
    NOT_PROTECTED = "NOT_PROTECTED"

    