
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class SubscriptionContractLastPaymentStatus(EnumType):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"

    