
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class ThemeCreateUserErrorCode(EnumType):
    INVALID_ZIP = "INVALID_ZIP"
    ZIP_IS_EMPTY = "ZIP_IS_EMPTY"
    ZIP_TOO_LARGE = "ZIP_TOO_LARGE"

    