
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class ThemeUpdateUserErrorCode(EnumType):
    NOT_FOUND = "NOT_FOUND"
    TOO_LONG = "TOO_LONG"
    INVALID = "INVALID"

    