
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class TransactionVoidUserErrorCode(EnumType):
    TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND"
    AUTH_NOT_SUCCESSFUL = "AUTH_NOT_SUCCESSFUL"
    AUTH_NOT_VOIDABLE = "AUTH_NOT_VOIDABLE"
    GENERIC_ERROR = "GENERIC_ERROR"

    