
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class UnitSystem(EnumType):
    IMPERIAL_SYSTEM = "IMPERIAL_SYSTEM"
    METRIC_SYSTEM = "METRIC_SYSTEM"

    