
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class UrlRedirectBulkDeleteBySearchUserErrorCode(EnumType):
    INVALID_SEARCH_ARGUMENT = "INVALID_SEARCH_ARGUMENT"

    