
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class UrlRedirectBulkDeleteBySavedSearchUserErrorCode(EnumType):
    SAVED_SEARCH_NOT_FOUND = "SAVED_SEARCH_NOT_FOUND"
    INVALID_SAVED_SEARCH_QUERY = "INVALID_SAVED_SEARCH_QUERY"

    