
"""
This is autogenerated code. Do not edit directly.
"""    
from classes import EnumType

class WeightUnit(EnumType):
    KILOGRAMS = "KILOGRAMS"
    GRAMS = "GRAMS"
    POUNDS = "POUNDS"
    OUNCES = "OUNCES"

    