import json
from utils import camel_to_snake
import keyword
import logging

schema = json.load(open("./schema.json"))

types = schema["data"]["__schema"]["types"]

interfaces = [t for t in types if t["kind"] == "INTERFACE"]

"""
Object class template

class CustomInterfaceType(InterfaceType):
    class Fields:
        field_name = Field("fieldName", FieldType)
        list of fields (Field)

    possible_type_loaders = {
        "TypeName": TypeLoader
    }
"""
def generate_interface_class(interface_data: dict):
    import_filed_kinds = set()
    import_argument_kinds = set()
    import_block = set()
    attributes_block = ""
    fields_block = ""
    for field_data in interface_data["fields"]:
        field_name = _check_valid_identifier(field_data["name"])
        field_name = camel_to_snake(field_name)
        field_kind, field_type = _get_field_kind_and_type(field_data["type"])
        field_kind = _check_valid_identifier(field_kind)
        field_type = _check_valid_identifier(field_type)
        field_arguments, argument_kinds = _get_field_arguments(field_data["args"])
        arguments_block = "{\n            " + ",\n            ".join(field_arguments) + "\n        }" if field_arguments else ""
        import_filed_kinds.add(field_kind + "Field")
        import_argument_kinds.update(argument_kinds)
        fields_block += f"        {field_name} = {field_kind}Field(\"{field_data['name']}\", \"{field_type}\", {arguments_block})\n"
        import_block.add(f"    from schema.{field_kind.lower()}s.{camel_to_snake(field_type)} import {field_type}\n")
        attributes_block += f"    {field_name}: \"{field_type}\"\n"

    possible_types = []
    import_type_loaders = set()
    for possible_type in interface_data["possibleTypes"]:
        possible_type_kind, possible_type_name = _get_field_kind_and_type(possible_type)
        possible_type_name = _check_valid_identifier(possible_type_name)
        type_loader_name = possible_type_kind.capitalize() + "TypeLoader"
        import_type_loaders.add(type_loader_name)
        possible_types.append(f"\"{possible_type_name}\": {type_loader_name}")
    possible_types_block = ",\n        ".join(sorted(possible_types))
    class_code = f"""
\"\"\"
This is autogenerated code. Do not edit directly.
\"\"\"
from base_types import InterfaceType
from type_loaders import {", ".join(sorted(import_type_loaders))}
from fields import {", ".join(sorted(import_filed_kinds))}
{f"from arguments import {', '.join(sorted(import_argument_kinds))}" if import_argument_kinds else ""}
from typing import TYPE_CHECKING

if TYPE_CHECKING:
{"".join(sorted(import_block))}


class {interface_data["name"]}(InterfaceType):
    possible_type_loaders = {{
        {possible_types_block}
    }}
    class Fields:
{fields_block}
{attributes_block}
    """
    return class_code

def _get_field_kind_and_type(field_type: dict):
    if "ofType" in field_type and field_type["ofType"] is not None:
        return _get_field_kind_and_type(field_type["ofType"])
    return str(field_type["kind"]).lower().capitalize(), field_type["name"]

def _check_valid_identifier(identifier: str):
    snake_identifier = camel_to_snake(identifier)
    if not identifier.isidentifier() or keyword.iskeyword(identifier) or not snake_identifier.isidentifier() or keyword.iskeyword(snake_identifier):
        logging.warning(f"Identifier \"{identifier}\" is not a valid identifier")
        return f"_{identifier}"
    return identifier

def _get_field_arguments(arguments_data: list[dict]):
    arguemnt_kinds = set()
    arguments = []
    for argument_data in arguments_data:
        argument_name = _check_valid_identifier(argument_data["name"])
        argument_kind, argument_type = _get_field_kind_and_type(argument_data["type"])
        argument_type = _check_valid_identifier(argument_type)
        arguments.append(f"\"{camel_to_snake(argument_name)}\": {argument_kind}Argument(\"{argument_type}\")")
        arguemnt_kinds.add(argument_kind + "Argument")
    return arguments, arguemnt_kinds


for i in interfaces:
    class_code = generate_interface_class(i)
    # Create or replace the file
    with open(f"./schema/interfaces/{camel_to_snake(i['name'])}.py", "w") as f:
        f.write(class_code)
