import json
from utils import camel_to_snake, snake_to_camel
import keyword
import logging

schema = json.load(open("./schema.json"))

types = schema["data"]["__schema"]["types"]

objects = [t for t in types if t["kind"] == "OBJECT"]

# print object names in new lines
# print("\n".join([o["name"] for o in objects]))

#objects = objects[:1]


"""
Object class template

class CustomObjectType(ObjectType):
    class Fields:
        field_name = Field("fieldName", FieldType)
        list of fields (Field)
"""
def generate_object_class(object_data: dict):
    import_filed_kinds = set()
    import_argument_kinds = set()
    import_block = set()
    attributes_block = ""
    fields_block = ""
    for field_data in object_data["fields"]:
        field_name = camel_to_snake(field_data["name"])
        field_name = _check_valid_identifier(field_name)
        field_kind, field_type = _get_field_kind_and_type(field_data["type"])
        field_kind = _check_valid_identifier(field_kind)
        snake_field_type = camel_to_snake(field_type)
        snake_field_type = _check_valid_identifier(snake_field_type)
        field_type = _check_valid_identifier(field_type)
        field_arguments, argument_kinds = _get_field_arguments(field_data["args"])
        arguments_block = "{\n            " + ",\n            ".join(field_arguments) + "\n        }" if field_arguments else ""
        import_filed_kinds.add(field_kind + "Field")
        import_argument_kinds.update(argument_kinds)
        fields_block += f"        {field_name} = {field_kind}Field(\"{field_data['name']}\", \"{field_type}\", {arguments_block})\n"
        import_block.add(f"    from schema.{field_kind.lower()}s.{snake_field_type} import {field_type}\n")
        attributes_block += f"    {field_name}: \"{field_type}\"\n"
    class_code = f"""
\"\"\"
This is autogenerated code. Do not edit directly.
\"\"\"
from base_types import ObjectType
from fields import {", ".join(sorted(import_filed_kinds))}
{f"from arguments import {', '.join(sorted(import_argument_kinds))}" if import_argument_kinds else ""}
from typing import TYPE_CHECKING

if TYPE_CHECKING:
{"".join(sorted(import_block))}


class {object_data["name"]}(ObjectType):
    class Fields:
{fields_block}
{attributes_block}
    """
    return class_code


def _get_field_kind_and_type(field_type: dict):
    if "ofType" in field_type and field_type["ofType"] is not None:
        return _get_field_kind_and_type(field_type["ofType"])
    return snake_to_camel(field_type["kind"].lower()), field_type["name"]

def _check_valid_identifier(identifier: str):
    if not identifier.isidentifier() or keyword.iskeyword(identifier):
        logging.warning(f"Identifier \"{identifier}\" is not a valid identifier")
        return f"_{identifier}"
    return identifier

def _get_field_arguments(arguments_data: list[dict]):
    arguemnt_kinds = set()
    arguments = []
    for argument_data in arguments_data:
        argument_name = _check_valid_identifier(argument_data["name"])
        argument_kind, argument_type = _get_field_kind_and_type(argument_data["type"])
        argument_type = _check_valid_identifier(argument_type)
        arguments.append(f"\"{camel_to_snake(argument_name)}\": {argument_kind}Argument(\"{argument_type}\")")
        arguemnt_kinds.add(argument_kind + "Argument")
    return arguments, arguemnt_kinds


for o in objects:
    class_code = generate_object_class(o)
    file_name = camel_to_snake(o['name'])
    file_name = _check_valid_identifier(file_name)
    # Create or replace the file
    with open(f"./schema/objects/{file_name}.py", "w") as f:
        f.write(class_code)
